### ISSUE TITLE
Strangeness with `renamed_repositories`

### ISSUE THREAD

**Issue by colmbuckley** [alandtse/tesla#103]
## Describe the bug

I have been unable to install this integration from HACS for the past few days; although it works fine when manually installed as a custom_component. HACS spins indefinitely when trying to retrieve the repository information.

I don't know for sure, but I suspect that there's a circular referencs in `hacs.hacs` - I see:

```
        "renamed_repositories": {
            [...]
            "alandtse/tesla": "custom-components/tesla",
            "custom-components/tesla": "alandtse/tesla",
            [...]
        }
```

Should both of these entries exist?

**Comment by alandtse** [comment]
That's a HACS [bug](https://github.com/hacs/integration/issues/2296). I can't do anything about it here. It's fixed but not released. If you wipe your HACS data and restart that's one potential solution but again, I don't maintain HACS.

**Comment by colmbuckley** [comment]
Aha, thank you. Applying the linked patch has fixed the issue; hopefully it gets into an actual release soon.
