### ISSUE TITLE
TeslaFi Token - How?

### ISSUE THREAD

**Issue by shanelord01** [alandtse/tesla#104]
Hi team,

I’m trying to understand how TeslaFi can provide the token required. 

AFAIK TeslaFi does not provide you with access to copy or otherwise view the stored refresh token that allows their service to interact with your vehicle, as this would typically be a security vulnerability/risk and if your account is compromised & could allow for a hacker to access or control your vehicle.

Does this Tesla HACS integration connect with TeslaFi in a way I can’t see? If so - can this be done with services like Teslascope as well?

Thanks,
Shane.

**Comment by alandtse** [comment]
https://support.teslafi.com/en/communities/1/topics/16979-tesla-v3-api-tokens)

**Comment by shanelord01** [comment]
This link in and of itself doesn’t answer my questions. I’ve read it already before I posted.

**Comment by alandtse** [comment]
I don't support TeslaFi. You have to ask them. We just take the token generated by them. I don't know how they generate it nor is it something I bother with now. If you don't want to use TeslaFi, you can find another app to generate them for you.

**Comment by purcell-lab** [comment]
> This link in and of itself doesn’t answer my questions. I’ve read it already before I posted.

@shanelord01 follow the instructions provided at the teslafi link to generate a token, you then need to copy that refresh token into this HACS application when authenticating.
