### ISSUE TITLE
Integration not Loading with Home Assistant 2021.12

### ISSUE THREAD

**Issue by AlexandreKw** [alandtse/tesla#117]
## Version of the custom_component

I'm using the latest version this integration without HACS, refreshed the files yesterday (Dec.11th).

## Describe the bug

Right after upgrading the Home Assistant 2021.12 release on Dec 11th, the system raised a notification telling Tesla Custom Integration was not loaded.
When checking the logs it mentioned something with HTTP_UNAUTHORIZED no longer being allowed or available by HA Core. 

## Debug log

Unfortunately I've reverted back to 2021.11 right away since I had to leave and wanted a stable system.

**Comment by rsteckler** [comment]
You need to upgrade to Tesla integration 1.4 (within HACS)

**Comment by scottda4270** [comment]
I have the very same issue, dont know how to upgrade the integration as unbale to delete it now and unable to reinstall again. Can you share how i upgrade the installation to 1.4 please? I too am running the new 2021.12 version on HASS. thanks

**Comment by Sonusss** [comment]
Hi,
I just made a fresh install of HA 2021.12 with Tesla Custom Integration 1.4 installed from HACS and cannot add integration from components/integration. This integration doesn't show up

**Comment by ammarzuberi** [comment]
Just installed on a fresh 2021.12 installation, can't add the integration with the error:
```
Error
Config flow could not be loaded
```
Nothing in logs.
