### ISSUE TITLE
HACS continues to say "new repository" but cannot download/update

### ISSUE THREAD

**Issue by drlauridsen** [alandtse/tesla#122]
## Version of the custom_component
1.4.0

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

Custom integration originally installed via HACS userdefined repository, but suddenly the userdefined alandtse repository is gone, and it seems the custom Tesla integration is now available directly from the  HACS repository, since HACS keeps announcing that a new (Custom Tesla) repository is available.
I am however not able to download this new repository, and it seems I am stuck with this message no matter ehat I do, as seen in screenshot..

## Debug log

Two errors in log that I assume both are related to the issue..

```text

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.hacs
Source: custom_components/hacs/hacsbase/data.py:181
Integration: HACS (documentation, issues)
First occurred: 11.40.00 (1 occurrences)
Last logged: 11.40.00

Did not find alandtse/tesla (362700564)

---

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.hacs
Source: custom_components/hacs/tasks/setup_websocket_api.py:396
Integration: HACS (documentation, issues)
First occurred: 11.40.40 (21 occurrences)
Last logged: 11.59.47

Could not use repository with ID 0 ('NoneType' object has no attribute 'data')
![Screenshot_20211216-120009_Home Assistant](https://user-images.githubusercontent.com/61352332/146360054-456ea820-3f8c-41b7-a4c1-f7f95b513d94.jpg)


```

**Comment by jherby2k** [comment]
Same. Tried removing the custom repository from the list, but trying to add the Tesla integration just shows a spinner

**Comment by alandtse** [comment]
Report this to HACS. This isn't a bug here.

**Comment by alandtse** [comment]
You can manually wipe it out in the HACS configuration files, but that's for advanced users. Again, report to HACS since the issue is with HACS code.

**Comment by FalconUK** [comment]
Has been reported and fixed, but not rolled out yet.

https://github.com/hacs/integration/issues/2383
