### ISSUE TITLE
Integration does not show up under Configuration/Integrations (even after 2 HA restarts)

### ISSUE THREAD

**Issue by raoulteeuwenPE** [alandtse/tesla#13]
## Version of the custom_component

Latest, i'm unable to get it running even initially

## Configuration

I'm on HA OS on an RPi4, running HA 2021.8.6

## Describe the bug

I've added the repo to HACS, rebooted HA (twice), the integration shows up in HACS, but when i go to Configuration/Integrations and try to add it, the Tesla custom component does not show up. I wondered whether i would need to remove the Tesla integration that DOES show up, but have no idea if that is possible for my current config and if so, how.

## Debug log

Happy to supply logs, but as far as i can see, there are no relevant messages in the log that explain why the custom Tesla integration does not show up

```

**Comment by alandtse** [comment]
Hard refresh the integrations page.
