### ISSUE TITLE
Last_reset attribute resets too often / doesn't match sensor value

### ISSUE THREAD

**Issue by qJake** [alandtse/tesla#14]
## Version of the custom_component

v0.2.0

## Configuration

Installed via HACS. Configured via GUI config flow. No errors to report (this is a logic issue, not an error/exception).

## Describe the bug

The new energy management stuff in Home Assistant expects that you have an entity which "counts up" as usage is measured, and then at some point if that entity resets to 0, the `last_reset` attribute on the sensor should be updated to the current timestamp.

The current charge sensor is not behaving this way.

![image](https://user-images.githubusercontent.com/652006/129975567-0fcc29a8-4529-4138-881f-4b2647a0a2b5.png)

Because the `last_reset` attribute was updated without the sensor resetting, Home Assistant doesn't track any usage in the energy dashboard:

![image](https://user-images.githubusercontent.com/652006/129974870-7418b818-5bd5-4ba0-b73e-bedbd71f3644.png)

Essentially, the `last_reset` value must be updated nightly at 12 AM, and at the same moment, the sensor must be reset to 0.

## Future Thoughts

Today - in 2021.8.x - this is broken.

However, as of 2 days ago, they announced that this mechanism was "deprecated": https://developers.home-assistant.io/blog/2021/08/16/state_class_total (Of course, just as people were starting to implement this whole thing... 🙄)

And instead, they are adding `state_class: total_increasing` which represents an entity that counts up forever (unless HA restarts).

Ideally, since this custom component is developed much more rapidly than the official integration (ahem...OAuth... 🙄), it would be awesome if we could:

1. Fix the `last_reset` attribute issue and push a new version, so that energy monitoring starts working *today* for users that have this configured
2. Add support for `state_class: total_increasing` (or just use the existing `state_class: measurement` since it sounds like they are tweaking the logic behind this?) and wait for HA to release with these changes
3. Remove or end support for the `last_reset` attribute (or leave it... it probably doesn't hurt anything? HA just won't read it.)

I am not a strong Python developer, but if this is really easy to fix and someone could point me in the right direction, I can take a crack at it. I can write Python but I don't have familiarity with running tests or anything like that, sorry. 😅 I want to help if I can, because I think it would be really cool for HA to track my overall kWh used for charging my Tesla!

**Comment by alandtse** [comment]
The Tesla API doesn't provide a data point on when the energy added data is reset. Right now we estimate it based on when the value is less than the old value which appears to map to the reset behavior. I believe Tesla resets the value every time you reconnect the charger. It doesn't care what day it is. 

I'm not sure if there's a real solution to map it into HA's ecosystem, which you noted is changing. I'm inclined to wait till that's settled before trying to rewrite the behavior.

**Comment by qJake** [comment]
Ah, I see. I thought the incrementing logic was done within the addon here, not within Tesla's API itself.

That makes sense, I can understand wanting to wait.

And to your point, I think checking if the value is less will work - and if you detect that, you can just set the `last_reset` timestamp to that moment in time. I don't think it has to be midnight necessarily. And yeah... all of this could be going away, it sounds like. 🙂 

----

And for anyone else reading this thread, I can provide a really simple workaround that gets *close* to the correct kWh (off by maybe ±0.1kWh every 10kWh).

* Make a sensor template for current charger wattage, use the following template to calculate wattage using `A * V`, your sensor template should look similar to this:
    * `{{ (state_attr('sensor.xxx_charging_rate_sensor', 'charger_actual_current') | int) * (state_attr('sensor.xxx_charging_rate_sensor', 'charger_voltage') | int) }}`
* Use the hilariously-named *[integration* integration](https://www.home-assistant.io/integrations/integration/) (actually computes the Reimann sum of a graph) to calculate the daily sum of the wattage:  
```yaml
sensor:
  - platform: integration
    source: sensor.voyager_charger_wattage
    name: tesla_charged_kwh
    unit_prefix: k
    unit_time: h
    round: 2
```

Restart HA.

Before you use this entity, you have to go into the *Customizations* interface and set **device_class: energy** AND **unit_of_measurement: kWh**, or the Energy component in HA won't let you select it as an energy tracking source.

While you're in there, why not change the `friendly_name` to something, and icon to `mdi:car-electric` while you're at it? 😉 

![image](https://user-images.githubusercontent.com/652006/129990818-f49cf825-3e03-4ec4-a214-6942258bb918.png)

This resulting entity will be set up with the correct attributes to work directly with the Energy component. It has `state_class: measurement` and a `last_reset` which resets at midnight (along with the value). It should show up in your device consumption entity list appropriately:

![image](https://user-images.githubusercontent.com/652006/129990883-7c70961b-4a2b-461c-8490-55f13963f561.png)

A bit manual/hacky, but it works!

**Comment by alandtse** [comment]
Thanks. I'll leave this open so people can see your workaround.

To be honest, we likely need to expose another sensor to fit with the HA home paradigm. The problems with energy_added:
- it doesn't differentiate between charging inside or outside the home
- it doesn't account for pass through energy use. E.g., warming up the car when not charging the battery.

I haven't played with the API enough to determine if we have any actual energy measurements that are realtime. Perhaps there's an instantaneous power API we can provide and then HA can calculate it based on where the car is and for how long.

**Comment by alandtse** [comment]
Should be resolved by https://github.com/alandtse/tesla/releases/tag/v0.2.1
