### ISSUE TITLE
Some of the entities don't seem to work

### ISSUE THREAD

**Issue by Jens-Wymeersch** [alandtse/tesla#15]
## Version of the custom_component
Latest

## Configuration

```yaml
Logger: homeassistant
Source: custom_components/tesla_custom/sensor.py:108
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 11:08:57 (22 occurrences)
Last logged: 11:30:09

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/config/custom_components/tesla_custom/tesla_device.py", line 112, in refresh
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 501, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
  File "/config/custom_components/tesla_custom/sensor.py", line 108, in extra_state_attributes
    "charger_power": self.tesla_device.charger_power,
AttributeError: 'ChargingSensor' object has no attribute 'charger_power'
```

## Describe the bug

It might be not a bug, but I can't see or do the following :
- see the battery level of the car
- open or close the doors of the car (only the trucks)
- Tesla mileage sensor
- Tesla location tracker

## Debug log

```text

Add your logs here.

```

**Comment by alandtse** [comment]
You may have to remove and readd the integration from the integration page. For some reason you have an old version of teslajsonpy. Re-adding should force it to reinstall.

**Comment by Jens-Wymeersch** [comment]
@alandtse I've done what you said and initially all worked. I had to do a restart and now again I don't get any data anymore. Even the data I got before is missing. Any ideas ?

**Comment by alandtse** [comment]
The component will not wake a sleeping car unless you turn on the option to force cars awake. If the car is asleep, it will be unavailable until it wakes up.

**Comment by ultratoto14** [comment]
@alandtse i have the same problem of `AttributeError: 'ChargingSensor' object has no attribute 'charger_power'`
I use a docker image, I tried to remove/reinstall and after a restart it's still the same it's like HA is installing back the teslajsonpy 0.18.3, any advice ?

**Comment by alandtse** [comment]
That's precisely what is happening. If you update HA it will revert teslajsonpy. I can't do anything about that. You just need to remove and readd the integration or manually install the updated teslajsonpy.

**Comment by alandtse** [comment]
You actually don't have to remove it. Just start trying to add the custom component and it will do the install.
