### ISSUE TITLE
 google assistant voice 

### ISSUE THREAD

**Issue by lianfengcom** [alandtse/tesla#152]
## Version of the custom_component

1.6.0

## Describe the bug

It works perfectly fine when turning on the Tesla's air conditioner with google assistant voice, but when opening the trunk or front trunk, the google assistant prompts "You must enter a pin code to perform this action, but the app on the device is currently No pin code has been set", Tesla does not set a place to open the trunk PIN 

## Debug log

```text

Add your logs here
```

**Comment by alandtse** [comment]
This isn't Google Assistant voice so I'm not sure how I can fix it.
