### ISSUE TITLE
Change charging amps

### ISSUE THREAD

**Issue by jLynx** [alandtse/tesla#157]
Hi

Sorry if this in already implemented, but I cannot work out how to do it.

I see we have control to start and stop a charge, but is there a way to change current charge amps? #
![Screenshot_20220311-092656](https://user-images.githubusercontent.com/4393979/157748885-a860e03e-098b-4a69-864f-e0b31c7f6a14.jpg)

**Comment by alandtse** [comment]
Please search the issues. This has been asked and answered multiple times.

**Comment by jLynx** [comment]
Oh sorry I didn't see it initially. But now I see it here https://github.com/alandtse/tesla/issues/86
