### ISSUE TITLE
Charging polling takes too long.

### ISSUE THREAD

**Issue by hitnrun30** [alandtse/tesla#161]
Ok, I have read through the issues and updates but either it is me or something else that needs help..  

I want to close the Garage when it is open and I begin charging the car.  I plugged it in and nothing.  Waited a little bit, nothing.  I  know there is a best practice for this, but what would that be.  I'm thinking that when I come home set the polling interval to be 15 seconds and when the garage closes reset it to 660, but how do i do that and in Node Red BTW.

any help is appreciated.

**Comment by hitnrun30** [comment]
I was hoping for some kind of response.  Why even have polling, why not just setup to get push notifications.  API has a notifications piece.

**Comment by ehendrix23** [comment]
Have a look at https://github.com/alandtse/tesla/wiki/Polling-policy to see how polling works and how you can adjust it accordingly based on your need.

For notifications API, if you have a working example to be shared? From what I understand there is only polling or "stream" however for "stream" only 1 app can be getting the stream at a time. Which means if this integration uses that then the Tesla app on your phone can't use it.

**Comment by hitnrun30** [comment]
Well that makes a bit of sense.  But there must be a way, what if you have 2 cars and 2 phones.  Wouldn't they both be getting the stream?

**Comment by ehendrix23** [comment]
Might be. But not something we can implement unless Tesla informs everyone how to do it, or someone can reverse engineer.

**Comment by shred86** [comment]
I’ve never worked with websockets so I’m not much help here, but to get around the limitation of 1 connection, couldn’t a user just create a separate account to use with just HA?

**Comment by alandtse** [comment]
Closing given 3.0 rewrite.
