### ISSUE TITLE
Scedule departue

### ISSUE THREAD

**Issue by Dominic-070** [alandtse/tesla#164]
a switch and time field for setting a scheduled time for charging and HEVC, as in the Tesla App

**Comment by michaelsidenius** [comment]
That would be a good enhancement

**Comment by InTheDaylight14** [comment]
@alandtse @shred86 Wanted to run my thoughts by y'all before building. I was originally thinking the following:
- Select for Off/Sch Charge/Sch Depart
- Select for Off/All days/Weekday Only preconditioning and off-peak 
- Input_datetime for Sch Charge/Sch Depart/Off-Peak End

However there are no input_datetimes available to custom integrations. [Discussion](https://community.home-assistant.io/t/time-date-input-entity/410973).

This has me thinking about a different path. Exposing a service call for setting scheduled charging and setting scheduled departure with user friendly argument descriptions.

I would also want to add various attributes to the climate entity for the state of scheduled charge/depart, the time, status of weekend only, etc.

**Comment by alandtse** [comment]
Sounds good. Given there are other custom components who had to improvise, let's see if it makes sense to follow their service call style. Actually, I haven't checked if date time input exists for services in core that we could align with.

**Comment by maruel** [comment]
Just as a reminder, there's already two ways to implement preheating or adjust charging level:
- Use normal home assistant time based automation 
- Use a separate Google Calendar to schedule 

I use the latter and it works great! I share the calendar with all the family members, so anyone can set the preheating. For example I'm at the gym, I know I'll leave in 1h and it's cold outside, I set a one-off event in 45min in this calendar.

Separately to the feature, I feel some documentation (read: copy pastable examples) to steer users toward the already available ways would be good idea too?

**Comment by tmenguy** [comment]
@maruel sounds great the calendar part ... can you elaborate a bit on how you set it up? Thx!

**Comment by InTheDaylight14** [comment]
> Separately to the feature, I feel some documentation (read: copy pastable examples) to steer users toward the already available ways would be good idea too?

The Wiki of this project is a perfect place for write-ups like that.

**Comment by maruel** [comment]
I documented at https://maruel.ca/post/tesla_preheat/

**Comment by InTheDaylight14** [comment]
[Wiki entry](https://github.com/alandtse/tesla/wiki/Scheduled-Charging-and-Departure) to walk-through the existing functionality wrt scheduled departure and charging. 

Right now I'm thinking the dedicated service call are not worth it. It would look very similar to the info in that Wiki entry.

**Comment by tmenguy** [comment]
Hum I still do think having a direct "prepare car" at a given time is still a good idea as it seems that through the app the battery is prepared too.

**Comment by larstobi** [comment]
The features were merged in the upstream lib last week: https://github.com/zabuldon/teslajsonpy/pull/360
