### ISSUE TITLE
location_tracker incorrectly shows as Away

### ISSUE THREAD

**Issue by hemanthpai** [alandtse/tesla#176]
In Home Assistant, the location_tracker entity for my car has the state “Away” (or not_home) even though the car is at Home. Is this a bug or is additional configuration necessary to get the correct home/not_home values?

**Comment by alandtse** [comment]
Are the other sensors showing valid data?

**Comment by hemanthpai** [comment]
@alandtse - Yes, other sensors are showing valid data. For example, it’s showing the correct % of battery charged. Only the location seems to be incorrect. Specifically, the “not_home” state is incorrect. The longitude and latitude seem to be correct as they map to my home address.

**Comment by alandtse** [comment]
All device trackers do is provide the gps coords to HA. Stating whether something is home or not is an HA issue and not something the integration controls. Make sure you've actually defined a location as home.
