### ISSUE TITLE
How does this component polling algoritm compare to teslamate ? 

### ISSUE THREAD

**Issue by donnib** [alandtse/tesla#181]
Hi,
How does this component polling mechanish compare to teslamate's solution ? What if i want both e.g the log from Teslamate and the control that this component gives me ? What suggestion do you have ? I mean won't they both colide at some point then drain the battery ? 

From Teslamate [doc ](https://docs.teslamate.org/docs/integrations/home_assistant) it's stated 

`Whilst HomeAssistant provides an official component for Tesla vehicles, the component has not been updated recently, and does not have the sophistication of TeslaMate's polling mechanism, resulting in the component's default values keeping the vehicle awake and draining the battery.`

Is this still the case with this fork of the original component ? 

/donnib

**Comment by alandtse** [comment]
I don't know what Teslamate does. You can review the code or the wiki. https://github.com/alandtse/tesla/wiki/Polling-policy
