### ISSUE TITLE
Gather Voltage and Amp Data from Tesla

### ISSUE THREAD

**Issue by afreels95** [alandtse/tesla#185]
**Is your feature request related to a problem? Please describe.**
no. just want additional metrics exposed!

**Describe the solution you'd like**
I would like a current voltage & amps metrics when charging our tesla.

**Describe alternatives you've considered**
i have used other apis to gather this data but think it would be easy to implement looking at your code

**Additional context**

**Comment by alandtse** [comment]
This already exists in the charging rate sensor.

**Comment by afreels95** [comment]
I only see charging state of 1 or 0 on my charging sensor. is there documentation as to where this is?

**Comment by afreels95** [comment]
@alandtse I now see this in the attributes section on that sensor. But it doesnt look like Home Assistant uses these when exporting to prometheus metrics. Do you know anything about that? I am making a grafana dashboard using these metrics and would love to have them stored in Prometheus.
