### ISSUE TITLE
Sensor already exists, unique ID issue

### ISSUE THREAD

**Issue by jherby2k** [alandtse/tesla#193]
I'm seeing this in the log:

Platform tesla_custom does not generate unique IDs. ID tesla_model_3_425998_charging_state_data_sensor already exists - ignoring sensor.sonic_charging_state_data_sensor

Any way to fix this that doesn't involve reinstalling? Things seem to be working well otherwise.

## Version of the custom_component

2.0.1

**Comment by alandtse** [comment]
This is odd. It's unique because we use the last 6 digits of the VIN as you can see in the name. You don't have two instances installed or something else weird?
