### ISSUE TITLE
AttributeError: 'TeslaDataUpdateCoordinator' object has no attribute 'async_config_entry_first_refresh'

### ISSUE THREAD

**Issue by stepir** [alandtse/tesla#2]
Logger: homeassistant.config_entries
Source: custom_components/tesla/__init__.py:155 
First occurred: 10:45:30 AM (1 occurrences) 
Last logged: 10:45:30 AM

Error setting up entry stepir@yahoo.com for tesla
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tesla/__init__.py", line 155, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
AttributeError: 'TeslaDataUpdateCoordinator' object has no attribute 'async_config_entry_first_refresh'

**Comment by alandtse** [comment]
You'll need to be on 2021.4.0 or above unfortunately. https://github.com/home-assistant/core/releases/tag/2021.4.0

I'll add it in as a minimum requirement.
