### ISSUE TITLE
Issue when multiple cars are tied to the same tesla account (heated steering and seats)

### ISSUE THREAD

**Issue by rako77** [alandtse/tesla#207]
https://github.com/alandtse/tesla/blob/dbd4480a1c4445b610454dbc3ac8e2639bd7611f/custom_components/tesla_custom/helpers.py#L17

In this helper and specifically my issue is with an account with multiple cars fails to turn on the correct climate when enabling the heated steering wheel or heated seats.

The issue appears to be it's returning the first device in the array of devices without checking that the device is the right one, therefor In my home when the heated steering for Car \# 2 is triggered it turns on Car \# 1 climate.

**Comment by alandtse** [comment]
@megabytemb @ehendrix23 can either of you confirm please?

**Comment by megabytemb** [comment]
I wish i had the infrastructure to properly test this. haha
But i can see how that problem would arise.

I don't know exactly how I would fix it right now, But i'll get this done after work (or perhaps at lunch) today.

**Comment by ehendrix23** [comment]
@megabytemb Let me know if you need help. I have 2 cars in my account. Only 1 with heater steering wheel but both have heated seats. :-)

**Comment by megabytemb** [comment]
Created https://github.com/alandtse/tesla/pull/208 which i believe fixes this issue.
