### ISSUE TITLE
TypeError in controller.py update_interval()

### ISSUE THREAD

**Issue by j9brown** [alandtse/tesla#214]
## Version of the custom_component

v2.2.0, installed via HACS

## Configuration

No relevant configuration (configured via the UI).  This integration has been working fine for some time.

## Describe the bug

The integration threw an exception.

## Debug log

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tesla_custom/__init__.py", line 241, in update_listener
    controller.update_interval = config_entry.options.get(CONF_SCAN_INTERVAL)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 1591, in update_interval
    if value < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by j9brown** [comment]
As far as I know, I didn't change anything related to the Tesla integration.  I just found this in the log after restarting Home Assistant.

**Comment by alandtse** [comment]
It's staged for the next release. This shouldn't really impact your use, but if it breaks functionality, enable HACS beta and grab the dev branch.
