### ISSUE TITLE
use mdi:car-connected rather than mdi-update for the update-switch

### ISSUE THREAD

**Issue by arallsopp** [alandtse/tesla#22]
I find the Tesla's use of the word 'update' confusing. It seems to expose:

- *update available* - a sensor indicating that there is an update for the car's software.
- *update-switch* - an entity controlling whether HA continues to poll the car.

I think it would be better if we used the "mdi:car-connected" icon for the update-switch, and considered renaming it to 'enable polling' or 'enable scans' (as 'scan' is the word used in the configuration).

I've tweaked my dashboard to show these values so that I'm no longer confused, but I wonder if others might benefit from making the change in the actual integration.

![image](https://user-images.githubusercontent.com/2462104/132490448-30761cec-b91d-4c21-8007-ca4ec41103d1.png)

**Comment by alandtse** [comment]
This is a good point. Feel free to submit a PR if you want. We can just fix the display name without making it a breaking change.

**Comment by arallsopp** [comment]
Good work, @alandtse. Thanks.
