### ISSUE TITLE
Occupancy and Driver sensors

### ISSUE THREAD

**Issue by GitHubGoody** [alandtse/tesla#221]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Expose values available via the Tesla API as sensors to enable occupancy (# of total in vehicle and driver ID). From skimming the API, is_user_present and user_id could be a start for the driver. If there's any way to access the seat sensors, that could prove useful for determining which seat(s) are occupied and maybe who is in the car (especially if it had weight data).

**Describe alternatives you've considered**
N/A

**Additional context**
None

**Comment by alandtse** [comment]
Can you provide a link to where you saw this? I'm not seeing anything about this https://tesla-api.timdorr.com/.

**Comment by GitHubGoody** [comment]
The two examples I gave are under Vehicles > State and Settings > vehicle_data

https://www.teslaapi.io/vehicles/state-and-settings

I could not find the seat data, but they've got to be in there somewhere unless those are wired discrete to the airbags. But, since the seat heaters can be set to auto, that information is on the bus somewhere...hopefully exposed to the API too.

**Comment by alandtse** [comment]
Do you see how to convert `user_id` to something known? Have you confirmed that `is_user_present` is a valid boolean to say the user_id is in the car?

As for seat data question, yes it's possible it's not found or documented. But also, the API is documented by the community. No one's getting paid to do it so it's reliant on someone finding it and taking the effort to add it. If you do happen to see the data, you should submit a PR.

**Comment by GitHubGoody** [comment]
Sorry, but I wouldn't know where to start on either of those.

**Comment by mbrevda** [comment]
Yeah, bit of a chicken and egg to confirm the data without access to it. Is there some way to read data this via a custom API call?

**Comment by alandtse** [comment]
> Yeah, bit of a chicken and egg to confirm the data without access to it. Is there some way to read data this via a custom API call?

Enable debug on teslajsonpy. It will log all raw calls and responses that the component makes. To try specific commands use the custom api service. `service: tesla_custom.api` Search and you can find examples of how to use it. Known commands are [here](https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/endpoints.json).

**Please note I don't provide any support for the custom service since it's the same as running teslajsonpy directly to issue raw commands.**

**Comment by mbrevda** [comment]
Oh wow, thanks!

**Comment by GitHubGoody** [comment]
Nice! Thank you!

**Comment by GitHubGoody** [comment]
@alandtse Is the user_id attribute simply reflecting the account that's logged into the integration? I changed driver profiles in the car and forced an update. The user_id attribute didn't change.
