### ISSUE TITLE
Locks not showing in homekit

### ISSUE THREAD

**Issue by bryshaw** [alandtse/tesla#229]
I have the tesla integration and HomeKit integration. Any ideas why the trunk/frunk and door locks are not populating?

**Comment by lankthedank** [comment]
You need to add a new HomeKit integration only including 'lock' domains. It will create a new HomeKit accessory, and then new accessories for each relevant lock for the car. You can individually add the locks from the QR codes created in notifications.

**Comment by alandtse** [comment]
I don't use homekit but I assume this was resolved. Thanks @lankthedank
