### ISSUE TITLE
No module named 'teslajsonpy' after HA container update

### ISSUE THREAD

**Issue by hakong** [alandtse/tesla#230]
After a scheduled update of the HA container, tesla_custom no longer loads (afaik this was after the HA container update). I just tried updating HA, HACS, redownloading the tesla integration and restarting the HA container. Still does not load.

```
Log Details (ERROR)
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 22:03:47 (1 occurrences)
Last logged: 22:03:47

Setup failed for custom integration tesla_custom: Unable to import component: No module named 'teslajsonpy'
```

```
Home Assistant 2022.7.1
Frontend 20220707.0 - latest
```

```
Home Assistant Community Store
Integration version:	1.25.5
```

```
Tesla integration version:
v2.3.0
```

**Comment by alandtse** [comment]
Remove and reinstall the integration in HA or manually install the dependency. This is a HA issue that it didn't install the dependency.

**Comment by IvanBrazza** [comment]
I'm having the same issue on 2022.7 - I tried reinstalling the integration in HA (removed it entirely both from HA and HACS) but now I get an error saying the integration can't be set up in the UI and in the logs that it couldn't install teslajsonpy:

<img width="563" alt="Screenshot 2022-07-10 at 11 43 42" src="https://user-images.githubusercontent.com/1753736/178141536-35da6351-6ecc-45d6-965a-5715ad4cf46b.png">

<img width="1164" alt="Screenshot 2022-07-10 at 11 43 58" src="https://user-images.githubusercontent.com/1753736/178141557-da89930d-94cb-4a41-8ead-189acd0b2132.png">

**Comment by hakong** [comment]
I downgraded the HA container to 2022.6.7 to get it working again. I guess the 2022.7 update with Python 3.10 is what broke it.
@alandtse is this a HA issue or HACS issue?

**Comment by IvanBrazza** [comment]
> I downgraded the HA container to 2022.6.7 to get it working again. I guess the 2022.7 update with Python 3.10 is what broke it. @alandtse is this a HA issue or HACS issue?

You can also run `pip install teslajsonpy` in the container and it will work on 2022.7 in the meantime. Downside is that you have to run it every time the container is recreated...

**Comment by hakong** [comment]
That's strange, I tried that before downgrading and it didn't work. Or do I have to do it every time the container is started?
I ran `pip install teslajsonpy` and then restarted the container. That at least, did not work.
