### ISSUE TITLE
Car location offset

### ISSUE THREAD

**Issue by lisankai93** [alandtse/tesla#233]
Hello Alandtse, thanks for you great integration!

My model3 is in China. The gps info (longitude and latitude) obtained through teslamate's mqtt is accurate, but the gps info obtained through homeassistant's Tesla integration (v2.3.0) will always have a constant offset.

For example:

GPS info from teslamate：

- latitude: 23.127603 longitude: 113.318353 (actual location)

GPS info from Tesla integration v2.3.0:

- latitude: 23.125008 longitude: 113.323774

Thanks again.

**Comment by lisankai93** [comment]
I tried the GPS coordinate but the results are still different.

**Comment by alandtse** [comment]
Enable debug logging on teslajsonpy. You can then see the info the API is returning per vehicle. See if the GPS is being returned in a more accurate state by any field. If there's a better field, we can edit the component to use that for China users.

**Comment by alandtse** [comment]
The alternative is to figure out what Tesla mate is pulling.

**Comment by lisankai93** [comment]
> Enable debug logging on teslajsonpy. You can then see the info the API is returning per vehicle. See if the GPS is being returned in a more accurate state by any field. If there's a better field, we can edit the component to use that for China users.

I debug the teslajsonpy. Then I found the GPS info as follows:

"drive_state":{"corrected_latitude":23.125017,"corrected_longitude":113.323768,"gps_as_of":1657676900,"heading":70,_**"latitude":23.127622,"longitude":113.318358**_,"native_latitude":23.125026,"native_location_supported":1,"native_longitude":113.323779,"native_type":"gcj","power":0,"shift_state":null,"speed":null,"timestamp":1657676901911}

The correct GPS info is "latitude":23.127622,"longitude":113.318358, which is the same to the teslamate.

Can you update the relevant GPS for China users?

Thanks!

**Comment by alandtse** [comment]
Looking at this more, it looks like native_location_supported is intended to comply with Chinese regulations at the cost of accuracy. https://teslamotorsclub.com/tmc/threads/new-location-data-found-on-tesla-api.111022/. If someone wants to submit a patch so it's an option to ignore native_location, then I'd probably accept it.

**Comment by lisankai93** [comment]
> 

Yes. I think it's a easy way that for the Chinese tesla owners, just choose the latitude" and "longitude" instead of others.

**Comment by Emniroll** [comment]
User from China.
It's because the China use GCJ－02 coordinate system（all map apps in China） instead of normal WGS－84（google）.
You can modify device_tracker.py like this,and it works on my car.
```
"""Support for tracking Tesla cars."""
from __future__ import annotations

from homeassistant.components.device_tracker import SOURCE_TYPE_GPS
from homeassistant.components.device_tracker.config_entry import TrackerEntity

from . import DOMAIN as TESLA_DOMAIN
from .tesla_device import TeslaDevice

import math
import copy

async def async_setup_entry(hass, config_entry, async_add_entities):
    """Set up the Tesla binary_sensors by config_entry."""
    entities = [
        TeslaDeviceEntity(
            device,
            hass.data[TESLA_DOMAIN][config_entry.entry_id]["coordinator"],
        )
        for device in hass.data[TESLA_DOMAIN][config_entry.entry_id]["devices"][
            "devices_tracker"
        ]
    ]
    async_add_entities(entities, True)


x_pi = 3.14159265358979324 * 3000.0 / 180.0
pi = 3.1415926535897932384626  # π
a = 6378245.0  # 长半轴
ee = 0.00669342162296594323

def wgs84togcj02(lng, lat):
    dlat = transformlat(lng - 105.0, lat - 35.0)
    dlng = transformlng(lng - 105.0, lat - 35.0)
    radlat = lat / 180.0 * pi
    magic = math.sin(radlat)
    magic = 1 - ee * magic * magic
    sqrtmagic = math.sqrt(magic)
    dlat = (dlat * 180.0) / ((a * (1 - ee)) / (magic * sqrtmagic) * pi)
    dlng = (dlng * 180.0) / (a / sqrtmagic * math.cos(radlat) * pi)
    mglat = lat + dlat
    mglng = lng + dlng
    return [mglng, mglat]


def gcj02towgs84(lng, lat):
    dlat = transformlat(lng - 105.0, lat - 35.0)
    dlng = transformlng(lng - 105.0, lat - 35.0)
    radlat = lat / 180.0 * pi
    magic = math.sin(radlat)
    magic = 1 - ee * magic * magic
    sqrtmagic = math.sqrt(magic)
    dlat = (dlat * 180.0) / ((a * (1 - ee)) / (magic * sqrtmagic) * pi)
    dlng = (dlng * 180.0) / (a / sqrtmagic * math.cos(radlat) * pi)
    mglat = lat + dlat
    mglng = lng + dlng
    return [lng * 2 - mglng, lat * 2 - mglat]


def transformlat(lng, lat):
    ret = -100.0 + 2.0 * lng + 3.0 * lat + 0.2 * lat * lat + \
          0.1 * lng * lat + 0.2 * math.sqrt(math.fabs(lng))
    ret += (20.0 * math.sin(6.0 * lng * pi) + 20.0 *
            math.sin(2.0 * lng * pi)) * 2.0 / 3.0
    ret += (20.0 * math.sin(lat * pi) + 40.0 *
            math.sin(lat / 3.0 * pi)) * 2.0 / 3.0
    ret += (160.0 * math.sin(lat / 12.0 * pi) + 320 *
            math.sin(lat * pi / 30.0)) * 2.0 / 3.0
    return ret


def transformlng(lng, lat):
    ret = 300.0 + lng + 2.0 * lat + 0.1 * lng * lng + \
          0.1 * lng * lat + 0.1 * math.sqrt(math.fabs(lng))
    ret += (20.0 * math.sin(6.0 * lng * pi) + 20.0 *
            math.sin(2.0 * lng * pi)) * 2.0 / 3.0
    ret += (20.0 * math.sin(lng * pi) + 40.0 *
            math.sin(lng / 3.0 * pi)) * 2.0 / 3.0
    ret += (150.0 * math.sin(lng / 12.0 * pi) + 300.0 *
            math.sin(lng / 30.0 * pi)) * 2.0 / 3.0
    return ret

def location_convert(gcj) -> dict:
    tmp =copy.copy(gcj)
    new_lon,new_lat = gcj02towgs84(tmp.get("longitude"),tmp.get("latitude"))
    tmp["longitude"],tmp["latitude"]=new_lon,new_lat
    return tmp

class TeslaDeviceEntity(TeslaDevice, TrackerEntity):
    """A class representing a Tesla device."""

    def __init__(self, tesla_device, coordinator):
        super().__init__(tesla_device, coordinator)
        self.gcj02location = self.tesla_device.get_location()
        self.wgs64location = location_convert(self.gcj02location) if self.gcj02location else None

    @property
    def force_update(self):
        """Disable forced updated since we are polling via the coordinator updates."""
        return False

    @property
    def latitude(self) -> float | None:
        """Return latitude value of the device."""
        location = self.tesla_device.get_location()
        if location and location != self.wgs64location:
            self.gcj02location=location
            self.wgs64location=location_convert(location)
        return self.wgs64location.get("latitude") if self.wgs64location else None

    @property
    def longitude(self) -> float | None:
        """Return longitude value of the device."""
        location = self.tesla_device.get_location()
        if location and location != self.wgs64location:
            self.gcj02location=location
            self.wgs64location=location_convert(location)
        return self.wgs64location.get("longitude") if self.wgs64location else None
    
    @property
    def source_type(self):
        """Return the source type, eg gps or router, of the device."""
        return SOURCE_TYPE_GPS

    @property
    def extra_state_attributes(self):
        """Return the state attributes of the device."""
        attr = super().extra_state_attributes.copy()
        location = self.tesla_device.get_location()
        if location:
            attr.update(
                {
                    "trackr_id": self.unique_id,
                    "heading": location["heading"],
                    "speed": location["speed"],
                }
            )
        return attr


```

Can  alse add a determine statement like ”if location in China“,like this

```
  def out_of_china(lng, lat):
      """
      :param lng:
      :param lat:
      :return:
      """
      if lng < 72.004 or lng > 137.8347:
          return True
      if lat < 0.8293 or lat > 55.8271:
          return True
      return False
```

**Comment by alandtse** [comment]
> It's because the China use GCJ－02 coordinate system（all map apps in China） instead of normal WGS－84（google）.

Thanks for confirming. I don't know how this plays out with HA and relevant maps for China users. The conversion may be one option but it sounded like the non-WGS coordinates may be accurate. Do you know? Again, I'm happy to take a PR that swaps over appropriately for China users but I don't know the impact on such a change.

**Comment by Emniroll** [comment]
It may works like this.
Fisrt,HA's map works on WGS-84,and phone's location was gotten disrectly from the internet so it also base on WGS. So our phone location is currect.
But we use https://auth.tesla.""cn"" for authentication,we get data from the Tesla's server which for Tesla app's build-in map(In China) ,so it was alreadly coverted into GCJ.
And after covertting it back,I can see the Car shows exactly same position in HA's map and Tesla app's map. 
I'll try to make a PR later.

**Comment by lisankai93** [comment]
> It may works like this. Fisrt,HA's map works on WGS-84,and phone's location was gotten disrectly from the internet so it also base on WGS. So our phone location is currect. But we use [https://auth.tesla.""cn](https://auth.tesla.%22%22cn)"" for authentication,we get data from the Tesla's server which for Tesla app's build-in map(In China) ,so it was alreadly coverted into GCJ. And after covertting it back,I can see the Car shows exactly same position in HA's map and Tesla app's map. I'll try to make a PR later.

Thanks a lot.
