### ISSUE TITLE
Authentication error: Need oauth credentials

### ISSUE THREAD

**Issue by s450586793** [alandtse/tesla#235]
Logger: custom_components.tesla_custom.config_flow
Source: custom_components/tesla_custom/config_flow.py:190
Integration: Tesla Custom Integration ([documentation](https://github.com/alandtse/tesla/wiki), [issues](https://github.com/alandtse/tesla/issues))
First occurred: 15:36:28 (3 occurrences)
Last logged: 15:41:18

Authentication error: Need oauth credentials

**Comment by s450586793** [comment]
问题解决了。感谢来自哈斯比安的唐兴街1991。
对于那些来自中国的特斯拉车主，要成功登录，您需要将sso地址从 https://auth.tesla.com/ 更改为 https://auth.tesla.cn/。
找到teslajsonpy，文件 const.py，更正它并完成！

**Comment by alandtse** [comment]
This is unnecessary. Just change it when setting up your account.

![image](https://user-images.githubusercontent.com/7086117/180165991-9ebe5250-2d14-421c-b37a-239a7317eb43.png)

**Comment by s450586793** [comment]
您的来信已收到。谢谢。--------------江阴市万禾铝业科技有限公司   吴孝斌
