### ISSUE TITLE
update_available_sensor data doesnt match car or Tesla app

### ISSUE THREAD

**Issue by JerksonS** [alandtse/tesla#236]
The tesla app on my phone just told me there's an update available (2022.20.6)
Went to the car and confirmed its on wifi and there's an update available on-screen.... but the sensor returns "off" as if there is no update available and shows the correct installed version 2022.16.3

![image](https://user-images.githubusercontent.com/3187941/180580601-ec600f14-6df6-4233-be3d-741593b9a9d1.png)

After enabling debug log and restarting I found this in the log
`2022-07-22 19:31:45 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=binary_sensor.tess_update_available_sensor, old_state=None, new_state=<state binary_sensor.tess_update_available_sensor=off; friendly_name=Tess update available sensor @ 2022-07-22T19:31:45.956240-04:00>>`

**Comment by alandtse** [comment]
To avoid draining your battery, the component only updates after it detects a car has gone into a non-sleeping state. Give it some time to actually do an update.

You can also enable teslajsonpy debugging and look at the data we're getting. The relevant part of the json is here:

```json
    "software_update": {
      "download_perc": 0,
      "expected_duration_sec": 2700,
      "install_perc": 1,
      "status": "",
      "version": ""
    },
```

`status` should say available if it's available. If it doesn't, then the api may have changed but we'll still need to know what it says to do anything.
