### ISSUE TITLE
Keep last values after restart

### ISSUE THREAD

**Issue by dawiinci** [alandtse/tesla#251]
**Describe the solution you'd like**
After I restart HA I would like to see the latest values without waking up the Tesla. Right now all values are unknown. Especially after a short restart the values should remain because it is impossible that they have changed. In that case the car would be awake. 

**Additional context**
It is not possible to never restart HA and having to wake up the car for that is a waste of energy.
With values being unknown, automations will fail.

**Comment by shred86** [comment]
This is an issue on the teslajsonypy side (library that this integration uses) but we’re working on a rewrite for both so might be able to implement a solution. 

My initial thought would be to save the response from the VEHICLE_DATA endpoint to a JSON file and reference that file when the car state is “asleep”. Specifically:

- Only save the JSON file when the car state is “online”. 
- Reference the JSON file when the car state is “asleep”.
- Implement a time check where this only works if the JSON file was saved within a certain time period. I’m thinking hours so this should definitely cover an HA restart.

My only concern might be we would be writing a file to the system drive every 10 seconds. Probably minimal changes in most cases but not sure if that is reasonable. If it is in fact a concern (which I’m not sure it is), then maybe write to RAM (if there’s a way to do that) and save it periodically to the system drive. 

There would obviously have to be some clear documentation on how this works as to not confuse users as to the data they’re seeing (e.g. actual state data vs last data before changing to asleep).

Anyways, hopefully someone with more Python and HA dev experience can chime in. I think I’d be able to implement just as long as it makes sense.

**Comment by alandtse** [comment]
HA has a built in entity that saves state. I had a PR that converted to it, but HA rejected that saying it doesn't make sense for cars that move to restore state. Search my PRs to core and you should be able to find it.

**Comment by dawiinci** [comment]
That makes no sense to reject. If the car is parked I need the last value. Otherwise all automations will fail after a restart. 
It also keeps the last value as long as it doesn't restart. Could you make this optional?

**Comment by dawiinci** [comment]
Is there a way to enable that anyway? Otherwise I have to make virtual sensors...

**Comment by dawiinci** [comment]
Looks like after the rewrite nothing has changed. 

An option to update the values without waking the car would be nice - or make it keep the values after a restart.

It makes no sense to wake the car constantly and waste energy for that. Especially in times like that.

**Comment by dawiinci** [comment]
Any plans on this topic or should I start using helpers for that?

**Comment by alandtse** [comment]
Feel free to submit a PR if you want this enhancement.

**Comment by dawiinci** [comment]
My solution would be in HA only. Not sure how to integrate it into the plugin.

**Comment by xrado** [comment]
yes, this is really annoying, all entities become unknown,  no option to persist values between restarts?

**Comment by alandtse** [comment]
> yes, this is really annoying, all entities become unknown,  no option to persist values between restarts?

Turn on the option to wake up vehicles on restart.

**Comment by dawiinci** [comment]
I don't want to waste energy for that. But thanks.
