### ISSUE TITLE
 API breakage in version 2022.36 (it does not seem to include charge_to_max_range anymore)

### ISSUE THREAD

**Issue by mariogrip** [alandtse/tesla#275]
## Version of the custom_component

2.4.3

## Describe the bug

API breakage in version 2022.36, it does not seem to include charge_to_max_range anymore

This causes crash that also causes other entries becoming unavailable

I have created a patch for this on teslajsonpy that fixes this issue, see https://github.com/zabuldon/teslajsonpy/pull/351

## Debug log

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/tesla_device.py", line 129, in refresh
    self.tesla_device.refresh()
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/homeassistant/charger.py", line 121, in refresh
    self.__maxrange_state = data["charge_to_max_range"]
KeyError: 'charge_to_max_range'

```

**Comment by jaymunro** [comment]
Has your battery_sensor also become unknown?
Since I updated to 2020.36.1 the charge level for the car battery has become ‘unavailable’. Is this the case for you too @mariogrip?

**Comment by anhaff** [comment]
My battery sensor is 'unknown' since yesterday, may be even earlier, but the car was away from home for 2 days. ( "Home Assistant 2022.10.2, Supervisor 2022.09.1, Operating System 8.5, Frontend 20221006.0 - latest")

**Comment by mariogrip** [comment]
Yes, this is a sideeffekt of this.

Could we maybe bring in the fix @alandtse seems like more people stubble om this issue now

**Comment by alandtse** [comment]
Sure, please submit a PR bumping the dependency.

**Comment by mariogrip** [comment]
Did this fix the issues @jaymunro and @anhaff?

**Comment by iancg** [comment]
> Did this fix the issues @jaymunro and @anhaff?

I'd also had the same issue and this has resolved it for me.  Thanks all.

**Comment by anhaff** [comment]
Yes, thank you all.

**Comment by jaymunro** [comment]
Yes, battery % is once again reporting in correctly. Nice work.
