### ISSUE TITLE
Tesla integration spamming network DNS

### ISSUE THREAD

**Issue by utsnik** [alandtse/tesla#279]
Hey!

It seems like my Tesla integration is spamming my DNS records on the network. Is there any reason for this?

I've set polling to 660 seconds.

![image](https://user-images.githubusercontent.com/6017190/196509650-1d370bbc-9608-4d09-babb-2f38faf7e82e.png)

**Comment by cliffjao** [comment]
I suspect there's some issue reaching Tesla servers right now or something. If I reload the component (or Home Assistant), the component is stuck in the "Initializing" state for a long time. Started happening this morning.

**Comment by utsnik** [comment]
> I suspect there's some issue reaching Tesla servers right now or something. If I reload the component (or Home Assistant), the component is stuck in the "Initializing" state for a long time. Started happening this morning.

It's been like this since i installed it. A month ago or something. The integration works just fine though!

**Comment by cliffjao** [comment]
Ah, must be a different issue then.

**Comment by alandtse** [comment]
We don't do anything with the DNS. You can enable teslajsonpy to see the API calls. See https://github.com/alandtse/tesla/wiki/Polling-policy if you want the details. Any issues with spamming your DNS beyond the standard get calls as described in the docs are an issue with your HA machine.

[Basics of DNS caching](https://www.cloudns.net/blog/dns-cache-explained/)

**Comment by shred86** [comment]
The integration does pull data from the vehicle list endpoint every 60 seconds, which seems to match your DNS records. The vehicle list end point just tells us if the car is awake or asleep. The polling interval you can set (660 seconds) is when we pull data from the vehicle data endpoint (full vehicle data), if the vehicle is awake.

**Comment by alandtse** [comment]
I'll close this out since this looks like standard behavior get wise and related to system DNS caching. Please reopen if you determine it's something else

**Comment by wez** [comment]
I'm seeing many concurrent DNS requests for this domain coming from this integration, and it's reaching the max concurrent query limit of 512 on my DNS server.

I've had 1.8 million DNS queries today, but my poll interval is 660 seconds.  By my math, I would expect `86400/660 = 130` requests per day assuming just one request per poll interval: maybe that is ~50x larger based on the number of entities, but even so, that number should be much less than nearly 2 million. It feels as though something is very much amiss.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/117777/212253705-37dd9b5b-1481-4e27-893b-7006b8bbcfed.png">

This started happening earlier today:

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/117777/212254389-09f77f91-7a93-42f2-b629-f6b424aaefd9.png">

It seems as though there might be many concurrent tasks running all trying to get the same information at once?  Is there something a bit wacky in some retry logic in an error case that might stack up some polling tasks?

**Comment by wez** [comment]
I just remembered that I have a second pihole; this one has another 3 million DNS requests for this stuff today:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/117777/212255698-e5e954e1-0192-49d6-ade1-374373de973f.png">

**Comment by alandtse** [comment]
Are you sure your two dns servers aren't reflecting each other? You can enable debug on teslajsonpy for any connection attempts. As a comparison, I have 3 vehicles on my account and it looks like I only have 2,222 dns queries for yesterday per pihole. Given we poll every minute just for tesla server status (1440 min/day) and then will poll awake cars directly (increases the frequency based on multiple factors), ~2K seems like a reasonable amount.

**Comment by wez** [comment]
I'm fairly certain this isn't a loop; they both only talk to the upstream/recursive DNS, annd the other pihole servers don't appear as top clients in each others stats.
I've stopped one of them for the moment to see if the query volume falls, just to be sure.
