### ISSUE TITLE
Steering wheel heater switch

### ISSUE THREAD

**Issue by ad2022uk** [alandtse/tesla#283]
The steering wheel heater switch is no longer available in the new version.

**Describe the solution you'd like**
A return of steering wheel heater switch

**Describe alternatives you've considered**
None

**Additional context**
It was present in 2.x versions but missing in 3.x version

**Comment by alandtse** [comment]
@shred86 are you sure `steering_wheel_heater` is a capability indicator and not an activity indicator? I'm looking at the old code, and it looks like the steering wheel only becomes on/off if climate is on at some point so it used to enable climate to test for it.
https://github.com/alandtse/tesla/pull/188#issuecomment-1107360963.

If the old behavior is the steeing_wheel doesn't appear until climate has been on at least once, then we probably should document it.

**Comment by ad2022uk** [comment]
HVAC on does not invoke any other setting for steering wheel alone

**Comment by alandtse** [comment]
It's not that it invokes it. It's that the API cannot return data about a heated steering wheel if climate is off. In other words, until climate has been enabled, the API reports the heated steering wheel doesn't exist.

**Comment by ad2022uk** [comment]
How was it shown before then?
Was the API changed?

**Comment by shred86** [comment]
> @shred86 are you sure `steering_wheel_heater` is a capability indicator and not an activity indicator? I'm looking at the old code, and it looks like the steering wheel only becomes on/off if climate is on at some point so it used to enable climate to test for it. [#188 (comment)](https://github.com/alandtse/tesla/pull/188#issuecomment-1107360963).
> 
> If the old behavior is the steeing_wheel doesn't appear until climate has been on at least once, then we probably should document it.

Nope, definitely not sure on this one as this was something I was unable to test since my Model S doesn’t have a heated steering wheel. It probably is an activity indicator given it’s in the `climate_state` dictionary. I just assumed the key would also be available if the car had a heated steering wheel, but that doesn’t appear to be the case.  I’m guessing it’s one of those keys that _only_ appear when it’s on?

Unfortunately the option codes in the API are not usable, otherwise we could just use that to determine if the option should be available. I wonder what the Tesla app uses. If we can find a way to determine the capability exists for the vehicle, this should be an easy fix (I hope). Otherwise, we could always just create the entity for all vehicles but the goal was to only create entities for features that exist on the vehicle.

**Comment by freshfieldx** [comment]
I'm also seeing this

**Comment by bkr1969** [comment]
Can you look at the previous version?  It was working there.

**Comment by blair287** [comment]
Same issue heated steering wheel not showing up anymore was working in previous version.

**Comment by shred86** [comment]
If anyone with a heated steering wheel can provide the JSON response from VEHICLE_DATA, that would be helpful to see if there’s any keys we can use to determine if a vehicle has a heated steering wheel or not. To do this, you have to enable debug logging for teslajsonpy in Home Assistant. There’s a lot in the logs but if you search for vehicle_data, you should see when the request to that endpoint is made followed by a response with a large amount of data. I’m just looking for the [vehicle_config section](https://tesla-api.timdorr.com/vehicle/state/vehicleconfig) and [climate_state](https://tesla-api.timdorr.com/vehicle/state/climatestate).

**Comment by craigrouse** [comment]
@shred86 here you go!

```
  "climate_state":{
      "allow_cabin_overheat_protection":true,
      "auto_seat_climate_left":false,
      "auto_seat_climate_right":false,
      "battery_heater":false,
      "battery_heater_no_power":null,
      "bioweapon_mode":false,
      "cabin_overheat_protection":"Off",
      "cabin_overheat_protection_actively_cooling":false,
      "climate_keeper_mode":"off",
      "cop_activation_temperature":"High",
      "defrost_mode":0,
      "driver_temp_setting":20.0,
      "fan_status":0,
      "hvac_auto_request":"Override",
      "inside_temp":12.7,
      "is_auto_conditioning_on":false,
      "is_climate_on":false,
      "is_front_defroster_on":false,
      "is_preconditioning":false,
      "is_rear_defroster_on":false,
      "left_temp_direction":0,
      "max_avail_temp":28.0,
      "min_avail_temp":15.0,
      "outside_temp":12.5,
      "passenger_temp_setting":20.0,
      "remote_heater_control_enabled":false,
      "right_temp_direction":0,
      "seat_heater_left":0,
      "seat_heater_rear_center":0,
      "seat_heater_rear_left":0,
      "seat_heater_rear_right":0,
      "seat_heater_right":0,
      "side_mirror_heaters":false,
      "steering_wheel_heater":false,
      "supports_fan_only_cabin_overheat_protection":true,
      "timestamp":1667427926754,
      "wiper_blade_heater":false
   }
```

This is from my Model Y with steering wheel heater. The car is currently asleep and the climate control turned off, so it would appear the "steering_wheel_heater" flag property is returned regardless of climate control status. We also have wiper blade heaters on the Y (really it just heats a small section of the screen under the wiper blades to free them if they're frozen - the wiper blades themselves aren't heated). Hope this is useful - let me know if you need anything else.

**Comment by coreGreenberet** [comment]
> If anyone with a heated steering wheel can provide the JSON response from VEHICLE_DATA, that would be helpful to see if there’s any keys we can use to determine if a vehicle has a heated steering wheel or not. To do this, you have to enable debug logging for teslajsonpy in Home Assistant. There’s a lot in the logs but if you search for vehicle_data, you should see when the request to that endpoint is made followed by a response with a large amount of data. I’m just looking for the [vehicle_config section](https://tesla-api.timdorr.com/vehicle/state/vehicleconfig) and [climate_state](https://tesla-api.timdorr.com/vehicle/state/climatestate).

I've checked the option codes and I'm having a model Y with "STCP". According to https://github.com/timdorr/tesla-api/blob/master/docs/vehicle/optioncodes.md that is a "Steering Wheel" with Power. Which probably means heated like ST02 or ST33
