### ISSUE TITLE
Upgrade 3.0 unable to unlock charger door

### ISSUE THREAD

**Issue by copacetic82** [alandtse/tesla#285]
Regarding: "Changed trunk, frunk and charger door from lock to cover entities."

In the previous version I used the charger door lock entity to unlock the charge port i.e. to be able to remove the charging cable. With version 3.0 I am unable to do this. I have to unlock the door from the official Tesla app. 
- Opening and closing the charger door works when no cable is connected.
- Unlocking the car using the lock entity does not unlock the charger door/port
- Switching off the charger switch does not unlock the charger door/port

**Comment by alandtse** [comment]
Thanks. @shred86 I haven't tested this, but did we consider the case the charger door could lock? This may just mean having the cover issue an unlock command on open.

**Comment by ad2022uk** [comment]
Yes I can unlock the charger either.
I used to invoke the unlock_charger option before.

**Comment by shred86** [comment]
We're calling the same `CHARGE_PORT_DOOR_OPEN` as before. All we did was essentially change the previous charger door type from a lock entity to a cover entity, but the underlying functionality is identical.

However, I just realized one change in that before, I think you could issue the lock and unlock command regardless of the state the charger door was in. With the cover entity, if the door is open, it doesn't let you select the "open" button in the HA front end. However, you can call the "Cover: Open" service which will work. Just tested this on my Model S.

@copacetic82 If you unlock the car using the lock entity, you can't remove the charger cable? But if you unlock the doors from the official Tesla app, you can? That doesn't make sense to me either. I just tested this on my car and it works. I did notice if I unlock the doors, the charger port ring on the car is still green (latched) but I can remove the charger cable by pressing the button on the charger itself. When I issue the "Cover: Open" command, the charger port ring is white (unlatched) so I can just pull the charger plug out without pushing the button.

**Comment by copacetic82** [comment]
@shred86 I was referring to the charger door ("I have to unlock the door from the official Tesla app."), sorry for the misunderstanding. ;) 

I can confirm that (while charger door open and cable locked) the cover shows "open" in the frontend i.e. "open" button is grey and only "close" button can be pressed. Calling the entity manually as shown below does work (thanks for the tip!). I can build an automation to work around this and unlock the door from the frontend. :)

service: cover.open_cover
data: {}
target:
  entity_id: cover.tesla_model_3_charger_door
