### ISSUE TITLE
Disregard

### ISSUE THREAD

**Issue by ChipMIK1** [alandtse/tesla#286]
I use an IKEAS E1743 for commanding trunk open/close.  

"0" to "off is close trunk (short click) & "brightness_down" is open trunk (Long press) 

If i "short click" again while the trunk is travelling it will loose status of trunk & work opposite so "off" now is close & "brightness_down" is open trunk.

Unfortunately i dont know if this was an issue before 3.0 too.

**Comment by alandtse** [comment]
I'm not sure I understand. Are you saying you've modified your trunk? We are using the commands available from the official API. We unfortunately cannot handle modifications to vehicles differently. What is the behavior in the official app?

**Comment by ChipMIK1** [comment]
Sorry for wasting your time, i have redone way to many automations today and must have had something happend on first travel & then swapped functionality of the IKEA unit. Thank you very much for an outstanding integration. This one is truly super as HA now can adjust charging level to the car which is truly super when having solarpanels. Again, sorry. I have closed the issue now.
