### ISSUE TITLE
3.00 can’t get status from Frunk

### ISSUE THREAD

**Issue by fishredleung** [alandtse/tesla#298]
The status of the frunk won’t update after it is opened, unless pressing the forcing data update button.
Moreover, the new version are not friendly for the eclectic frunk users( after opening it, there’s no way to close it through HA commands) suggesting switch back to the lock presentation for the Frunk control.

**Comment by shred86** [comment]
We were under the impression there were no models with powered lift gates for the frunk - do you happen to know which models and roughly year they started adding that?

**Comment by fishredleung** [comment]
It’s a refit module
