### ISSUE TITLE
Unable to access login page

### ISSUE THREAD

**Issue by mischoe** [alandtse/tesla#3]
The linked website is opened with an error...

Die Website ist nicht erreichbargcg74bhlxv4rotu8wqhyv1z1u4dsie9s.ui.nabu.casa hat die Verbindung unerwartet geschlossen.
Versuchen Sie Folgendes:

Verbindung prüfen
Proxy und Firewall prüfen
ERR_CONNECTION_CLOSED

**Comment by alandtse** [comment]
Thanks. I don't use nabucasa so you may have to access HA while in your lan to set it up.

**Comment by stepir** [comment]
correct, access HA locally

**Comment by jun3280net** [comment]
@alandtse thanks for the update.  I installed through HACS and it fails during the initialization process.  Any idea what might be the problem - as I'm trying to update HA locally : localhost:8123
![image](https://user-images.githubusercontent.com/30555695/116623992-5cfd4e80-a904-11eb-8941-a3861c45cd44.png)

Thanks

**Comment by alandtse** [comment]
The component uses the setting for external_url under General Settings. It will not work properly if your HA is misconfigured. Please correct it there.

**Comment by jun3280net** [comment]
> The component uses the setting for external_url under General Settings. It will not work properly if your HA is misconfigured. Please correct it there.

Thank you so much @alantse!  Everything is back and working properly again! I honestly wouldn't have known, as I must have set that field very early on when I was learning how to setup Home Assistant.  Everything I do now is in the configuration.yaml file - so it never occurred to me I had defined it elsewhere. I've included a screenshot of what you were referring to for others who may run into the same problem :

![image](https://user-images.githubusercontent.com/30555695/116650616-c437f480-a93e-11eb-9c8b-e48eb0e2e143.png)

[https://www.home-assistant.io/docs/configuration/basic/](https://www.home-assistant.io/docs/configuration/basic/)

**Comment by alandtse** [comment]
Glad you got it working. 

For others, you may have to enable advanced settings under the user profile to see it.

The component actually tries the external url first. This allows the use of https if it's setup properly. The only weirdness is nabucasa doesn't appear to work properly but I'm not sure how the proxy works.

**Comment by jherby2k** [comment]
Worked fine with Nabu Casa for me...

**Comment by trekie86** [comment]
I am also unable to login, in fact I can't seem to find where the login prompt is at all. If I click on 'Update Information' in the integration page, nothing happens.
![image](https://user-images.githubusercontent.com/23006256/131202246-d0898635-df6b-435b-b659-42e0c8cd0376.png)

**Comment by alandtse** [comment]
You have to add the component on the integration page like any other integration.

**Comment by trekie86** [comment]
My bad, it wasn't showing up on the list before. After another restart it was there.

Attempting to authenticate now.

**Comment by trekie86** [comment]
It worked, took two attempts. It may be helpful to add the setup information to the README to prevent dummies like me from asking stupid questions.

**Comment by alandtse** [comment]
> It worked, took two attempts. It may be helpful to add the setup information to the README to prevent dummies like me from asking stupid questions.

Sorry, I thought it does say it?
> In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Tesla Custom Integration". If you are replacing core, remove the core integration before installing.

I guess I could say hard refresh the browser?

**Comment by trekie86** [comment]
You are right, that's step #8. I read it as in HCS, but that was me reading it wrong. The reason it took two attempts was because it seems if you fat finger a password, it results in a 500.

**Comment by alandtse** [comment]
Oh. That's not supposed to give you a 500. That's probably a bug. Do you have the logs still? If not, no biggie. If you run into it again, please open a new issue.

**Comment by trekie86** [comment]
I will check my service logs in the morning and see if there is anything interesting. Right now just operating through the Android app, I'll log onto the server tomorrow. 

Thanks for your help and patience.
