### ISSUE TITLE
Range and Odometer sensors now returns mi in stead of km

### ISSUE THREAD

**Issue by hufkens** [alandtse/tesla#301]
I upgraded to the v3.0.0 and changed my sensors, but then a new version came in v3.0.1 and after that upgrade the Odometer and the Range sensors report data in Miles and not Kilometers anymore. My Tesla is configured in km, and that has worked before.

Do I need to configure something?

**Comment by hufkens** [comment]
Seems to be a dashboard issue. I can update the unit there and the data is changed to km 👍

**Comment by riesi77** [comment]
I have the same issue - and I vote for reopening this one. Changing the unit is possible in manual dashboards, but not in the automatic one.

**Comment by hufkens** [comment]
OK. I will re-open the issue.

**Comment by TheDK** [comment]
Same here and thanks for pointing out that units can be changed within the entity (works fine for me)! Of course, would be best if it would be pulled from the car settings (I have km there as well, but got everthing in mi).

**Comment by purcell-lab** [comment]
Same issue here, I have my local settings in Home Assistant set to metric, but with v3.0.1 this integration is reporting in miles.

![Screenshot_20221025-070820](https://user-images.githubusercontent.com/79175134/197629833-c48de66c-8ead-40a0-8c93-4f3d01416265.png)

![Screenshot_20221025-070945](https://user-images.githubusercontent.com/79175134/197629932-4c190d5f-5155-41b8-8cb5-627ff142f4f4.png)

**Comment by shred86** [comment]
That’s odd. The change made was to specify the device class in HA so it _would_ be tied to the user’s Unit System setting. I’ll have to look at it again when I get home (currently out of town on a work trip) but when I tested it on my stand alone HA install, the conversion was working for temperature and range, so not really sure what’s going on. As it’s already been mentioned, you can specify the Unit of Measurement for each sensor now as well.

**Comment by purcell-lab** [comment]
> @purcell-lab Do you happen to remember what the Tesla API response reports for the vehicle_data endpoint for your vehicle? Are the ranges in miles or kilometers? I thought we looked at this before and determined it’s always reported in miles, and I checked this on my car by switching the displayed units to kilometers but the API was still reporting in miles so I assumed the conversion was happening on the vehicle and app side.

Yes, the API reports miles.

**Comment by FalconUK** [comment]
HA is now reporting km for me, even though the car is configured to display miles. 

I'm from the UK, so we measure short distances in metric, long distances in miles. Temperature in Celsius, pressure in PSI, etc......

I found /api/1/vehicles/{id}/data_request/gui_settings in the JSON API documentation. This could be what the App uses to use the correct units.
```
{
  "response": {
    "gui_24_hour_time": false,
    "gui_charge_rate_units": "mi/hr",
    "gui_distance_units": "mi/hr",
    "gui_range_display": "Rated",
    "gui_temperature_units": "F",
    "show_range_units": true,
    "timestamp": 1543187561462
  }
}
```

This doesn't answer the question on bar/PSI for tyre pressures though. Pretty sure the JSON reports bar, yet my app shows PSI.

**Comment by shred86** [comment]
I implemented this to conform to HA’s Unit System. We’re just passing the native value from the Tesla API to HA, which is miles for range and celsius for temperature. HA will then use whatever the user’s Unit System is set to (i.e. metric or imperial) to convert the values. For your case in the UK where you use a mix, you can just open the odometer, for example, click Settings and specify the Unit of Measurement for that entity.

That being said, there seems to be an issue where it’s not displaying correctly for some users which I’m still unable to determine why. Not sure if it’s something on HA’s end because everything appears to be implemented correctly on our end.

**Comment by tasranson** [comment]
For me Car is in Km (in Aus), new version displays the numbers as miles after install.  If I change the odometer entity units to km, it converts the data and displays correctly.  If I just change the dashboard units, the number does not convert.  I think thats a dashboard problem though, not an integration one.

**Comment by shred86** [comment]
@tasranson Yep you’re correct, I just got confirmation that it’s actually a HA core “issue”. They only implemented temperature conversion for the user’s Unit System setting. Apparently the others are currently in the works (distance, rates, etc.). For now, you can just specify the unit for the entities like you mentioned.

**Comment by FalconUK** [comment]
> For your case in the UK where you use a mix, you can just open the odometer, for example, click Settings and specify the Unit > of Measurement for that entity.

Where is this please, I can't see it on the entity settings in the GUI.

**Comment by purcell-lab** [comment]
Just started seeing this warning bring reported in 2022.11.beta

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 7:18:27 PM (1 occurrences)
Last logged: 7:18:27 PM

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for tesla_custom using this method at custom_components/tesla_custom/base.py, line 71: if self.hass.config.units.is_metric
```

**Comment by FalconUK** [comment]
Not therefor me, on either range or odometer, on v3.0.0, has this been changed in v.3.0.2?

**Comment by purcell-lab** [comment]
> Not therefor me, on either range or odometer, on v3.0.0, has this been changed in v.3.0.2?

This is a feature of Home Assistant core itself, which version are you running?

I think it was introduced with 2022.4
https://community.home-assistant.io/t/unit-of-measurement-2022-4/409860

**Comment by FalconUK** [comment]
I'm running 2022.10

**Comment by FalconUK** [comment]
Just updated via HACS to v3.0.2 and it's there now, and working correctly.

**Comment by craigsbits** [comment]
> Not there for me, on either range or odometer, on v3.0.0, has this been changed in v.3.0.2?
> 
> ![image](https://user-images.githubusercontent.com/77235040/198264256-f87d0ef3-1b94-4743-822b-b9d4787a220d.png)

At last.  I thought I was going **!¡##@ mad!

**Comment by hufkens** [comment]
Looks like this is no longer an issue, so I will close it. 
Thanks a lot for the responses and the work!

**Comment by purcell-lab** [comment]
Confirmed resolved, the update this morning and my ranges are back to km.
![Uploading Screenshot_20221115-073529.png…]()
