### ISSUE TITLE
Heated seat "auto" selection

### ISSUE THREAD

**Issue by craigsbits** [alandtse/tesla#302]
The official tesla app/car controls now has an "auto" selection for the heated seats.  The issue is that if I change the heat level from this integration (1,2,3) I can only then select 'off' .  I would like to have the "auto" feature to use in my pre-heating scripts.  This selection may be an extension of the "auto" selection for the Climate itself.  Currently the Climate control has 'off' and "heat/cool" in the integration, the latter works different from selecting "auto" in the car as that does reset the seat heaters to "auto".

**Comment by InTheDaylight14** [comment]
I don't see this documented in the [Unofficial Tesla API](https://tesla-api.timdorr.com/vehicle/commands/climate). It is using numeric level 0-3 for heater intensity. It will have to be figured out there, added to that repository, updated in teslajsonpy, then this integration can be updated. 


https://github.com/timdorr/tesla-api/issues/646

**Comment by coreGreenberet** [comment]
in climateState there are new parameters for that:

auto_seat_climate_left: false,
auto_seat_climate_right: true

In this case it was set to manual on the driver (left) and auto on the passenger (right) seat

**Comment by InTheDaylight14** [comment]
Yes, that is promising. The tesla API also has a command for ```remote_auto_seat_climate_request```. I'm guessing that only the front seat can be set to Auto. That is consistent with my Tesla app for a M3.

If anyone can set the back seats to Auto in the Tesla mobile app please comment here.

**Comment by craigsbits** [comment]
Yes only front seats can be set to auto.  The hvac in general can reset the seat heaters to auto.  The climate 'heat/cool' mode in integration does not exist on the car (is this meant to be 'auto'?) Selecting 'auto' on screen also resets the front seat heaters to auto.Craig

Sent from Sky Yahoo Mail on Android 
 
  On Thu, 1 Dec 2022 at 23:24, ***@***.***> wrote:   


Yes, that is promising. The tesla API also has a command for remote_auto_seat_climate_request. I'm guessing that only the front seat can be set to Auto. That is consistent with my Tesla app for a M3.

If anyone can set the back seats to Auto in the Tesla mobile app please comment here.
