### ISSUE TITLE
Solar data no longer available after 3.x upgrade

### ISSUE THREAD

**Issue by d2inco** [alandtse/tesla#303]
Performed the upgrade from 2.x to 3.0 Saturday night 10/22, and then the upgrade to 3.1 upgrade monday morning, 10/24

Solar Device ("Home Solar Integration") is showing "unavailable", as is the sensor "sensor.solar_panels".  I've confirmed that the data is present within the Tesla Android app.

![image](https://user-images.githubusercontent.com/5826360/197515484-2a4603b5-8379-4c38-bae2-754a0ba2d2ff.png)

**Comment by alandtse** [comment]
A reinstall of the integration into HA should have been enough. The HACS reinstall should normally not be necessary unless something is really wrong with the files and that would basically not load at all into HA.

Token issues will be detected and require a reauth. At that point, you'll get reprompted. The only other way to put a new token is to modify the config entry under `/config/.storage/core.config_entries` but you need to stop HA before you manually modify it's config files directly.
