### ISSUE TITLE
Nothing works after 3.0.1 update

### ISSUE THREAD

**Issue by bkr1969** [alandtse/tesla#304]
Everything is "Unavailable" and listed as "This entity is no longer being provided by the tesla_custom integration. If the entity is no longer in use, delete it in settings." Obviously something very wrong here.

**Comment by alandtse** [comment]
Remove and readd. The entities changed per the breaking notes for the 3.x.

**Comment by bkr1969** [comment]
OK. Deleting and reinstalling makes entities available again except everything has a new name.  Also, heated steering is no longer there.  Can we add it back in?
