### ISSUE TITLE
All entities unavailable after update

### ISSUE THREAD

**Issue by automaton82** [alandtse/tesla#313]
Running the latest v3.0.2 version of the Tesla integration in HACS, and ever since the latest update of everything (Home Assistant Core and Tesla integration) all entities are unavailable, even when the car is awake (waking up via the app).

There are no entries in the log about this, all of the entities say "restored" and look like this:

![image](https://user-images.githubusercontent.com/4467711/198356937-19439360-4c89-4d15-a342-e87dbd22a7a2.png)

And if you click on one:

![image](https://user-images.githubusercontent.com/4467711/198356990-2eaf4d4e-c1ea-47c8-aa2f-2222d868c9d2.png)

What can I do to debug and make this work? It worked for months with no issues. I've tried restarting the integration, HACS, Core, and the entire device with no change. If it requires a new refresh token I don't know how to input it (and it's not asking for one).

**Comment by alandtse** [comment]
Remove and reinstall. Entities were renamed as noted in the breaking changes.
