### ISSUE TITLE
Mini typo in hyperlink on config screen

### ISSUE THREAD

**Issue by rolandb5** [alandtse/tesla#319]
## Describe the bug

Small typo: telsafi.com instead of teslafi.com (someone managed to register it though)

<img width="433" alt="Screenshot 2022-11-01 at 06 48 59" src="https://user-images.githubusercontent.com/17737913/199167554-a758e1af-4575-4a40-9282-a23f381f3d2d.png">

**Comment by alandtse** [comment]
Thanks.#314 should fix this
