### ISSUE TITLE
Bring back release charge port option

### ISSUE THREAD

**Issue by aalllop** [alandtse/tesla#323]
**Is your feature request related to a problem? Please describe.**
On previous versions it had the option to release the charge port. Now it has disappeared 

**Describe the solution you'd like**
Bring back that entity

**Comment by jcmallorquin** [comment]
Yes, please. Very useful!

**Comment by Woempia** [comment]
Yes please, it was so useful. Really miss it

**Comment by agehall** [comment]
Yes! This was an essential part of my HA integration for my car!

**Comment by olsenab** [comment]
Same for me, the only function i used :)

**Comment by InTheDaylight14** [comment]
Do y'all have the entity name from before? I can try to keep it the same when adding this back.

I assume it was a lock. "lock.my_tesla_charge_port_latch"? @aalllop

**Comment by agehall** [comment]
it was called “lock.<car_name>_charger_door_lock” before.

Great if it can be kept but I don’t really care that much - the important thing is that I can use it. If I have to change a few automations, no problem…

**Comment by alandtse** [comment]
The name will have to change. The breaking change was because of that rename. @shred86 what was the convention you adopted here?

**Comment by agehall** [comment]
Are you sure it was just the name that changed? I thought this was caused by the charge port entity becoming a door instead of a lock...

**Comment by alandtse** [comment]
Yes there were other changes but the name change itself would've been considered breaking because the type (e.g., lock) was removed from the end of entities. Breaking changes means users have to fix stuff as it's not seamless. Since shred wanted to do that anyway, we bundled a bunch.

**Comment by agehall** [comment]
Sure, but a breaking name change is not a big deal IMHO - that just means I have to spend 10 minutes adjusting my integrations. If the entity disappears completely, which was the case here, we are kind of stuck unless one goes down the route of using the custom api service.

**Comment by shred86** [comment]
This was addressed in [this issue](https://github.com/alandtse/tesla/issues/285). The functionality is still there, you just have to call the cover open service.
