### ISSUE TITLE
Deprecated function warning - is_metric

### ISSUE THREAD

**Issue by drlauridsen** [alandtse/tesla#326]
You might already be aware of this, but latest HA update shows this warning... just to make sure we are ready for future versions..

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 09.31.43 (1 occurrences)
Last logged: 09.31.43

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for tesla_custom using this method at custom_components/tesla_custom/base.py, line 71: if self.hass.config.units.is_metric

**Comment by SylvainGa** [comment]
Hi, as this fix been moved to the main branch? I installed that integration last weekend and noticed that warning today.

**Comment by alandtse** [comment]
No. This will be moved when it actually may impact people. No sense forcing people to upgrade HA because of a deprecation warning.

**Comment by SylvainGa** [comment]
Make sense. Not much time left though. According to the message in the log, it will stop working in Home Assistant 2023.1

**Comment by tubalainen** [comment]
Looks like a dupe: https://github.com/alandtse/tesla/issues/442
