### ISSUE TITLE
Remaining Charge Time

### ISSUE THREAD

**Issue by mbrevda** [alandtse/tesla#348]
Would be great to expose the remaining charge time. I'd consider calculating this via a template but the battery capacity doesn't seem to be exposed. If this data is not available, this can be closed.

edit: [`time_to_full_charge`](https://www.teslaapi.io/vehicles/state-and-settings#:~:text=%22-,time_to_full_charge,-%22%3A%200.0) seems to be available. Perhaps the FR here should be to retrieve data from the API?

**Comment by alandtse** [comment]
Isn't it already exposed under `sensor.XXX_charging_rate` as an attribute? Are you saying you want it as a sensor too?

@InTheDaylight14 FYI

**Comment by mbrevda** [comment]
`rate` is km/h, I was hoping to see total remaining time

**Comment by alandtse** [comment]
You mean this? 
![image](https://user-images.githubusercontent.com/7086117/202094936-33def6e4-5bf0-4646-9ac1-b8eef853231e.png)

**Comment by mbrevda** [comment]
Yes. exactly. Thank you!

**Comment by mbrevda** [comment]
Actually, yea - a sensor (especially as a datetime thingy) would probably be pretty useful (for example, lots simpler to include in a glance card). Would that be possible?

**Comment by InTheDaylight14** [comment]
Updated the PR. I kept the same format of "1.25" hours to full charge

**Comment by alandtse** [comment]
Actually, given we have that value as an attribute, can we do it as a timestamp? It's basically now + value.

**Comment by InTheDaylight14** [comment]
PR has been updated the be a timestamp

**Comment by alandtse** [comment]
Thanks. I did have an additional question about one of your typing hints that is holding up my merging. Can you take a look please? https://github.com/alandtse/tesla/pull/349/files/538a0b0ca01e882994a3bc4c029746ec3c57f7ca#diff-bcce858d816475bf667bae799ffc7a925ada091914b9045bb8cfa8fc0b7ad2b1R477

**Comment by InTheDaylight14** [comment]
> Thanks. I did have an additional question about one of your typing hints that is holding up my merging. Can you take a look please? https://github.com/alandtse/tesla/pull/349/files/538a0b0ca01e882994a3bc4c029746ec3c57f7ca#diff-bcce858d816475bf667bae799ffc7a925ada091914b9045bb8cfa8fc0b7ad2b1R477

Alright, I think its good now

**Comment by mbrevda** [comment]
Great to see this released! Seems this value always defaults to `now()`. While the _correct_ value when not charging is debatable, I'm not sure `now()` is the most intuitive value here. Thoughts?

**Comment by InTheDaylight14** [comment]
I was thinking about that but couldn't come up with a default value that makes sense. 

Maybe we just don't update the value if the the timer has reached 0. And we initialize the sensor with ```now()``` on HA start-up.

**Comment by mbrevda** [comment]
yeah, thats sounds better.

**Comment by InTheDaylight14** [comment]
Alright, the solution I found withing my ability is to have the sensor return "Unknown" when the remaining time is 0.0. 

This will keep the database from filling up with all the state changes every few seconds when not charging.
