### ISSUE TITLE
reCAPTCHA error message

### ISSUE THREAD

**Issue by RamEliC** [alandtse/tesla#35]
I recently installed the addon and cannot authenticate due to the CAPTCHA not functioning.  

I'm using a public DNS record to access HA remotely (over HTTPS using LetsEncrypt).

![image](https://user-images.githubusercontent.com/11785846/132957206-c99fb719-907a-45bb-9bad-a59d879b3d27.png)

**Comment by omelhus** [comment]
Update to the latest version of the component (released this morning) and use Auth App for Tesla on iOS or Tesla Tokens on android to create a new refresh token.

The component has moved away from the proxy/captcha workaround.

See https://github.com/alandtse/tesla/releases
