### ISSUE TITLE
Tesla always online since version 3.1.0

### ISSUE THREAD

**Issue by peerkn** [alandtse/tesla#353]
Hello, 
since version 3.1.0 my car is always online. Going back to version 3.0.2 the car goes in offline mode. I tested wlan on/off, sentry on/off, usb on/off nothing helps only restore to version 3.0.2 helps.
Is it a problem in this version?
Thanks
Peer

**Comment by alandtse** [comment]
No. There was no code to change the online behavior. The version downgrade is unlikely to change anything. You could try enabling debug logging to see when the component contacts the car or Tesla. This is described on the wiki pages.

**Comment by peerkn** [comment]
Dear Alan Tse,

thank you for your answer. You gave me the hint for the error. I think
there must be an error in strings.json, because you changed no code. The
old one has 1.107 bytes, the new one has 1.108 bytes. When i replace the
new strings.json with the old one, my tesla is going  to sleep.

Thanks for your great work.

Best regards

Peer Knoth

Am Fr., 18. Nov. 2022 um 22:14 Uhr schrieb Alan Tse <
***@***.***>:
