### ISSUE TITLE
Now frunk / trunk / charger are covers ... it leads to issue in HomeKit, expose lock too?

### ISSUE THREAD

**Issue by tmenguy** [alandtse/tesla#354]
Hi, 

First thanks for the amazing integration.

**Is your feature request related to a problem? Please describe.**
In v3.0 frunk/trunk/window/charger port are now covers (vs lock before)
My issue is that I map all of those in HomeKit (to do some automation from here and have better access to those functionalities) ... and cover in home assistant are rightfully mapped as HomeKit window covering .... so when you say "open all the window blind in the house" to siri ..... it actually will open my "real" blind, and my whole Tesla ... even if my car is far from home :(

**Describe the solution you'd like**
keeping everything like it is today ... but adding back the lock entities (in addition to the cover ones) so we can choose by enabling / disabling entities the way we want to handle those elements.

Thanks for reading :) ... and more than happy to assist
BR
Thomas

**Comment by alandtse** [comment]
This may be a case where you need to exclude the cover from Home kit or HA. It also may be an HA enhancement to not expose certain items to Homekit. We are not likely to bring back the old architecture because cover is the most appropriate entity of all the available ha entity types.

**Comment by tmenguy** [comment]
Hi, 

Yes I can already not expose the covers if I want to homekit it is already possible in HA.
Understood your point of view anyway no pb. Will fork the project, or find a may in yaml to expose a switch entity from a cover if possible.

BR
Thomas

**Comment by tmenguy** [comment]
Hi,

Just so you know, I get this solved through a simple YAML solution, so for anyone interested:

-do not expose Tesla cover anymore in HomeKit in your yaml configuration:
-add in your yaml configuration:
`
lock:
  - platform: template
    name: Model 3 de Thomas Charger Door
    unique_id: model_3_de_thomas_charger_door_lock_YAML
    value_template: "{{ is_state('cover.model_3_de_thomas_charger_door', 'closed') }}"
    lock:
      service: cover.close_cover
      target:
        entity_id: cover.model_3_de_thomas_charger_door
    unlock:
      service: cover.open_cover
      target:
        entity_id: cover.model_3_de_thomas_charger_door         
  - platform: template
    name: Model 3 de Thomas Frunk
    unique_id: model_3_de_thomas_frunk_lock_YAML
    value_template: "{{ is_state('cover.model_3_de_thomas_frunk', 'closed') }}"
    lock:
      service: cover.close_cover
      target:
        entity_id: cover.model_3_de_thomas_frunk
    unlock:
      service: cover.open_cover
      target:
        entity_id: cover.model_3_de_thomas_frunk
  - platform: template
    name: Model 3 de Thomas Trunk
    unique_id: model_3_de_thomas_trunk_lock_YAML
    value_template: "{{ is_state('cover.model_3_de_thomas_trunk', 'closed') }}"
    lock:
      service: cover.close_cover
      target:
        entity_id: cover.model_3_de_thomas_trunk
    unlock:
      service: cover.open_cover
      target:
        entity_id: cover.model_3_de_thomas_trunk
  - platform: template
    name: Model 3 de Thomas Window
    unique_id: model_3_de_thomas_window_lock_YAML
    value_template: "{{ is_state('cover.model_3_de_thomas_windows', 'closed') }}"
    lock:
      service: cover.close_cover
      target:
        entity_id: cover.model_3_de_thomas_windows
    unlock:
      service: cover.open_cover
      target:
        entity_id: cover.model_3_de_thomas_windows
`

**Comment by tmenguy** [comment]
So issue can be closed ...
