### ISSUE TITLE
Valet Mode

### ISSUE THREAD

**Issue by alexbeatle** [alandtse/tesla#355]
Requesting a feature to add valet mode enable\disable as a switch.

**Comment by InTheDaylight14** [comment]
@alandtse I'm thinking a service call for this one. That way the pin can be entered as a parameter of the service call. 

An alternative would be asking for the valet pin in the config flow and using it when turning a valet mode switch on/off. If someone were to change their pin they would need to reconfigure the integration. That doesn't seem like the best solution, although users are probably not changing the pin very often. 

Thoughts?

**Comment by alexbeatle** [comment]
+1 for the service call with the pin as the parameter.

**Comment by alandtse** [comment]
> @alandtse I'm thinking a service call for this one. That way the pin can be entered as a parameter of the service call. 
> 
> An alternative would be asking for the valet pin in the config flow and using it when turning a valet mode switch on/off. If someone were to change their pin they would need to reconfigure the integration. That doesn't seem like the best solution, although users are probably not changing the pin very often. 
> 
> Thoughts?

We can store via a config flow and edit with an option flow. I wonder if there's a service call to update that data programmatically. Does HA have that yet?

**Comment by alandtse** [comment]
> +1 for the service call with the pin as the parameter.

Custom API should already allow for this. If we're making something specific, we might as well leverage whatever UI options HA provides.
