### ISSUE TITLE
Vehicle battery sensor doesn't match car/app, uses SOC instead of uSOE

### ISSUE THREAD

**Issue by carleeno** [alandtse/tesla#359]
## Version of the custom_component

3.1.0

## Describe the bug

Noticeable in the colder months: the battery level through this integration does not match the app or car's reported battery level. This is because this integration appears to be using the battery SOC (state of charge) rather than the uSOE (usable state of energy).
The SOC doesn't change in cold weather as the amount of charge in the battery is technically the same, but the usable energy decreases in low temperatures. This is why the battery values shown in the app and in the car display use the uSOE value which reflects that less energy is available (along with the snowflake icon).

The Vehicle State API has uSOE available as `charge_state.usable_battery_level`, I'm happy to create a PR (in teslajsonpy as well) but wanted to start the discussion if the main battery sensor should match the car/app, or if a second sensor for usable battery should be created instead. We could even add a snowflake attribute that sets true when there is >= 2% difference between the 2 values to also match the car/app behavior.

**Comment by alandtse** [comment]
Thanks for bringing this up. I don't live in a cold climate so wouldn't have known about this. Given that I don't think HA has a native way to address this, I think it's really our choice on what makes the most sense for users. I'd lean toward matching the app behavior to avoid confusion. For advanced users, we could expose an additional sensor or attribute. That could also be gated by an option flag.

If you want to just propose something that makes sense to you, we can leave it in an open PR for a little bit before integrating to see what the reaction is. But to be honest, it may be best to just release and see if anyone really complains one way or the other before changing it.

**Comment by carleeno** [comment]
awesome, thank you, I'll spin a pr to update the existing battery sensor to reflect the app/car (uSOE); and add a "raw_soc" attribute for those who may want to show if their battery is cold for example (I personally would then make a template sensor to add a snowflake icon to my dashboard)

**Comment by alandtse** [comment]
I'll hold off on the next release to get this in too.

**Comment by carleeno** [comment]
thanks, will create the pr shortly
