### ISSUE TITLE
Add sensor data transfer (upload/download)

### ISSUE THREAD

**Issue by KirkKirk** [alandtse/tesla#369]
Is it possible to be added a sensor for data UPLOAD / DOWNLOAD?
That will help to trace communication between the car and the mothership.

**Comment by carleeno** [comment]
I was taking a look at the raw api data (as I'm working on collecting various data for some tests) and unfortunately it doesn't contain any data upload/download stats, or anything related such as fsd saved clips or software update download.

It seems the only option for tracing comms between the car and cloud is to monitor usage via your wifi router (which of course won't include anything over LTE).

**Comment by KirkKirk** [comment]
cheers
