### ISSUE TITLE
Config flow - missing attribute labels

### ISSUE THREAD

**Issue by bdr99** [alandtse/tesla#37]
## Version of the custom_component
1.0.0

## Configuration
N/A

## Describe the bug
When I go to Configuration -> Integrations and select tesla_custom, the attribute labels are missing in the config flow form, so I can't tell what I'm supposed to enter into these fields. See below screenshot.

![image](https://user-images.githubusercontent.com/2292715/133328950-d81cc0e0-76f0-4ae7-a00e-cee84eeb8029.png)

HA version: 2021.9.3

## Debug log
N/A

**Comment by omelhus** [comment]
What language is HA set to?

You say you select tesla_custom? Not “Tesla Custom Integration”? It sounds like HA hasn’t loaded translations at all. Have you tried a forced refresh in the browser?

(The first field is email, second is refresh token)

**Comment by bdr99** [comment]
> 
> 
> What language is HA set to?

English.

> You say you select tesla_custom? Not “Tesla Custom Integration”? It sounds like HA hasn’t loaded translations at all. Have you tried a forced refresh in the browser?
> 
> (The first field is email, second is refresh token)

Yes, it appears as "tesla_custom". I tried a hard refresh but no change. Tried restarting HA multiple times. Also tried in an incognito window, with a different browser entirely, and with a different computer. 
![image](https://user-images.githubusercontent.com/2292715/133330478-cba72fb7-9efa-4d05-86fa-1ab6b045c4c9.png)

**Comment by bdr99** [comment]
I figured it out. I had put the integration in `custom_components` in a folder called `tesla`, not `tesla_custom`. Didn't know this mattered.
