### ISSUE TITLE
vehicle Time charging complete sensor incorrect

### ISSUE THREAD

**Issue by purcell-lab** [alandtse/tesla#374]
## Version of the custom_component

v3.3.1

## Describe the bug

Time left attribute reports correct 1.33 hrs
new Time charging complete sensor report 13 hours which is incorrect.

![image](https://user-images.githubusercontent.com/79175134/204169213-dbceafd6-1338-4431-a1ef-29608eecd970.png)

**Comment by alandtse** [comment]
Make sure HA has your correct timezone. We're using that to determine what `now()` is.  It's possible that the sensor should return in UTC instead of locale timeone, but I haven't looked.

**Comment by purcell-lab** [comment]
My timezone is GMT+10 and is set correctly in HA.

![Screenshot_20221128-185031](https://user-images.githubusercontent.com/79175134/204222839-eccd4119-1fa9-43f8-b80b-da828db95bb3.png)

So it could be the UTC offset that is missing.
