### ISSUE TITLE
[Question] Will setting the charge limit to the same existing value wake the car if it's asleep?

### ISSUE THREAD

**Issue by cliffjao** [alandtse/tesla#379]
Will setting the charge limit to the same existing value wake the car if it's asleep?

**Comment by cliffjao** [comment]
Did a quick test and it looks like it does... Car changed from Disconnected to Connected state even though it's the same value. Would it make sense to only wake the car if the value actually changes?

**Comment by alandtse** [comment]
It could be added as a feature assuming we know the state without waking up. It woke up because you sent a command. We don't check for whether the command is useless.
