### ISSUE TITLE
how to install teslajsonpy in HA?

### ISSUE THREAD

**Issue by iambbbb** [alandtse/tesla#38]
how to install teslajsonpy in HA?
i googled it but still have no idea.

**Comment by omelhus** [comment]
HA installs it for you when you activate the component.

**Comment by alandtse** [comment]
Specifically if you add the integration, HA should check the version of teslajsonpy.  If you have logging enabled on info, it should show you.
```bash
2021-09-15 00:18:31 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of teslajsonpy~=0.20.0
```

**Comment by iambbbb** [comment]
I mean how to update to the latest one??

**Comment by omelhus** [comment]
Remove the existing integration, restart HA a couple of times, reinstall custom component.
