### ISSUE TITLE
Heated Seat Not Updating When Climate Off

### ISSUE THREAD

**Issue by InTheDaylight14** [alandtse/tesla#392]
## Describe the bug

Changing the heated seat selector when the climate is off results in the following response
```
{'response': {'reason': 'cabin comfort remote settings not enabled', 'result': False}
```

If the climate is turned on and then the selector is changed it follows the expected behavior of successfully changing the heated seat setting. 

Interacting with a heated seat setting in the Tesla Apps turns on the climate. Possible solution is to add a check if the climate is on, if not turn climate on, then change the heated seat setting. If the selection is Off and the climate is Off then no change would need to be made as we are sure the heated seats are off. 

Possible risk: Users might not expect the entire climate system to turn on when changing the selector.

**Comment by alandtse** [comment]
Follow whatever the official app does. I think that will align with people's expectations. HA doesn't give us a good way to provide feedback to users. I guess we could do a notification if there's an error...
