### ISSUE TITLE
Make remote start go away from HomeKit

### ISSUE THREAD

**Issue by dawiinci** [alandtse/tesla#399]
Since the latest version I have a remote start button in HomeKit. I have never added it, I only use the climate control. I guess this is somehow linked though. 

I specifically checked and the button is not enabled in the HomeKit configuration. I even enabled/disabled it with no luck.

**Comment by alandtse** [comment]
You need to filter it via HA or Homekit.

**Comment by dawiinci** [comment]
Yes, but I am filtering it by not selecting the switch "remote start", yet it still appears in HomeKit.

**Comment by alandtse** [comment]
I'm not sure what you think we can do here to solve that bug.

**Comment by alandtse** [comment]
Just disable the entity in Tesla if it bothers you.

**Comment by dawiinci** [comment]
If I disable it, it still shows up in HomeKit. Just shown as not responding. 

I removed the climate controls and it also removed the remote start. After adding the climate again remote start didn't show up again. 

Seems fixed. Not sure where the bug originated. 

Thanks for your help.
