### ISSUE TITLE
Feature Request Tracking Entity 

### ISSUE THREAD

**Issue by Madbeefer** [alandtse/tesla#40]
I am glad that this integration works, I was wondering if the tracker entity would be something that could be put into this version?

**Comment by alandtse** [comment]
It's already there:
![image](https://user-images.githubusercontent.com/7086117/133576794-05595817-2a26-4efd-8e9c-e807f6c0a9b4.png)

**Comment by Madbeefer** [comment]
Weird, it doesn't seem to show up for me.

**Comment by Madbeefer** [comment]
Even odder, is I tried re-installing to see if it would add in the tracking entity now it won't authenticate.

**Comment by alandtse** [comment]
Please open a new issue using the template.
