### ISSUE TITLE
Estimated Battery Range Sensor 

### ISSUE THREAD

**Issue by craigrouse** [alandtse/tesla#412]
**Is your feature request related to a problem? Please describe.**
The Tesla API exposes "Ideal Battery Range" (based on rated range), and "Estimated Battery Range", based on recent consumption figures. The Estimated Range (`est_battery_range`) is not surfaced by this integration, but I used it in the old integration through the raw charging state data. 

**Describe the solution you'd like**
Add estimated range sensor

**Describe alternatives you've considered**
There aren't any, since the raw data fields aren't exposed in v3.

**Additional context**
I still feel there's value in exposing the old raw data sensors per this [issue](https://github.com/alandtse/tesla/issues/294).

**Comment by alandtse** [comment]
Just to clarify, we made a decision in the rewrite to not expose the raw json like we used to to and instead encourage people to contribute new sensors. It was a balance between only allowing power users to have access or getting the sensors available for non-power users. While not a perfect overlap, power users are more likely to have the motivation/skillset to submit a PR and given the rewrite was intended to make it easier to add stuff, I think we've been noticing more contributions too.

We could revisit that decision in the future, but I'd like to at least try for a few more months.

**Comment by craigrouse** [comment]
I totally get it @alandtse, and agree there has been a good uptick in contributions. Perhaps eventually, all the raw data can be exposed as individual sensors where it makes sense, but disabled by default for the ones less likely to be used.
