### ISSUE TITLE
Missing Battery percentage

### ISSUE THREAD

**Issue by alex4988** [alandtse/tesla#417]
Hi Guys,
with last update(3.6.0) i can't visualize battery percentage of my Tesla M3 LR '21, why? But i can manage my windows/door/hvac ecc...

Best Regards,
Alessandro

**Comment by alandtse** [comment]
Please provide more details including screenshots. I'm not sure if you're saying that it's unavailable or missing or whatever.

**Comment by arjungopisetty** [comment]
I'm having the same issue after the most recent update (v3.6.0). The estimated range percentage and mileage entities are no longer present. Here's a screenshot from my HA dashboard showing the missing sensors:
<img width="491" alt="Screen Shot 2022-12-10 at 12 39 57 PM" src="https://user-images.githubusercontent.com/5950166/206874466-c7fb8762-d0b3-4c99-8cd1-a9d1836e85bb.png">

## Logging

Here's (possibly) related log messages:
```text
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:175
First occurred: 12:34:11 PM (1 occurrences)
Last logged: 12:34:11 PM

Error unloading entry runipg@gmail.com for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 498, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 262, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 175, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!.
```

```text
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 12:29:25 PM (2 occurrences)
Last logged: 12:35:00 PM

Unable to prepare setup for platform tesla_custom.sensor: Platform not found (cannot import name 'UnitOfPressure' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

**Comment by carleeno** [comment]
it looks like UnitOfPressure was only added in 2022.11, so it's pretty recent. We may have jumped the gun to start using it so soon, I don't see that they have announced when the old units will be removed (and we still use the old units in other places)
https://developers.home-assistant.io/blog/2022/10/26/new-unit-enumerators/

I can push a pr to use the old pressure units for now until they announce when it will be deprecated.

**Comment by arjungopisetty** [comment]
Thanks for fixing this issue! I am on version 2022.10.5.
