### ISSUE TITLE
chinese not work

### ISSUE THREAD

**Issue by Archaeus** [alandtse/tesla#421]
i cant use in China，what is the auth inChina？ 
![JBD84$53~QIGWL1WHJX8MFY](https://user-images.githubusercontent.com/36544054/206915267-4e8a1785-c36a-4e3c-946c-f6b6120d3f76.png)

**Comment by Archaeus** [comment]
![Uploading $%]Y%CBS1}RH{HB9MD58D1B.png…]()
how to fix this address

**Comment by Archaeus** [comment]
![$% Y%CBS1}RH{HB9MD58D1B](https://user-images.githubusercontent.com/36544054/206915490-3264d923-0f51-48d6-a546-4a288cbe3086.png)

**Comment by alandtse** [comment]
Use auth.tesla.cn instead.

**Comment by Archaeus** [comment]
> Use auth.tesla.cn instead.

i have a try,but it not work.
