### ISSUE TITLE
Tesla just Unavailable

### ISSUE THREAD

**Issue by elamnr** [alandtse/tesla#430]
![Screenshot 2022-12-13 at 2 24 09 PM](https://user-images.githubusercontent.com/61445773/207436636-4751c4bc-354f-4087-bea5-9a63b12c517d.png)
My connection using the HACS installed Tesla integration in HA has just stopped working. I've tried everything short of deleting and re-adding the car through the integration, but I don't want to take that step because I worry that I will have to re-set up all the automations and scripts I've done over time because it will be a new entity. Is there a way to reset or test the connection to Tesla's servers? I can't find anything prompting me for my Tesla username or token, so I don't know where to go to test these.

**Comment by Hubro** [comment]
If you just updated the integration, it seems you're just going to have to delete and re-add the integration, unfortunately.

See: https://github.com/alandtse/tesla/discussions/428

**Comment by alandtse** [comment]
That's the likely answer.
