### ISSUE TITLE
New 'Auto' front seat heater mode not correct

### ISSUE THREAD

**Issue by craigsbits** [alandtse/tesla#433]
This new 'auto' mode recently added to the integration (thanks to all involved) does not appear to be working for the right seat heater (uk drivers).   The left seat heater (passenger) is working fine!  All other setting for high/medium/low/off are working.  It is odd that the passenger side is working correctly so hopefully this is a simple fix. 

As I said this is a RHD vehicle.  Does the integration work for LHD as we have not had any reports to date.

**Comment by alandtse** [comment]
The commands should have been left and right side so shouldn't care about RHD vs LHD unless Tesla flips something. @InTheDaylight14 any thoughts?

**Comment by InTheDaylight14** [comment]
Turns out the seat ID map is different for ```remote_seat_heater_request```. I think we try the above PR and see if that fixes the behavior for everyone. 

If not I'd bet there is a configuration option that points to RHD and we can switch up the mapping based on that.

**Comment by InTheDaylight14** [comment]
@craigsbits Can you confirm if v3.7.1 fixed this issue for RHD?
