### ISSUE TITLE
Some signal to trigger on if heading home

### ISSUE THREAD

**Issue by anhaff** [alandtse/tesla#436]
I would like to be able to make home assistant react when I activate "navigate to home" in the car.

Not sure if this is possible - it would mean the API has to expose this action or at least a destination lat/long position.

It could be in the form of an attribute of the location tracker.  The current position is there already

**Comment by InTheDaylight14** [comment]
Check out the just released v3.7.0

It has a destination location tracker. That device_tracker state will change to "Home" if the vehicle is actively navigating Home. 

There is also an attribute under the new arrival_time sensor called "Destination". That will also show "Home" or the name of any destination that is being navigated to. Ex. an address, or name of a store like "Home Depot"

**Comment by anhaff** [comment]
Thanks. Did not know about 3.7.0 when I asked

Appears to be the right thing. Will check it out next time I am away from home with the car.
