### ISSUE TITLE
Fart button/switch

### ISSUE THREAD

**Issue by tubalainen** [alandtse/tesla#438]
**Is your feature request related to a problem? Please describe.**
I would like to trigger my Tesla to fart if a `person `is detected (via Frigate/AI) on the driveway.

**Describe the solution you'd like**
For the Tesla to play the fart sound via the external speaker. 

**Describe alternatives you've considered**
None

**Additional context**
The feature is a new one, came with the new Tesla FW - 2022.44.25.1

**Comment by enzo2** [comment]
Thanks for quickly addressing this. Looking forward to advancing the state of the art in emissions testing.

**Comment by tubalainen** [comment]
Oh owo! Thanks for the release, but for some reason the new button isnt exposed for me,. Dont know why.

**Comment by peter-funktionIT** [comment]
> for some reason the new button isnt exposed for me,. Dont know why.

For me it showed up as a disabled diagnostic button at my Tesla model. You just need to enable it.

Appreciate this new important feature, thank you contributors :+1:
