### ISSUE TITLE
is_metric is deprecated

### ISSUE THREAD

**Issue by floow77** [alandtse/tesla#442]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 08:59:46 (1 occurrences)
Last logged: 08:59:46

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for tesla_custom using this method at custom_components/tesla_custom/base.py, line 71: if self.hass.config.units.is_metric

## Version of the custom_component
V3.7.1

**Comment by InTheDaylight14** [comment]
Duplicate https://github.com/alandtse/tesla/issues/326
