### ISSUE TITLE
[Question] charge not started via switch

### ISSUE THREAD

**Issue by pbathuk** [alandtse/tesla#461]
## Version of the custom_component
V3.8.1

## Configuration
Configured though UI - can post the setup, but all defaults 
```yaml
Add your logs here.
```

## Describe the bug
It's more of a question than a bug, but could be a bug.
I have been using the automation for quite sometime.
The automation is quite simple (it does lots but all basic if then steps) - if 00:30 then turn the charger on (on the car).
It appears this morning it did fire (trace image included), but it didn't actually start the charge. However at 4:30 (and I only added this yesterday) it defaults to start the charger again (so that if it is not fully charged it will continue).. luckily this happened as I had set the SoC to 100% as doing a trip this morning.
My belief is that because the car was asleep at the time the charge switch did nothing, but was lucky that it fired the second time around. I can see in my log book that the charger did only turn on at 4:30 not 12:30. (Second fire of the switch).
I share logs, but don't have debug turned on.

What I have done is enable a "wake car" + 10 sec delay into the automation at 00:30.

![Screenshot_20221226_085632_Home Assistant](https://user-images.githubusercontent.com/25253860/209529962-d3e75129-3b90-474c-bc5b-8c7053ba79b6.jpg)
![Screenshot_20221226_085639_Home Assistant](https://user-images.githubusercontent.com/25253860/209529986-f0a0526d-05c5-4d1b-8192-6712958607a9.jpg)

## Debug log

```text

Add your logs here.

```
As above don't have debug logs as was not expecting it and to get this to rework would be pretty hard, as it's the first time it's happened after 2 weeks of success

**Comment by pbathuk** [comment]
I believe I've just been luckily previously, as it seems the wiki indicated (by way of the sample code):
https://github.com/alandtse/tesla/wiki/Modify-Charge-Limit

Which seems to show that awake if sleep needs to be run. 

So I believe I have answered my own question, but I would like to get other people's point of view

**Comment by carleeno** [comment]
Turning on the charge switch will wake it first if it's asleep.
Take a look at the logbook for the charger switch to see if it ever turned on, or if it turned on then back off. Also look at the asleep and online sensors around that same time.

If you send a command but the car was unreachable (not asleep but actually unreachable) there should be an error in your logs from teslajsonpy, so check those as well. If HA has restarted then the system logs are cleared so you want to check those quickly.

**Comment by pbathuk** [comment]
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/tesla_custom/switch.py:127
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 00:30:20 (1 occurrences)
Last logged: 00:30:20

Error executing service: <ServiceCall switch.turn_on (c:01GN5XC5XD5B1VTPEFV0MSGGRZ): entity_id=['switch.tony_charger']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1763, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/tesla_custom/switch.py", line 127, in async_turn_on
    await self._car.start_charge()
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 1059, in start_charge
    data = await self._send_command("START_CHARGE")
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 759, in _send_command
    raise ex
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 744, in _send_command
    data = await self._controller.api(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1333, in api
    return await self.__connection.post(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 160, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 208, in __open
    raise TeslaException(resp.status_code, "vehicle_unavailable")
teslajsonpy.exceptions.TeslaException: vehicle_unavailable

**Comment by pbathuk** [comment]
That was on the log.. I guess the car was unavailable.. so need to test for that I guess

**Comment by carleeno** [comment]
Yep you could do a loop where it tries to turn it on every 15 minutes until the switch remains on. If it fails for any reason it will retry. It's not possible to reliably know ahead of time if it will fail.

**Comment by pbathuk** [comment]
Ok, good to know & I think answers my question. Do you think there is a test for availability of the car?

- I still don't know why it was available as it was at home with good connection to WiFi

**Comment by carleeno** [comment]
the test is to send a command and see if it succeeded or not. Tesla could report that the car is online, but if there is a temporary internet or service outage, the command would still fail for vehicle_unavailable. You won't know until you try to send the command that you want to perform, as a test may succeed one time then fail the next time. This can also happen from tesla server maintenance or outages.

**Comment by pbathuk** [comment]
Brilliant.. So as an aside, I've just used ChatGPT to write the code for me to loop.. didn't even know you could, so wanted to ask the bot :) 

Got a great bit I can add to my YAML:
```yaml
    action:
      - service: sensor.turn_on
        entity_id: sensor.tony_charger
      - delay:
          minutes: 1
      - condition: state
        entity_id: sensor.tony_charger
        state: 'off'
      - service: sensor.turn_on
        entity_id: sensor.tony_charger
      - delay:
          minutes: 1
      - goto: 'start'
      - label: start
```

I'm closing this now (btw our car is called Tony the Tesla 😁 )

**Comment by pbathuk** [comment]
FYI the code above does not work 100%.. but the fact it gave me something is what I'm impressed with

**Comment by pbathuk** [comment]
For anyone interested the ChatGPT is not valid Yaml code (goto & label don't seem to be supported), but this work:

```yaml
repeat:
  until:
    - condition: state
      entity_id: switch.tony_charger
      state: "on"
  sequence:
    - type: turn_on
      device_id: 12649940722560b225328eb23c4f1e6e
      entity_id: switch.tony_charger
      domain: switch
    - delay:
        minutes: 1
```
