### ISSUE TITLE
Please pull in the Tesla navigation destination string

### ISSUE THREAD

**Issue by OrangeMikey** [alandtse/tesla#477]
It would be useful to have the destination string available when navigating I believe this is in the Tesla api as:

Active_route_destination

as currently I can’t make a nice notification email unless I navigate to destinations I have defined in home assistant

active_route_energy_at_arrival would also be useful to me, but I am not sure if other people would find that useful.

**Comment by carleeno** [comment]
You can find both of those as attributes in the arrival time sensor
![Screenshot_20230107-200032](https://user-images.githubusercontent.com/54586926/211177390-2771cc02-7144-41e6-8e29-ca47bb27bd70.png)

**Comment by OrangeMikey** [comment]
Missed this. Thank you
