### ISSUE TITLE
Successful service calls are not optimistic

### ISSUE THREAD

**Issue by Bre77** [alandtse/tesla#479]
When calling a service like `number.set_value` and its succesful, the state is not changed optimistically, and due to the delay in polling it can take some time before Home Assistant knows what the current value actually is.

It might be appropriate to have `async_set_native_value` actually change the internal values of **_car** if the API call was successful.

**Comment by jaymunro** [comment]
I have noticed that setting the charging amps with the following results in an immediate change in current but the value displayed in HA for number.carname_charging_amps is not updated for ages. I haven't timed it but longer than 5 minutes I feel:

service: number.set_value
data:
  value: |-
    {{ 
      [0, 
        [ ( states('sensor.powerwall_excess_solar') | float  / 235 * 1000 ) | round(1)
          , ( states('input_number.car_charge_rate') | float  / 235 * 1000 ) | round(1)
        ] | min 
      ] | max
    }}
target:
  entity_id: number.carname_charging_amps

Is this the same symptom as described in this issue?

**Comment by Bre77** [comment]
Yes, the value only changes on every polling interval which defaults to 660s which is 11 minutes, so 5 min is about the average.

**Comment by jaymunro** [comment]
Ok, that makes sense. So I can confirm this behaviour. Though not serious, it is disconcerting when changing a value an not seeing it reflected in the UI. Makes you question the reliability of the integration.

Brett’s fix suggestion seems logical to me.

**Comment by Bre77** [comment]
Ok I just checked the library, and it should already be optimistic based on this line: https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/car.py#L899

I need to look into this futher as to why its not actually updating the state.

**Comment by Bre77** [comment]
Ok this is an issue with the underlying library, and not the Home Assistant integration. Will be closed by https://github.com/zabuldon/teslajsonpy/pull/392 and bumping the library.

**Comment by Bre77** [comment]
Can confirm using 3.7.2 fixes the number.*_charging_amps entity. Integration just needs a library bump now for others to get the fix.

**Comment by alandtse** [comment]
Oops, reopening and will close once we have a real bump PR.
