### ISSUE TITLE
Can't find API info for defrost

### ISSUE THREAD

**Issue by elektrinis** [alandtse/tesla#481]
I want to add a dashboard button for defrost specifically, but can't find information on how that can be done.
Standard HVAC service call does not offer "Defrost" mode, and I can't find info on specific API command. Can someone point me to right place? Thanks.

**Comment by carleeno** [comment]
Hi, it's pretty straightforward, to set defrost mode use `climate.set_preset_mode` with a value of Defrost. If you want a single button to do this, one option is to create a button helper and an automation which watches that helper and runs the above service. It will automatically turn it on when you set the preset mode as well.

![image](https://user-images.githubusercontent.com/54586926/211822064-78b2c1c7-8975-4d2f-9504-72aeafc526d2.png)

**Comment by elektrinis** [comment]
It works! Thank you :)
