### ISSUE TITLE
vehicle energy_added sometimes decreases

### ISSUE THREAD

**Issue by llamafilm** [alandtse/tesla#488]
## Describe the bug
Home Assistant shows a warning because the `energy_added` sensor sometimes decreases.  If I understand this correctly, a `total_increasing` sensor is expected to reset to zero sometimes, but never decrease other than that.

```
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:385 
Integration: Sensor (documentation, issues) 
First occurred: 5:50:11 PM (1 occurrences) 
Last logged: 5:50:11 PM

Entity sensor.tesla_model_3_energy_added from integration tesla_custom has state class total_increasing, but its state is not strictly increasing. Triggered by state 25.53 (26.95) with last_updated set to 2023-01-21T01:46:31.326044+00:00. Please report it to the custom integration author.
```

Here's a graph from Home Assistant and another from IotaWatt showing the actual power flowing into the car.  I was experimenting today with adjusting the charging amps, trying to maximize the use of my solar power.
<img width="1054" alt="Screen Shot 2023-01-20 at 19 20 25" src="https://user-images.githubusercontent.com/3991046/213841418-343d5f28-8fe7-4aab-9cf3-ff8f42b395fa.png">
<img width="1062" alt="Screen Shot 2023-01-20 at 19 20 16" src="https://user-images.githubusercontent.com/3991046/213841422-9287d516-0d90-47de-bca7-a95516f02516.png">

## Version of the custom_component
3.9.1

## Version of Home Assistant
2023.1.6

**Comment by alandtse** [comment]
This is a tesla issue unfortunately. The API sometimes drops the value.
