### ISSUE TITLE
Query polling_interval

### ISSUE THREAD

**Issue by lnxbil** [alandtse/tesla#492]
Hi,

I'd like to know if I'm just unable to find it or is it currently not possible to query the current `polling_interval`? I know that I can set it via the service and/or automation. If it is currently not possible, could this be integrated?

Best,
LnxBil

**Comment by alandtse** [comment]
https://github.com/alandtse/tesla/wiki/Polling-policy

**Comment by lnxbil** [comment]
Thank you for this detailed answer. Where exactly is the information how I can poll the current value of the interval?

**Comment by alandtse** [comment]
You should ask the HA forums. scan_interval is a default setting for integrations. I have no idea what you can do with it.

**Comment by lnxbil** [comment]
Oh, thank you!
Maybe that should also go into the documentation?

**Comment by alandtse** [comment]
Sounds like a good idea. Once you get an answer, please feel free to update the wiki.
