### ISSUE TITLE
Inside temp not updating 

### ISSUE THREAD

**Issue by blair287** [alandtse/tesla#496]
Issue started today noticed that when the car is woken up everything in HA update correctly apart from inside temp and current temp on hvac for some reason, this before always used to update when car was woken up.

Only way could get it to update was reboot HA. Tesla app clearly showed 0c but HA just reported last temp of 14c from when the car last went to sleep. Outside temp seemed to update and be correct.

![Screenshot_20230125_012643_Home Assistant](https://user-images.githubusercontent.com/44187409/214461496-2746a1aa-7632-4efb-af8a-6515cc90ac8d.jpg)
![Screenshot_20230125_012624_Tesla](https://user-images.githubusercontent.com/44187409/214461510-ee0546c7-edd5-48ec-95d9-a20a77a2f1d4.jpg)

**Comment by blair287** [comment]
> Please provides teslajsonpy logs. The temperatures are updated at the same time so there shouldn't be a case where only one updates.

Sorry how do I get those logs

**Comment by alandtse** [comment]
https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging
