### ISSUE TITLE
Control the charge cable port lock/unlock via the integration

### ISSUE THREAD

**Issue by scottda4270** [alandtse/tesla#50]
It would be great to be able to control the charge port lock with a HA routine or Node Red flow. I presume its the charger sensor entity is to show if a cable is plugged in or not but cant find a sensor the port lock/unlock....not sure if this is exposed via the Tesla API or not?

thanks

**Comment by alandtse** [comment]
Isn't the lock available? `lock.tesla_model_3_charger_door_lock`?

**Comment by scottda4270** [comment]
But that would unlock the doors as well. I just wanted to unlock the charge port if at all possible.

**Comment by alandtse** [comment]
Uh. that's not what the [api ](https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/homeassistant/lock.py#L160)is supposed to do.

**Comment by scottda4270** [comment]
Ok will try that later. Thanks.

Sent from my iPhone

On 2 Oct 2021, at 10:56, Alan Tse ***@***.***> wrote:

﻿

Uh. that's not what the api <https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzabuldon%2Fteslajsonpy%2Fblob%2Fdev%2Fteslajsonpy%2Fhomeassistant%2Flock.py%23L160&data=04%7C01%7C%7Cac1831ed322b463b4b8608d9858ad828%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687653652007371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jCXZC%2BZmyptGqBo7RycLodQyUMbnx%2BfxtFMhahsHPyE%3D&reserved=0> is supposed to do.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falandtse%2Ftesla%2Fissues%2F50%23issuecomment-932725110&data=04%7C01%7C%7Cac1831ed322b463b4b8608d9858ad828%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687653652017326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Qi%2FepSnpukSDfWzbZuPrpr7BTQXwFGxpbfN7UODWE6E%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATUBJGCHZAS2NB57HR73NCLUE3JLFANCNFSM5FFI7WJQ&data=04%7C01%7C%7Cac1831ed322b463b4b8608d9858ad828%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687653652017326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GNfc9dInUnxJ2fUatywdl7UCuQ%2Br2zBKwYeG%2FZXKYWo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cac1831ed322b463b4b8608d9858ad828%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687653652027283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FbcB1KrUpHoyACsUms7vP0ZYC%2FSB7eRBtszK2Id57B4%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cac1831ed322b463b4b8608d9858ad828%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687653652027283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TI5S2VdZIG6reTe8IvTpcARkJ%2B2DIZEeKjvrB4RJ%2ByY%3D&reserved=0>.

**Comment by scottda4270** [comment]
ah....got it now. Sorry I was being really stupid and was only seeing the **door lock sensor**, not the **charger door lock sensor**. It was right at the top of the list, how did I miss that!....sorry, sometimes things solutions are right in front of your eyes. Thanks very much @alandtse
