### ISSUE TITLE
Home Assistant: Setup failed for custom integration tesla_custom

### ISSUE THREAD

**Issue by jarodtoups** [alandtse/tesla#504]
Logger: homeassistant.setup
Source: setup.py:213
First occurred: 10:04:48 (1 occurrences)
Last logged: 10:04:48

Setup failed for custom integration tesla_custom: Unable to import component: cannot import name 'Controller' from 'teslajsonpy' (/usr/local/lib/python3.10/site-packages/teslajsonpy/__init__.py)

**Comment by alandtse** [comment]
You may have to manually install teslajsonpy. It appears damaged. You can try readding the integration. This may force HA to reinstall it.

**Comment by jarodtoups** [comment]
Fixed in version 2023.2.1
