### ISSUE TITLE
Shift State removed - broke my automation

### ISSUE THREAD

**Issue by domeassist** [alandtse/tesla#506]
Hi,

I had automations set up to open/close my garage door based on the old shift state. I updated to the new version and lost this sensor. Is it possible to bring this back?

A binary Parking Brake sensor or user present won't work because i had it set to:
Open on shift to R (When at home + when connected to home wifi)
Close the door when shifting from R to D (when at home)
Close the door when shifting from D to P (when at home + when connected to home wifi)

It would be awesome if shift state could be restored.

Thanks

**Comment by domeassist** [comment]
Hi again,

I should probably add: i did read up on the history of this and it seems when the raw json data was stopped there was a bit of discussion around shift state but it appears to have fallen by the wayside in the discussion and was parked (no pun intended) for a later date and associated issues closed. There have been a few requests for shift state from a few users. I don't have the experience to log a PR so am hoping someone more savvy could do that. I would be wildly appreciative if i could get my automations working again. Cheers!

**Comment by alandtse** [comment]
Thanks. I'm going to close this in favor of the older one. #476

**Comment by domeassist** [comment]
Thanks mate. Appreciate all your work!
