### ISSUE TITLE
Tesla amp charging wont let you pick 32amps.

### ISSUE THREAD

**Issue by jamesa22** [alandtse/tesla#507]
I have noticed you can't set charging amps above 16amps. It has worked a few times but mostly comes up with unknown error. This when trying to charge a Tesla Model Y.

**Comment by InTheDaylight14** [comment]
The upper limit is set by the attached charger. That could be the issue. The Tesla API will throw back an error, enable debugging and post the error text here. 

https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging
