### ISSUE TITLE
Some control or sensor status backwards

### ISSUE THREAD

**Issue by snovvmann** [alandtse/tesla#508]
Hi, 

My Tesla is on 2023.2.10, and the integration is 3.9.2.

I recently discovered that some of the controls or sensors are reporting the status backwards or incorrectly.

The ones I have identified:

Charger door (showing open when it is closed)
Frunk (showing open when it is closed) 
Charger (showing plugged in when it is not)

I do not know at what point this became an issue.  I do know that these controls and sensors were reporting properly late December 2022 or early January 2023.

The result of the issue is that, for example, I have to "close" the frunk in order to open it.  To close the frunk, I have to "open" it.

Thanks.

**Comment by snovvmann** [comment]
Well, between an HA update and a refresh, everything is back in sync for now.  I'll continue testing for the next few days.

**Comment by alandtse** [comment]
Glad it resolved. Please reopen if it happens again.
