### ISSUE TITLE
seperate Charging Details for Work and Home?

### ISSUE THREAD

**Issue by kingunlim** [alandtse/tesla#522]
### Discussed in https://github.com/alandtse/tesla/discussions/512

<div type='discussions-op-text'>

<sup>Originally posted by **kingunlim** February 14, 2023</sup>
Hi, 
I don't know if its easy to do, but it would be awesome if we can have a option to see detailed charing history where the car was plugged in, like in the tesla app?
i would need this feature for my work, so i wanted to ask if this is possible in any way?

best regards</div>

sry if its not allowed to ask a question here in the issues thread, i'm just not sure if the developer sees the question in the discussion.
best regards

**Comment by alandtse** [comment]
You should ask HA to provide this functionality. It doesn't make sense to implement at the Tesla level.

**Comment by kingunlim** [comment]
But what can HA do to provide this?
your integration must tell ha in the first place that there are 2 seperate charging values?
if im right atm your integration does not seperate work and home charging like in the tesla app.

that would be a awesome feature if you could implement this, in my case it would be enough to get a toggle to exclude the charging of my work and just get the home charging values.

best regards

**Comment by anhaff** [comment]
> But what can HA do to provide this? 

You could have different automations for different locations to control the charging.
