### ISSUE TITLE
Frunk and other status out of sync

### ISSUE THREAD

**Issue by snovvmann** [alandtse/tesla#523]
I am running the latest version of the Tesla integration, along with Tesla 2023 software.  I have been using the integration for several months and this has been a persistent issue.

The frunk, charging port, hatch, etc. get out of sync, where, even when the frunk is closed the integration "thinks" that the frunk is open.  Therefore, my only option to open the frunk is to select close frunk, then the frunk opens.  Same goes for charging port, etc.

Even when the car is awake and the integration shows "connected", the status does not refresh.  This becomes a problem when using scenes.  If I have a scene that opens the frunk, but the integration thinks that the frunk is already open (even though it is closed), the scene does not work.  

Please advise.  Thanks.

**Comment by danielp370** [comment]
I'm seeing the same problem. I have two tesla. The second one that is unplugged keeps jumping between plugged in and plugged for charger.

**Comment by t112013** [comment]
same here. just noticed today.  but this must have happened in the pass week. what can it be ?

**Comment by t112013** [comment]
i actually see that the state is changing to unplugged and plugged in all the time (every 10 sec)
This broke my automations :(

**Comment by danielp370** [comment]
I enabled debugging. 
I run a force update and then 
I see it query my vehicles and for the one that is unplugged the  vehicle_data looks correct. That is, it shows charing_state: Disconnected.  The HA binary sensor reflects the correct (unplugged) value.
Then according to HA ten seconds later the binary sensor changes to plugged-in. I dont see anything in logs to show why that changed.

**Comment by danielp370** [comment]
At least in my case, the problem stops when I unplug the other car. So I suspect it is updating the wrong state.  @snovvmann do you have multiple vehicles or tesla products?

Anyway, I'll try look further when I get time.

**Comment by snovvmann** [comment]
> At least in my case, the problem stops when I unplug the other car. So I suspect it is updating the wrong state. @snovvmann do you have multiple vehicles or tesla products?

@danielp370 I do not have another Tesla product or multiple Tesla vehicles.  For me, the status for the frunk, hatch, charging door, etc. seemingly and randomly change states, which causes automation to break.  Sometimes the integration would show that the frunk is open when it's really closed.  Other times it would show closed when it's really open.  Still, I've seen the dashboard where it shows close and open options at the same time, as if the integration does not know the state so it presents both options.

I ended up creating a scene that triggers an automation so that the process accepts my desired command (e.g., open frunk), then checks to see the state that the integration is reporting.  If the integration thinks that the frunk is already open, then the automation will simply issue a close command.  This will cause the frunk to open.  It works, but I wish I didn't have to go through the trouble of creating a helper toggle, scene, and automation just to do this.
