### ISSUE TITLE
Failed to establish a new connection: [Errno 101] Network unreachable') installing teslajsonpy==3.7.4

### ISSUE THREAD

**Issue by bbostock** [alandtse/tesla#540]
<h>After updating HA to 2023.3.5 the custom_tesla integration no longer starts. </h>

The error in the log is:
Setup failed for custom integration tesla_custom: Requirements for tesla_custom not found: ['teslajsonpy==3.7.4'].

After completely removing the integration and many reboots on attempting to re-add the integration the log shows missing teslajsonpy

## Configuration

```yaml
VERSION = "3.10.3"
```

## Debug log

```text

2023-03-20 10:15:08.268 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package teslajsonpy==3.7.4: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa19cb670>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/teslajsonpy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa19c87f0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/teslajsonpy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa19ca560>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/teslajsonpy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa19cb7f0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/teslajsonpy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa19c9fc0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/teslajsonpy/
ERROR: Could not find a version that satisfies the requirement teslajsonpy==3.7.4 (from versions: none)
ERROR: No matching distribution found for teslajsonpy==3.7.4
[

```

**Comment by redlefloh** [comment]
I received the following error after upgrading to 2023.3.4, could that be related? 
`2023-03-20 16:28:58.570 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for tesla_custom using this method at custom_components/tesla_custom/__init__.py, line 267: hass.config_entries.async_setup_platforms(config_entry,`` PLATFORMS)`

**Comment by alandtse** [comment]
> Failed to establish a new connection: [Errno 101] Network unreachable')'

Something is wrong with your network connection. Your HA machine isn't able to connect to the pypi servers for some reason. Nothing this component can do for you.

> I received the following error after upgrading to 2023.3.4, could that be related?

No. See above. What you identified is something independent. That was [fixed](https://github.com/alandtse/tesla/issues/499) in 3.9.2 and above.

**Comment by bbostock** [comment]
Thanks Alan, turns out to be the use of a fixed IP address combined with the dns address set to my router instead of a proper dns address such as 8.8.8.8. Sorry to have bothered you. 
Bill

**Comment by alandtse** [comment]
Glad you were able to figure it out. Please let me know if you run into anything else.
