### ISSUE TITLE
Controller.update() got an unexpected keyword argument 'vins'

### ISSUE THREAD

**Issue by cbirkenbeul** [alandtse/tesla#558]
Hi,
since yesterday the integration cannot connect to the tesla api.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tesla_custom/__init__.py", line 398, in _async_update_data
    return await self.controller.update(
TypeError: Controller.update() got an unexpected keyword argument 'vins'
```
The App had some issues yesterday too, maybe there are some api changes.

**Comment by alandtse** [comment]
This is our API that's giving you an issue. But most likely your teslajsonpy is outdated. We need [3.8.0](https://github.com/alandtse/tesla/blob/dev/custom_components/tesla_custom/manifest.json#L25).

**Comment by cbirkenbeul** [comment]
Thanks. That was the issue.
