### ISSUE TITLE
Cabin Overheat Protection shows unavailable periodically

### ISSUE THREAD

**Issue by fhteagle** [alandtse/tesla#570]
I see the select.cabin_overheat_protection gets blanked out (placeholder text of the entity's friendly name), and none of On, No A/C, or Off are selected. Entity history shows either unknown or unavailable.

This seems to occur periodically, I do not have an exact pattern of when this happens. It does seem to be associated with the Tesla going out of LTE signal at the very least. 

Tesla app continues to show "No A/C", even when the integration's entity is unknown or unavailable.

## Version of the custom_component

HA 2023.4.1 in a docker container
Tesla integration 3.11.0 installed via HACS
2023 Model YLR 2023.6.9 software

## Debug log

Possibly relevant homeassistant.log lines:

```
  File "/config/custom_components/tesla_custom/number.py", line 59, in async_set_native_value
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 813, in change_charge_limit
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 768, in _send_command
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 753, in _send_command
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1336, in api
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1346, in __post_with_retries
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 161, in post
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 209, in __open
    raise TeslaException(resp.status_code, "vehicle_unavailable")
```

I have turned on debugging logger to see if I can catch any other pattern or relevant errors, and will update if I find any.

**Comment by alandtse** [comment]
Your vehicle is reporting that it isn't available to provide info. We therefore don't have any info we can populate the sensor with. Tesla controls when the API responds like that and there's nothing we can really do about it. While we can retry, we're trying not to get people banned from the API.

**Comment by fhteagle** [comment]
@alandtse  - Okay I accept that the car will not be able to update without Wifi or LTE signal. However, this select box does not re-populate after the car is back in signal. For example, I have the car on my home wifi (continuously responding to pings), press "force data update", and instead of this select re-populating, the same error lines as above are re-posted to home-assistant.log 

I.e., the logged error message is occurring even when the car is definitely available to the app and to the HA integration.

**Comment by alandtse** [comment]
You can try getting a new token, but 408 errors are coming from Tesla's server. They control that. Perhaps they're already blocking you on unofficial apps.

**Comment by fhteagle** [comment]
I can not find any other evidence of your theory that my API access is at all blocked, throttled, or limited. All of my sensors and controls work as expected. I can even make changes to the select.cabin_overheat_protection options, and see them reflected in the car and the Tesla app.

I really think there is an issue with teslajsonpy that makes it look like blocking is occurring in the way the error is handled, but that is definitely not the root cause.

**Comment by alandtse** [comment]
I mean I'm just reading the log you gave me. The source is open if you can figure it out. A 408 vehicle unavailable is a Tesla response that we can't control.
