### ISSUE TITLE
TeslaMate integration, Teslamate id field can't be set

### ISSUE THREAD

**Issue by moesizlag** [alandtse/tesla#583]
Hi,

first thx a ton for integrating TeslaMate, that was a feature I was long hoping for :-)
I got some issues getting it configured though, more specifically I can't set the Teslamate id field. I have it enabled but whenever I change "unknown" to the actual car id (1 in my case), it switches back to unknown a few seconds later.
Tried directly in the integration config and via the developer tools.

Any idea what the cause is?

Thx

**Comment by mkalmuk-godaddy** [comment]
Thanks, restarting another time fixed it. It doesn't seem the Tesla integration is pulling any metrics via MQTT from Teslamate from looking at the logs though :(

**Comment by moesizlag** [comment]
Nevermind, just after posting this msg the frist MQTT logs showed up.
