### ISSUE TITLE
HA log warning about invalid unit (Wh) for 'battery_remaining' sensor

### ISSUE THREAD

**Issue by ChrisJ60** [alandtse/tesla#589]
## Version of the custom_component

3.12.1

## Configuration

```yaml
2023-05-01 08:56:13.225 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.jenkins_family_battery_remaining (<class 'custom_components.tesla_custom.sensor.TeslaEnergyBatteryRemaining'>) is using native unit of measurement 'Wh' which is not a valid unit for the device class ('battery') it is using; expected one of ['%']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

## Describe the bug

Warning message in the Home Assistant log relating to an invalid unit for the sensor device class.

**Comment by Megabytemb** [comment]
@shred86 can you have a look at this? It looks like you wrote the Enegrysite code back in the day?

**Comment by shred86** [comment]
I think the Tesla API just reports battery remaining in Wh but obviously the HA device class must have changed recently where the unit of measurement is a percentage. Someone with a Powerwall would probably have to look at what the Tesla API provides and see if maybe there's a way to just pull in a percentage directly. Otherwise, it might just have to be calculated within the integration itself.

**Comment by ChrisJ60** [comment]
Mine (which is on the very latest firmware (23.4.2) shows this:

{
  "command_source": "Configuration",
  "battery_target_power": 237.75,
  "battery_target_reactive_power": 0,
  "nominal_full_pack_energy": 28487,
  "nominal_energy_remaining": 24039,
  "max_power_energy_remaining": 0,
  "max_power_energy_to_be_charged": 0,
  "max_charge_power": 10000,
  "max_discharge_power": 10000,
  "max_apparent_power": 10000,
  "instantaneous_max_discharge_power": 20860,
  "instantaneous_max_charge_power": 14000,
  "instantaneous_max_apparent_power": 11040.000000000002,
  "hardware_capability_charge_power": 0,
  "hardware_capability_discharge_power": 0,
  "grid_services_power": -0,
  "system_island_state": "SystemGridConnected",
  "available_blocks": 2,
  "available_charger_blocks": 0,
...

The key field here is:   "nominal_energy_remaining": 24039

This is for sure in Wh but I guess that HA expects it to be in % for some reason (Wh seems like a perfectly valid/reasonable metric for 'battery remaining' but hey...). Unfortunately you can't simply divide nominal_energy_remaining by nominal_full_pack_energy to get a percentage (well you can but it won't tie up with the '%' figure reported by the Tesla app as some capacity is 'reserved').


On 4 May 2023, at 02:38, shred86 ***@***.***> wrote:


I think the Tesla API just reports battery remaining in Wh but obviously the HA device class must have changed recently where the unit of measurement is a percentage. Someone with a Powerwall would probably have to look at what the Tesla API provides and see if maybe there's a way to just pull in a percentage directly. Otherwise, it might just have to be calculated within the integration itself.

**Comment by purcell-lab** [comment]
According to here: https://www.home-assistant.io/integrations/sensor/#device-class

- battery: Percentage of battery that is left in %
...
- energy: Energy in Wh, kWh, MWh, MJ, or GJ
- energy_storage: Stored energy in Wh, kWh, MWh, MJ, or GJ

This sensor should probably be migrated to device_class energy_storage.

![Screenshot 2023-06-14 08 52 08](https://github.com/alandtse/tesla/assets/79175134/2eb5c4bc-1964-44ee-bc5b-ec995bcf17d5)
