### ISSUE TITLE
Integration causing charging to start randomly

### ISSUE THREAD

**Issue by gdwickham** [alandtse/tesla#596]
I had set up the Telsa Integration within HA and developed an automation to charge the car when we had excess solar production, and to ramp up/down the charge rate (setting Charging Amps) based on current solar generation. The automation was set to run between 10am and 4pm daily every 60 seconds.
What I found was whilst the automation worked correctly, overnight the car charging would start at random times. (no charge schedule was set in the Tesla App).  I reset the wall charger and the car, but this did not help.
Disabling the automations did not help either, but disabling the integration stopped this behaviour.
Apologies if this is a known issue, but any fixes would be appreciated.

**Comment by alandtse** [comment]
The integration by itself does not enable charging. However, make sure you don't have any automations that enable switches. Check your HA log to see what enabled it.

Please also note that unless you have a charger schedule set up in Tesla's app, the car will immediately start charging once it's plugged in. That is the default behavior.

This is a duplicate but I'm too lazy to search for it for you. Please do search and update the issue with the earlier thread where this was discussed.
