### ISSUE TITLE
Decrease polling interval when car is active/driving

### ISSUE THREAD

**Issue by jaimevisser** [alandtse/tesla#60]
**Is your feature request related to a problem? Please describe.**
To prevent waking up my car (good) this integration has a rather high update interval (bad).

**Describe the solution you'd like**
When the car is active/driving decrease the polling interval so I get more detailed data of drives.

**Describe alternatives you've considered**
NA.

**Additional context**
NA.

**Comment by jaimevisser** [comment]
Hmm, might have to dive into the data. The trace on the map card looks very coarse so I assumed there just wasn't enough data to show a nice trace.

**Comment by alandtse** [comment]
I'll close this for now. If you notice a bug, please provide logs of teslajsonpy and the component.
