### ISSUE TITLE
TeslaMate MQTT warning at every HA startup

### ISSUE THREAD

**Issue by oeriksen** [alandtse/tesla#601]
After the release of the TeslaMate MQTT function, which I don't use, I'm getting this warning at every startup of Home Assistant:

`WARNING (MainThread) [custom_components.tesla_custom.teslamate] Cannot unsub from TeslaMate as MQTT has not been configured.`

Not a big deal but a bit annoying.

**Comment by automaton82** [comment]
I am also experiencing this issue.
