### ISSUE TITLE
Does polling wake my car / cache states locally when no change is expected

### ISSUE THREAD

**Issue by kevinholtkamp** [alandtse/tesla#605]
**Is your feature request related to a problem? Please describe.**
When my car is in my garage any I open my Tesla App, it always takes a long time (10-30 seconds) to connect to my car, so I assume it is sleeping.

I created an automation to automatically charge my car with solar energy. The automation first checks wether the SOC is <40%, in which case it will always charge regardless of solar production.

When this automation is active and I open the Tesla App, it always connects very fast (1-5 seconds).

I assume checking the SOC always connects to the car and polls the new state.

**Describe the solution you'd like**
When states are likely not going to change, for example when the car is in park and not charging, properties like SOC should be cached locally so the car does not need to be polled.

**Describe alternatives you've considered**
Instead of checking the SOC first, the automation could be set to only ever run during the day. but that would fail when I get home at midnight with 10% SOC and want the car to start charging.

**Comment by alandtse** [comment]
https://github.com/alandtse/tesla/wiki/Polling-policy
