### ISSUE TITLE
Warning from hass when opening the charge port "self.async_update_ha_state(), without enabling force_update"

### ISSUE THREAD

**Issue by mikesmitty** [alandtse/tesla#606]
## Version of the custom_component

v3.12.2

## Configuration

Default config:
- 660s polling interval
- "Normal" polling policy
- Previously configured to pull from Teslamate via MQTT, disabled at the time

## Describe the bug

Opened the "more info" page for the charge port lock entity and clicked "unlock", received warning below in the logs.

## Debug log

```text
Entity lock.CAR_NAME_charge_port_latch (<class 'custom_components.tesla_custom.lock.TeslaCarChargePortLatch'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
```
I didn't enable debug logging because the message seemed pretty explicit and easily reproducible, but if necessary I can turn on debug logging and reproduce it.

**Comment by alandtse** [comment]
Thanks for reporting.
