### ISSUE TITLE
Enable/disable cams when in Sentry mode

### ISSUE THREAD

**Issue by chrispazz** [alandtse/tesla#614]
Hello,
when my car is in my garage, it has no cellular network signal.
It can use WIFI signal but when it goes to sleep mode, also wifi stop working and I cannot wake up the car for charging from home assistant automation.
If I let sentry mode always on, it drains power using cameras (as I always use them).
If I can keep sentry mode enabled when at home but having home assistant stopping cameras when arrived at home and reactivating them when leaving.....

Chris

**Comment by darek-margas** [comment]
> Hello, when my car is in my garage, it has no cellular network signal. It can use WIFI signal but when it goes to sleep mode, also wifi stop working and I cannot wake up the car for charging from home assistant automation. If I let sentry mode always on, it drains power using cameras (as I always use them). If I can keep sentry mode enabled when at home but having home assistant stopping cameras when arrived at home and reactivating them when leaving.....
> 
> Chris

Tesla woke up on SMS so it won't work without coverage. Just schedule this charge in the car and it will wake up.

**Comment by alandtse** [comment]
I'm actually not sure what the issue or request is but I assume you're asking us to change the camera behavior? We don't control the cameras when in sentry mode. In fact, we don't have access to the cameras at all. I'll go ahead and close this. If you become aware of a way to control the cameras in the app, then we maybe able to do something about this.
