### ISSUE TITLE
Charger can go lower then 5A

### ISSUE THREAD

**Issue by riemers** [alandtse/tesla#625]
I don't know if it is an issue (since i don't own all models/combinations) but it allows to set my charge rate at 2A as minimum. I can actually see in the Tesla app that it has changed to 2A and also in the car, but the car doesn't swallow it. 5A is the minimum.

Is this intentional? If so can i set the limit somewhere?

**Comment by BogdanDIA** [comment]
Om my model Y, I can even go to 0 Amps with car's charger and the charging will stop without the charging switch to be off. This is good because I use an automation adjusting the charging current according to an external condition like solar panels production.
My understanding of this is: when the charger is plugged into the car, the charger will communicate its capabilities to the car and car will send them to the server. Those capabilities will be taken by Tesla custom integration from the server.
You can see the charging limits as attributes in the number.{name}_charging_amps entity:

min: 0
max: 13
step: 1
mode: auto
unit_of_measurement: A
attribution: Data provided by Tesla
icon: mdi:ev-station

**Comment by riemers** [comment]
Weird that the api says 0 is minimum while the app says 5A. It is what it is, if I set it to 0 the car says charging takes 24+ and if I set it back to 5A it was having a hard time returning back to normal. No clue if this is bad for the car, don’t think so 🤓 might just take a long time to average out the number perhaps 🤷

**Comment by fhteagle** [comment]
2023 Model Y with 2023.12 software, I can set as low as 5A on the app, but down to 0A selected (1A actual draw verified by OpenEVSE's CT measurement) via HA Integration.

Side comment:

Teslas leave a lot of things powered on during charging. I do not have an exact measurement, but I have heard other people estimate about ~300W of power used for electronics, coolant pumps, etc during the entire charging process. I changed from throttled charging as slow as 6 amps to waiting until conditions were right to charge as fast as the circuit could handle, and saw a pretty noticeable improvement in miles/kWh delivered across a month's timeframe. Your mileage may vary, as they say, but low and slow charging might not be the most efficient strategy for you...

**Comment by InTheDaylight14** [comment]
Can you set lower than 5A through the Tesla mobile app?

**Comment by alandtse** [comment]
As it looks like we're able to issue the command, there's nothing we can do to make sure the vehicle actually respects or uses it. I'll close this out.

**Comment by BogdanDIA** [comment]
> 2023 Model Y with 2023.12 software, I can set as low as 5A on the app, but down to 0A selected (1A actual draw verified by OpenEVSE's CT measurement) via HA Integration.
> 
> Side comment:
> 
> Teslas leave a lot of things powered on during charging. I do not have an exact measurement, but I have heard other people estimate about ~300W of power used for electronics, coolant pumps, etc during the entire charging process. I changed from throttled charging as slow as 6 amps to waiting until conditions were right to charge as fast as the circuit could handle, and saw a pretty noticeable improvement in miles/kWh delivered across a month's timeframe. Your mileage may vary, as they say, but low and slow charging might not be the most efficient strategy for you...

Indeed, charging to max current would be the optimum choice. In my case, I prefer to give the energy company as less as possible. Here is a table with values I took during a morning, 1A probably just covers for the car's consumption:

1A - 0 Km/h
2A - 1.9 Km/h
3A - 3.5 Km/h
4A - 4.5 Km/h
5A - 6.4 Km/h
6A - 7.7 Km/h
7A - 9.2 Km/h
8A - 10.5 Km/h
