### ISSUE TITLE
[Feature Request] Integrate Tesla_API_Lite project to obtain Auth Token locally

### ISSUE THREAD

**Issue by nickcj931** [alandtse/tesla#645]
**Is your feature request related to a problem? Please describe.**
Using 3 party (untrusted) apps to obtain auth tokens, not knowing if they are being stored by the app remotely etc. 

**Describe the solution you'd like**
There is a nice GitHub project which processes the Authentication locally on the users machine, it would be nice if this can be somehow added to the Tesla HA integration so it takes you through the onboarding process locally. 
Process could be something like this ->
1. User installs the Tesla HACS integration
2. Click here to obtain refresh token OR Already have token
3. if Obtain refresh token print out the URL to paste into browser
4. User performs authentication against Tesla login screen - receives Page not found copies the address
5. Pastes the address into the setup window on home assistant, this then takes the refresh token as the variable and passes it through to the rest of the setup where user inputs email etc to finish.

**Describe alternatives you've considered**
Using 3rd party apps is the only way a normal user can obtain Auth token, this can possibly be risky giving someone a "key" to your vehicle.

**Additional context**
Tesla_API_Lite project is here
https://github.com/Marky0/tesla_api_lite/tree/main
get_token.py is all that's needed (without storing a local JSON file)

**Comment by alandtse** [comment]
This I won't do. We used to do it locally but Tesla kept breaking it. There are open source apps that will grab the tokens. You can trust them as much as you can trust this open source component or the one you linked.
