### ISSUE TITLE
Delete old tesla from account

### ISSUE THREAD

**Issue by ravdberg** [alandtse/tesla#647]
**Is your feature request related to a problem? Please describe.**
I have a new tesla and am unable to delete the old one which is not connected to my account anymore.
I can delete the app and add it again but would be nice to have a delete option for the old car.

**Describe the solution you'd like**
Delete option
**Describe alternatives you've considered**
Delete the integration and reinstall it.

**Additional context**
None.

**Comment by alandtse** [comment]
Unfortunately, this is a HA issue. If you no longer have a car, the integration no longer provides any data for it. The fact HA keeps the entity means you have to manage it in HA. You should be able to delete the device there.

Reinstalling the component basically wipes everything and then you just see what is current. But again, that's a HA design decision.
