### ISSUE TITLE
Delete inactive devices (sold cars)

### ISSUE THREAD

**Issue by Chawiby** [alandtse/tesla#652]
Hi,
I wonder if it's possible to implement a functionality that allows to delete inactive devices.
In my example, I have sold two Teslas but they still show up as (inactive) devices (although they have been removed in the Tesla app itself).
However, it would be great if such devices together with their entities could also be removed from the Tesla integration in HA because they are completely useless due to their non-existence.
Thank you!
![2023-07-03 08_39_59-Einstellungen – Home Assistant](https://github.com/alandtse/tesla/assets/117714758/5c69ce21-3c5d-4f3f-8abc-053e42387168)

**Comment by alandtse** [comment]
This would be a HA issue. We stop updating info on the car once it's no longer in the account. HA would have to provide granularity to remove old devices. The option is always to reinstall the integration which forces HA to clear everything out anyway.

**Comment by Chawiby** [comment]
Thank you!
