### ISSUE TITLE
[Feature Request] Provide active_route_minutes_to_arrival directly

### ISSUE THREAD

**Issue by storm1er** [alandtse/tesla#656]
**Is your feature request related to a problem? Please describe.**

See https://www.reddit.com/r/homeassistant/comments/14qepmu/comment/jqmore7/?context=3

> I'm using HACS + [Tesla Custom Integration](https://github.com/alandtse/tesla) and it worked gratefully for Charge-on-sun feature. But doing a simple automation as "When Tesla goes home, cast tts in how many time" is hard as hell.(+ when arrival time is less than 2 min, cast tts "Tesla is approaching")
> 
> Here's why:
> 1/ Tesla API give drive_state.active_route_minutes_to_arrival BUT [alandtse use it to create an arrival datetime](https://github.com/alandtse/tesla/blob/dev/custom_components/tesla_custom/sensor.py#L678C22-L678C54)
> 2/ So this value "doesn't exist" on HA side and I have to recreate it myself
> 3/ [Why the f4ck comparing datetime with offset is so hard it can fill at least a whole google page search](https://www.google.com/search?q=home+assistant+compare+two+date&rlz=1C1ONGR_frFR1064FR1064&oq=home+assistant+compare+two+date&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg70gEIMjQ3OWowajSoAgCwAgA&sourceid=chrome&ie=UTF-8)
> 4/ Comparing is not enough, I need to get minutes remaining from this given date

**Describe the solution you'd like**
Provide the value of active_route_minutes_to_arrival as entity or attribute so it can be used directly in action

**Describe alternatives you've considered**
This one :( 
![image](https://github.com/alandtse/tesla/assets/9821946/baa192e2-b838-4861-9d13-670b85209751)

**Additional context**
I think I know why it has been done this way: This value is useless as it will not update itself between each tesla API call.

Maybe we could provide our own computed active_route_minutes_to_arrival ? with an event each minute and update it on each API call?

**Comment by zzarne** [comment]
I wouldn't like this integration to provide redundant data, but you can create a [template sensor](https://www.home-assistant.io/integrations/template/) with one of these templates:

```python
{{ (states('sensor.tesla_arrival_time') | as_timestamp - now() | as_timestamp) / 60 }}
```
or
```python
{{ (states('sensor.tesla_arrival_time') | as_timestamp - now().timestamp()) / 60 }}
```
Replace "tesla" with your car's entity base name in HA. Name it, for example, sensor.tesla_arrival_in_minutes and use it in your automation. Note that the value will start to become negative once the car has arrived. You can prevent this with a `(..., 0)| max` filter at the end of the template.

**Comment by storm1er** [comment]
Wooooh, fills perfectly the need, thanks a lot <3

But I really think this should be implemented directly into the integration. Can we consider this?

**Comment by storm1er** [comment]
Also, for the record, the full config is:

```

template:
  - sensor:
    - name: "Tesla arrival time remaining"
      unique_id: "ts_arrival_time_remaining"
      unit_of_measurement: "minutes"
      state: "{{ (states('sensor.<tesla_name>_arrival_time') | as_timestamp - now().timestamp()) / 60 }}"
```
