### ISSUE TITLE
Error when loading conf file: Component polling_interval Integration 'polling_interval' not found.

### ISSUE THREAD

**Issue by lamsof** [alandtse/tesla#666]
Issues not containing the minimum requirements will be closed:

Step to reproduce:
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3 on **Rasberry PI 3**
Tesla app v3.15.1

HACS : Download Tesla Customer App
In Dev menu, load configuration.yaml file

An erreur is displayed
Package services setup failed. Component polling_interval Integration 'polling_interval' not found.

![image](https://github.com/alandtse/tesla/assets/127216895/7a839c40-bf9e-49b8-8c79-4323f38affe8)

I tried to install previous version 3.13 and it is the same error.

The issue seems located in the file /config/custom_components/tesla_custom/services.yaml
I comment the last part "polling_interval", the configuration.yaml file is now valid and I can restart HA.

**Comment by alandtse** [comment]
Use the integrations menu to configure. Configuration.yaml is not supported.
