### ISSUE TITLE
Where to check polling_interval for a specific car?

### ISSUE THREAD

**Issue by edmooredop** [alandtse/tesla#669]
Hey, possibly a dumb question - I'm trying to debug some automations and can't find a way to check the integration thinks the polling interval is set to. It doesn't appear to be exposed as an entity in HA. If I hit "configure" on the integration I see what I assume is the default polling interval, but I don't seem to be able to make this change with the documented service call, whether or not I provide the VIN.

**Comment by alandtse** [comment]
Polling interval isn't set by car but for the entire integration. The poll switch allows you to exclude specific vehicles from the polling. See https://github.com/alandtse/tesla/wiki/Polling-policy for details on how polling works.

**Comment by edmooredop** [comment]
Hey Alan, apologies I don’t think I described my issue clearly.

I’ve been adding all the automations suggested in your polling interval examples, but they don’t seem to be working. To debug them I’m trying to find a way to see if the integration polling interval is being changed by the service call.

Is that exposed to the user anywhere? As mentioned I can see reference to it in the “configure” options but that seems to stay at 660s despite the automations trying to set it to 30s.

Thank you for your time and your brilliant work on this integration.

Ed Moore ʙsᴄ • Cinematographer
07980 524136 | edmoorebsc.com

**Comment by alandtse** [comment]
Nope. That info isn't exposed. It'd have to be a feature request to expose them.
