### ISSUE TITLE
TeslaMate MQTT not working (TeslamateID: None)

### ISSUE THREAD

**Issue by oakedcorn** [alandtse/tesla#684]
I'm a new user of this integration and I'm trying to set up the connection to TeslaMate via MQTT. But it seems that the MQTT subscribe topics are not rendered because my TeslamateID is somehow 'None' (there are no MQTT messages in the log file either and the integration reverts to the Tesla API).

```
DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:xxx TeslamateID: None
```
```
            if teslamate_id is not None:
                await self._get_car_topic(
                    car=car, teslamate_id=teslamate_id, topics=topics
                )
```

Where is TeslamateID supposed to be coming from? There does not seem to be a configuration entry, I tried setting it via the hidden entity, but that's not working either:
<img width="389" alt="image" src="https://github.com/alandtse/tesla/assets/45131487/7ed816be-abd8-4b0c-86eb-726e9ebcb167">

## Version of the custom_component
v3.15.2

## Configuration
see screenshot above

**Comment by oakedcorn** [comment]
Nevermind this ticket, it seems to be solved now but I'm not sure how. I tried multiple things, but in the end what I think did the trick is unhiding the teslamate id entity, set it to 1 and reloading the integration. 
Please close this ticket.

**Comment by LPirro** [comment]
@oakedcorn I'm having this problem as well. What you mean by unhiding the teslamate id entity, set it to 1?

**Comment by oakedcorn** [comment]
@LPirro, there's an entity called "Teslamate id" in the Tesla entities list which is hidden by default (click "show hidden entities" at the top). It needs to be unhidden (select the entity check box and click the unhide icon). After that it should be set to 1 (at least if you have one car only). A restart of HA may be needed between these actions - I'm not completely sure about that.
