### ISSUE TITLE
MQTT boolean conversion issue

### ISSUE THREAD

**Issue by oakedcorn** [alandtse/tesla#689]
## Configuration
Teslamate MQTT

## Describe the bug
Boolean entities are not updated correctly from MQTT (e.g. sentry mode, is_climate_on). I think it's due to ReceiveMessage returning msg.payload as a string, which is then casted to bool. But this doesn't work since bool("false") or even bool("False") always returns True.

**Comment by cguedel** [comment]
That's exactly what's the problem, thanks for figuring that out. I've added the following method to `teslamate.py`:
```
def cast_bool(val: str) -> bool:
    """Convert bool string to actual bool"""
    return val.lower() in ['true', 'True']
```

and changed the `MAP_*_STATE` maps to use that instead. That makes my `lock` entity change state flawlessly whenever Teslamate returns a changed value. I'm also intending to update some other entities that are currently not updated from MQTT using the same mechanism and then add a PR here.

**Comment by alandtse** [comment]
Thanks for reporting. Happy to take a PR to resolve this.
