### ISSUE TITLE
Icons for climate presets

### ISSUE THREAD

**Issue by hanpq** [alandtse/tesla#725]
Now (as of HA 2023.10) with the tile card being able to show preset buttons it would be nice if icons could be added for the different presents. 

This is how it currently looks,
![image](https://github.com/alandtse/tesla/assets/33247576/46755c4d-9301-4ed4-bb4d-0eca26ea6ed5)

A suggestion of icon could be:

Normal = mdi:fan
Defrost = mdi:car-defrost-rear
Keep on = mdi:infinity
Dog mode = mdi:dog-side
Camp mode = mdi:tent

**Comment by alandtse** [comment]
Thanks. Hopefully someone is willing to offer a PR to add the suggestions.
