### ISSUE TITLE
Failed to setup message after working for months

### ISSUE THREAD

**Issue by jgibo1** [alandtse/tesla#728]
I have been using this successfully to change my Time of use percentage to recharge at night. Tried reloading and also deleted and reinstalled. Still not working.

-->

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by Toolroom1** [comment]
Same for me, I was totally releying on this.

**Comment by tannerwastaken** [comment]
Same issue as #724
