### ISSUE TITLE
Please can someone help me connect to HA Tesla Powerwall app (not Custom)

### ISSUE THREAD

**Issue by Toolroom1** [alandtse/tesla#729]
On my mobile phone I have logged into the TEG-XXX network, although cannot log into a browser once connected. Once the WiFi is connected I then looked up the IP Address shown, I then used this IP when asked trying to get into the HA app followed by the password which I use the last 5 characters of my Powerwall Serial Number, but it fails every time. Any help much appreciated.

**Comment by alandtse** [comment]
This is not the right place to ask this.
