### ISSUE TITLE
Logbook entries repeatedly reporting entities as unavailable

### ISSUE THREAD

**Issue by billraff** [alandtse/tesla#736]
I installed this integration yesterday and have observed that every few minutes (not correlated to the polling setting in seconds as best I can tell) the entire collection of entities becomes unavailable and then returns. I can watch this happen -

 
<img width="650" alt="Screenshot 2023-10-09 at 9 22 19 AM" src="https://github.com/alandtse/tesla/assets/29167787/c3e0b277-8577-431a-beca-6af7cf0da05d">
<img width="668" alt="Screenshot 2023-10-09 at 9 24 04 AM" src="https://github.com/alandtse/tesla/assets/29167787/fc498a6c-ff09-4469-852b-218076714c79">

What could be causing this behavior? I assume it's on my side since I didn't see any issues describing this. My goal was to create an automation or two but if the automation were to try to run when the entities are unavailable it would fail.

**Comment by purcell-lab** [comment]
It would be really helpful if you could add the debug log to this issue, so we can see what the logs are reporting.

You can enable debugging from the integration tile.

![Screenshot 2023-10-10 09 22 05](https://github.com/alandtse/tesla/assets/79175134/7169c4a4-fd79-4031-8ff3-f6bff07d91b0)

**Comment by billraff** [comment]
I enabled the debug in the integration while the sensors were showing as available. Waited for them to become unavailable and then return to normal. Only took a few minutes. Is the debug log its own file somewhere or is it written to the home-assistant.log?

**Comment by purcell-lab** [comment]
> Is the debug log its own file somewhere or is it written to the home-assistant.log?

When you switch off debug, it should download the debug file to your browser.

The details are also available in your home-assistant.log

**Comment by billraff** [comment]
Attaching log file.
[home-assistant_tesla_custom_2023-10-10T10-50-59.083Z.log](https://github.com/alandtse/tesla/files/12856205/home-assistant_tesla_custom_2023-10-10T10-50-59.083Z.log)

**Comment by alandtse** [comment]
The logs are saying there's a connection error.
`httpcore.ConnectError: All connection attempts failed`
That typically indicate an error outside of the component. It could be the hardware, network connection, or your ISP. You will note that `homeassistant.components.openweathermap.weather_update_coordinator` also had trouble with the connection.

That said, at the end it appears to have resolved itself. But at this point, the logs don't show anything we can resolve.

**Comment by billraff** [comment]
Thank you for looking at the log. I'll do some digging on my end.
