### ISSUE TITLE
FR: Update service call to return JSON data response

### ISSUE THREAD

**Issue by purcell-lab** [alandtse/tesla#737]
**Is your feature request related to a problem? Please describe.**

Home Assistant Services can now respond with data:
https://www.home-assistant.io/blog/2023/07/05/release-20237/#services-can-now-respond
The technical developer reference is available here:
https://developers.home-assistant.io/docs/dev_101_services/#response-data

The Tesla Custom Integration provides for a the calling of services in particular the calling of end points, but currently doesn't provide the data response associated with a call:

![image](https://github.com/alandtse/tesla/assets/79175134/11d2f2fb-c9d0-4632-b2e5-da596e3c85cb)

**Describe the solution you'd like**
It would be great for debugging and creating additional sensors if the custom integration service could be updated to provide the JSON response:

```json
cli.py -e mark@purcell.id.au -z PRODUCT_LIST
{
    "response": [
        {
            "id": XXX,
            "user_id": XXX,
            "vehicle_id": XXX,
            "vin": "XXX",
            "color": null,
            "access_type": "DRIVER",
            "display_name": "Betty",
            "option_codes": null,
```

**Describe alternatives you've considered**
I am currently using additional python scripts to query the API and provide the JSON responses for the additional end points I am interested in.

```
$ ./get_period.py 
{"tou_period": "SUPER_OFF_PEAK", "buy_cost": 0.01, "sell_price": 0}

#!/usr/bin/env python3

try:
    import teslapy
except ImportError:
    print("Error: The teslapy module is not installed.")
    exit()

import teslapy
import datetime
import json

def get_current_tou_period(seasons_data):
    current_hour = datetime.datetime.now().hour
    current_minute = datetime.datetime.now().minute
    current_day_of_week = datetime.datetime.now().weekday()

    for season, data in seasons_data.items():
        for period, time_ranges in data['tou_periods'].items():
            for time_range in time_ranges:
                from_hour = time_range['fromHour']
                to_hour = time_range['toHour']
                from_minute = time_range['fromMinute']
                to_minute = time_range['toMinute']
                from_day_of_week = time_range['fromDayOfWeek']
                to_day_of_week = time_range['toDayOfWeek']

                if from_day_of_week <= current_day_of_week <= to_day_of_week:
                    if from_hour < to_hour: 
                        if (from_hour < current_hour < to_hour) or (from_hour == current_hour and from_minute <= current_minute) or (to_hour == current_hour and current_minute < to_minute):
                            return period
                    elif to_hour < from_hour:  # This handles the case where the period starts in the evening of one day and ends in the early morning of the next
                        if (current_hour > from_hour) or (current_hour < to_hour) or (from_hour == current_hour and from_minute <= current_minute) or (to_hour == current_hour and current_minute < to_minute):
                            return period
    return 'Unknown Period'

with teslapy.Tesla("mark@purcell.id.au") as tesla:
    tesla.fetch_token()
    battery = tesla.battery_list()[0]
    tariff_data = battery.api('SITE_TARIFF')['response']

    current_season = 'Summer'  # you may need to implement a way to determine the current season dynamically
    current_tou_period = get_current_tou_period(tariff_data['seasons'])

    buy_cost = tariff_data['energy_charges'][current_season].get(current_tou_period, 'N/A')
    sell_price = tariff_data['sell_tariff']['energy_charges'][current_season].get(current_tou_period, 'N/A')
```

```
./get_tariff.py 
{
    "response": {
        "code": "(edited)",
        "name": "Spotprice",
        "utility": "Amber",
        "daily_charges": [
            {
                "amount": 0,
                "name": "Charge"
            }
        ],
        "demand_charges": {
            "ALL": {
                "ALL": 0
            },
            "Summer": {},
            "Winter": {}
        },
        "energy_charges": {
            "ALL": {
                "ALL": 0
            },
            "Summer": {
                "OFF_PEAK": 0.1,
                "ON_PEAK": 15,
                "PARTIAL_PEAK": 1,
                "SUPER_OFF_PEAK": 0.01
            },
            "Winter": {}


#!/usr/bin/env python3
import teslapy
with teslapy.Tesla("mark@purcell.id.au") as tesla:
        tesla.fetch_token()
        battery = tesla.battery_list()[0]
#        tariff = battery.api('SITE_TARIFF')
#        battery.set_backup_reserve_percent(100)
#        battery.set_operation(backup)

#        print(battery) # should print battery status once successfully authenticated
#        print('----')
        print(battery.api('SITE_TARIFF'))
        

```

**Additional context**
A similar interface as per other services which have enabled responses would be great:
![image](https://github.com/alandtse/tesla/assets/79175134/4b08715f-320a-423f-b85f-8dc206f3aaa4)

**Comment by alandtse** [comment]
Happy to take a PR.

**Comment by purcell-lab** [comment]
With some help from my friend ChatGPT, I have a working solution. I'll upload the PR shortly.

![Screenshot 2023-10-26 11 41 07](https://github.com/alandtse/tesla/assets/79175134/ee934678-178e-4553-b91c-b1f959dabd33)

![Screenshot 2023-10-26 11 41 24](https://github.com/alandtse/tesla/assets/79175134/bff33e1a-9081-4834-9c85-6004276e7fdf)



To allow a service call to return results, you'll need to make a few modifications to your code. The process involves:

1. Ensuring that the service method returns a dictionary or similar structured data.
2. When registering the service, specify that it supports responses.

Let's walk through the changes step by step:

### 1. Modify the Service Methods to Return Responses

In the `api` method:
```python
    response = await controller.api(name=command, path_vars=path_vars, **parameters)
    return {"result": response}
```

In the `set_update_interval` method:
```python
    controller.set_update_interval_vin(vin=vin, value=update_interval)
    return {"result": True, "message": f"Update interval set to {update_interval} for VIN {vin}"}
```

### 2. Modify Service Registration to Support Responses

When registering the service, add the `supports_response=True` argument:

```python
    hass.services.async_register(
        DOMAIN,
        SERVICE_API,
        async_call_tesla_service,
        schema=API_SCHEMA,
        supports_response=True,
    )

    hass.services.async_register(
        DOMAIN,
        SERVICE_SCAN_INTERVAL,
        async_call_tesla_service,
        schema=SCAN_INTERVAL_SCHEMA,
        supports_response=True,
    )
```

### 3. Handle the Response in the Service Call Dispatcher

Modify the `async_call_tesla_service` function to return the result of the called service:

```python
    async def async_call_tesla_service(service_call) -> None:
        """Call correct Tesla service."""
        service = service_call.service
        response = None

        if service == SERVICE_API:
            response = await api(service_call)
        elif service == SERVICE_SCAN_INTERVAL:
            response = await set_update_interval(service_call)

        return response
```

### Final Notes:

- The modifications allow the service to return a structured response, which will be visible when calling the service via the Home Assistant frontend's developer tools.
  
- The changes ensure that when a service is called, it will provide feedback in the form of a structured response, enhancing user experience and potentially helping in debugging issues.

- The returned dictionary in each service method can be adjusted as per your requirements. The provided examples are generic and meant to illustrate the process.

By making these modifications, you should be able to see the responses from the service calls directly in the Home Assistant interface or any other method you use to invoke the services.
