### ISSUE TITLE
KeyError after updating to 3.18.0

### ISSUE THREAD

**Issue by luisiam** [alandtse/tesla#738]
## Version of the custom_component
3.18.0

## Configuration

```yaml
N/A
```

## Describe the bug

I only have solar panel (wihout powerwall). The integration stops working after updating to 3.18.0 with the following error in the logs. Downgrading to 3.17.1 fixes the issue.

## Debug log

```text

2023-10-09 22:19:17.075 ERROR (MainThread) [custom_components.tesla_custom] Unexpected error fetching tesla_custom data: 2252178759248406
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/__init__.py", line 440, in _async_update_data
    return await self.controller.update(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 825, in update
    return any(await asyncio.gather(*tasks))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 716, in _get_and_process_site_summary
    self._site_summary[energysite_id].update(response)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 2252178759248406

```

**Comment by d2inco** [comment]
Same situation here; I have Tesla (legacy SolarCity) Solar Panels, no Powerwall.  Downgrading  back to 3.17.1 fixes the problem.    When I'm back home, I'll re-upgrade and upload debug logs if @alandtse has not done that already.

**Comment by gkwok1** [comment]
@d2inco @luisiam Please try my fork and see if that fixes the issue. I added some code to only check site summary for battery systems. I have a system with PW so I can't really test the code for system w/o PW.

https://github.com/gkwok1/teslajsonpy/archive/refs/heads/dev.zip

Copy the teslajsonpy folder in the zip file to /config on HA and restart.

**Comment by luisiam** [comment]
> @d2inco @luisiam Please try my fork and see if that fixes the issue. I added some code to only check site summary for battery systems. I have a system with PW so I can't really test the code for system w/o PW.
> 
> https://github.com/gkwok1/teslajsonpy/archive/refs/heads/dev.zip
> 
> Copy the teslajsonpy folder in the zip file to /config on HA and restart.

Updated the integration to 3.18.0. Extract and copy teslajsonpy folder under /config on HA. Restart HA and it is still working. Looks like that fixes the issue.

**Comment by gkwok1** [comment]
@luisiam @alandtse I created a PR in [teslajsonpy](https://github.com/zabuldon/teslajsonpy) and hopefully it will be merged into the next release.

**Comment by d2inco** [comment]
I dont see any PRs on this side -- It looks like teslajsonpy is locked at 3.9.5 in `pyproject.toml` , `scripts/setup`, and/or `manifest.json` .  Can we get it bumped to 3.9.6 to capture the fix for those of us with just solar panels and no powerwall?

**Comment by alandtse** [comment]
Sure we'll take a PR. However the PR has to fix the broken tests that were ignored to do the last release.

**Comment by sargonas** [comment]
Same issue here, reverted back to 3.17.1 for the interim and all's well. This is the 4th of 5th "breaking change" from updating something in HA in the last month or so that I had to roll back, so I think I'm going to spin up a secondary testing instance when I get home later today... once I do happy to help test and triage the above if folks still need help pinning things down.
