### ISSUE TITLE
Unexpected error fetching tesla_custom data: 2252156766135598

### ISSUE THREAD

**Issue by Jizzay1** [alandtse/tesla#752]
## Version of the custom_component

v3.18.0

## Configuration

no YAML

## Describe the bug

Tesla solar system only, was working fine until a week or so ago, solar_power sensor "unavailable".

no change in results after reloading the integration, restarting HA, removing and reinstalling integration.  sensor shows up correctly with no data.  my system is generating as normal, confirmed by Tesla App.

## Debug log

Unexpected error fetching tesla_custom data: 2252156766135598
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/__init__.py", line 440, in _async_update_data
    return await self.controller.update(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 825, in update
    return any(await asyncio.gather(*tasks))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 716, in _get_and_process_site_summary
    self._site_summary[energysite_id].update(response)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 2252156766135598

**Comment by mitdesai** [comment]
I am facing the same issue. I am just starting up so I do not have any previous references.
But from what I have observed, 2 of my vehicles load perfectly fine. I have a Powerwall that is a separate site which loads fine as well. Only issue is with my 2 solar systems.

**Comment by alandtse** [comment]
Dupe #738
