### ISSUE TITLE
Beginning with 2023.38, location tracking fails

### ISSUE THREAD

**Issue by dennypage** [alandtse/tesla#756]
Beginning with 2023.38, Tesla introduced controls on location sharing. Location information now requires an approval grant from within the vehicle.

Relevant information can be found in the [vehicle_data endpoint](https://developer.tesla.com/docs/fleet-api#vehicle) in the Fleet API doc:

_For vehicles running firmware versions 2023.38+, location_data is required to fetch vehicle location. This will result in a location sharing icon to show on the vehicle UI._

**Comment by fgonza2** [comment]
i am seeing this issue as well, how can you approve it in-vehicle so it works?

**Comment by dennypage** [comment]
Not sure if it can be fixed with the current API...

**Comment by darek-margas** [comment]
So goodbye tracking in apps?

**Comment by purcell-lab** [comment]
Fix available for teslapy, presumably it needs to be ported to teslajsonpy before it can make it into this Home Assistant integration.

https://github.com/tdorssers/TeslaPy/issues/147

**Comment by oakedcorn** [comment]
Issue logged in teslajsonpy: https://github.com/zabuldon/teslajsonpy/issues/434

**Comment by NickWhitNTES** [comment]
A fix is available for TeslaMate in a fork
https://github.com/teslamate-fork/teslamate-fork#installation-of-the-fork-with-the-fix-for-tesla-fw-2023381

Can this same code fix be applied to this Integration?
