### ISSUE TITLE
Charger plugged in state not correct in v3.19.0 (MQTT sync enabled)

### ISSUE THREAD

**Issue by oakedcorn** [alandtse/tesla#761]
The car is physically plugged in, but the state of the charger entity is "unplugged". When triggering a data refresh it goes to the correct state, but a short moment later it switches back to "unplugged".

This behavior was observed after upgrading from v3.17.1 to v3.19.0. I have now switched back to v3.17.1 as a workaround.

Maybe related to this recent change?
[2eb4b537c3b5843455e933d0017727b1dc264ef2](https://github.com/alandtse/tesla/commit/2eb4b537c3b5843455e933d0017727b1dc264ef2)

**Comment by dagstuan** [comment]
I think I have an idea of what's causing this. I'll test a little bit with my own car and then send a new PR. Mapping between plugged_in and charging from Teslamate is not the easiest since the states don't line up perfectly.

**Comment by mlamberts78** [comment]
Same issue here, turned MQTT on today and see same behavior, charger is connected, but reports unplugged.

**Comment by dagstuan** [comment]
The fix in #764 seems to work fine for me for a few days now. Just waiting for @alandtse to merge it :)
