### ISSUE TITLE
Add new car?

### ISSUE THREAD

**Issue by cb2206** [alandtse/tesla#767]
Hi,
I sold my old car and bought a new one. It's the same model and is (currently) also named the same. 

In HA, I still see the device representing the old car and was kind of hoping it would just pick it up as the new one so that I don't need to recreate automations etc but the device is not pulling any data and also no new device for the new car showed up.

What's the best way to proceed?

Thanks

**Comment by alandtse** [comment]
The next reboot should detect the new car as a new entity. Or you can remove and readd to force it to look for new vehicles. Unfortunately, we rely on the API car ID which isn't tied to the name at all. You will need to change your entities in your automations.

**Comment by cb2206** [comment]
Great, thanks.
For others: The HA reboot didn't help in my case, deleting and re-adding the integration did.
