### ISSUE TITLE
Possibilty to remove a car from the integration

### ISSUE THREAD

**Issue by BarBaar44** [alandtse/tesla#769]
I have multiple cars in the integration as I had various loaner vehicles. Telsa now adds these automatically temporarily to your account and the integration picks them up. However, there is no way to remove these vehicles

**Describe the solution you'd like**
Be able to remove individual cars from the integration

**Describe alternatives you've considered**
reinstalling the integration. But that is only a workarounds

**Additional context**

**Comment by alandtse** [comment]
This is something HA needs to solve. The component only provides info on what is currently in the API. HA remembers all devices unless the component is removed. HA will need to provide deletion functionality. Your option is to wait or remove and readd the component.

**Comment by BarBaar44** [comment]
Not completely sure tbh. If you look at the shelly integration for example, it does have to option to remove device from the integration..

**Comment by mattster98** [comment]
Agreed about how Shelly is doing it.  I think it depends on what is enumerated when you set it up.  For Shelly devices, you add one per device, for Tesla, you add the account, which includes all the "devices" on the account.  I just got finished removing the integration and re-adding it, which worked, but far from convenient, especially given how long HA hung when I told it to delete.

If the inclusion workflow pulled the vehicles from your account then let you select the ones you want to include, then add them as independent items, that might work.  

HA clearly has support to delete things, if you create them in the right way.
