### ISSUE TITLE
Charger switch no longer works

### ISSUE THREAD

**Issue by Kopite1892** [alandtse/tesla#782]
Version 3.19.3

The switch to turn charger on\off has disappeared.

**Comment by skipishere** [comment]
Can we have some more information, are other parts missing as well? I'm currently on 3.13.3 and it's there and working. 
![image](https://github.com/alandtse/tesla/assets/26724777/c81ca47a-3826-4a3b-8628-d45820963bd5)

**Comment by Kopite1892** [comment]
I seem to have rectified it by uninstalling reinstalling
