### ISSUE TITLE
Car not sleeping while this integration is enabled - default polling settings

### ISSUE THREAD

**Issue by lellis2k** [alandtse/tesla#785]
### Discussed in https://github.com/alandtse/tesla/discussions/765

<div type='discussions-op-text'>

<sup>Originally posted by **lellis2k** November  7, 2023</sup>
My car was draining 9% in half a day so I changed my Tesla account password (to kick off other third party apps) and re-enabled only this integration. It still dropped by the same amount. 
I changed the password again, and didn't enable this integration and it now only drained 3% per day.

I posted this screenshot to FB and someone pointed out that the car must be awake this whole time for HA to have constantly changing data. How can I troubleshoot this to allow my car to sleep as much as it would without the integration? I'd like the data there when the car would be awake anyway, just don't want extra battery drain from it if possible. 2015 Model S 85.

![395425012_10160821848139174_3162632161537841073_n](https://github.com/alandtse/tesla/assets/3228976/4a1428f6-a7f8-4208-a031-bbc027a87cc4)
</div>

Originally raised in discussion but received no responses

**Comment by skipishere** [comment]
No need to duplicate. Will add reply in discussion.
