### ISSUE TITLE
Making issue reporting more consistent in GitHub

### ISSUE THREAD

**Issue by skipishere** [alandtse/tesla#788]
Was browsing the GitHub docs and it appears we can customise the Issue creation screen (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) including disabling creating an issue without a template. This might be a good way to encourage users who find an issue to use the correct template when reporting an issue.

Because it just pre-fills in an issue with information, a user could then delete it all and type in whatever they want (so it doesn't stop people reporting in a different style) but hopefully encourages users to give the information we need to potential investigate/resolve an issue.

I'm happy to investigate further (& make a PR if we go forward) but wanted to raise this to get other opinions/thoughts around it.

**Comment by alandtse** [comment]
That could be helpful. There are other actions that will [autoclose](https://github.com/alandtse/alexa_media_player/blob/dev/.github/workflows/autocloser.yaml) if the template doesn't match close enough. I do think we should consider one like [HA uses with dropdowns](https://github.com/home-assistant/core/blob/dev/.github/ISSUE_TEMPLATE/bug_report.yml). I wonder if it can feed the version from the releases we've done. I haven't had the time to experiment but if you're willing to investigate. Please do. 

You're probably seeing first hand where some templates would help best.

**Comment by skipishere** [comment]
Interestingly enough that was where I was starting from and ended up getting side tracked with seeing the forms and custom template chooser. I'm sure the end result will be a mix of all 3. I'll try and play with these this week 👍
