### ISSUE TITLE
Only read possible

### ISSUE THREAD

**Issue by JoseMadbird** [alandtse/tesla#799]
Hello. 

is Tesla custom integration available for highland model 3? Is possible to have problems due this new model?

I´ve installed V3.19.3 and i would say only have access to read the car, not possible to "write", Any script requesting a change, i´m receiving an error, but for example for "wake_up" example i´m receiving an answer by car, also i can see all the values from Car, charge, status, etc

Example, script:
_______________________
service: tesla_custom.api
data:
  command: CHANGE_CHARGE_LIMIT
  parameters:
    percent: "56"
    path_vars:
      vehicle_id: "***************"
    wake_if_asleep: true
________________________________

I´m receiving this error after some seconds "No se pudo llamar al servicio tesla_custom.api. Unknown error" --> Couldn´t call the service........

Can i get some help? I want to do some automations changing the "charge Options"

Many thanls in advance

**Comment by skipishere** [comment]
You are possibly affected by https://github.com/alandtse/tesla/issues/743 as new cars won't use the unofficial API we currently use.

**Comment by skipishere** [comment]
Cool, in which case I'll close this as a duplicate for now but feel free to re-open it if it turns out not to be
