### ISSUE TITLE
Deprecated constant in HA 2025.1

### ISSUE THREAD

**Issue by sh4rks** [alandtse/tesla#810]
## Version of the custom_component

Latest (3.19.5)

## Describe the bug

Some constants will disappear in HA 2025.1

## Debug log

Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 4 janvier 2024 à 16:31:40 (14 occurrences)
Last logged: 4 janvier 2024 à 16:32:06

PRESSURE_BAR was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.BAR instead, please create a bug report at https://github.com/alandtse/tesla/issues
PRESSURE_PSI was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.PSI instead, please create a bug report at https://github.com/alandtse/tesla/issues
SPEED_MILES_PER_HOUR was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.MILES_PER_HOUR instead, please create a bug report at https://github.com/alandtse/tesla/issues
TEMP_CELSIUS was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/alandtse/tesla/issues
ELECTRIC_CURRENT_AMPERE was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please create a bug report at https://github.com/alandtse/tesla/issues

Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:204
Integration: Dispositif de suivi (documentation, issues)
First occurred: 4 janvier 2024 à 16:32:06 (2 occurrences)
Last logged: 4 janvier 2024 à 16:32:06

SOURCE_TYPE_GPS was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please create a bug report at https://github.com/alandtse/tesla/issues

**Comment by alandtse** [comment]
Thanks for reporting. We're near the end of the lifecycle for this, but perhaps we can resolve it.

**Comment by ZoomeoTooknor** [comment]
It seems that no action is functional anymore (opening windows, managing temperature, heating, etc.)

**Comment by Sandvoxel** [comment]
> It seems that no action is functional anymore (opening windows, managing temperature, heating, etc.)

Yea I can push any changes to my car such as heat cool or anything really but it seems to be reading the data ok for now.
