### ISSUE TITLE
Update from v3.19.3 to v3.19.6 didn't work

### ISSUE THREAD

**Issue by denisjoshua** [alandtse/tesla#822]
## Version of the custom_component
v3.19.3 to v3.19.6

## Describe the bug
I try to update from v3.19.3 to v3.19.6 but HA didn't want to finish the update. 
Is just stay there and try to update.
I don't know where to see a LOG of the errors. 

## Debug log
In the Log Viewer I don't see anything about HACS or Tesla plugin 

Thanks in advance 

```

**Comment by alandtse** [comment]
3.19.6 is a beta release. Choose a non beta.

**Comment by denisjoshua** [comment]
And how can i choose please ? 
I have only one UPDATE button 
Thanks again

**Comment by alandtse** [comment]
Disable beta versions in options.

**Comment by denisjoshua** [comment]
Whoauuu greate :-) 
Now it's work. 
Thanks a lot
