### ISSUE TITLE
Increase polling rate while car charging

### ISSUE THREAD

**Issue by furstyferret-dev** [alandtse/tesla#824]
**Is your feature request related to a problem? Please describe.**
Due to the extended polling interval the integration picks up the fact that the car is charging, but not that it’s finished charging. This causes the wrong data to be passed to other components in Home Assistant (eg power cards, which show a constant 7kW hours after the car has stopped charging). 

**Describe the solution you'd like**
Poll every few minutes while the car is charging. It’s already awake so there’s no battery problem. 

**Describe alternatives you've considered**

**Additional context**

**Comment by alandtse** [comment]
This already happens.  Please review the wiki.

**Comment by furstyferret-dev** [comment]
Well, fairly obviously it doesn’t.

**Comment by skipishere** [comment]
@furstyferret-dev the page you want to look at is https://github.com/alandtse/tesla/wiki/Dynamic-Polling-Frequency
