### ISSUE TITLE
HA Guage Displays Non-Numeric (if car deep sleeps?)

### ISSUE THREAD

**Issue by tonywheeler60** [alandtse/tesla#825]
HA guage display shows Non-numeric after a certain time that is suspected to be based upon car sleep state.

I'm using a simple HA guage to represent the car charge state percentage.  This works perfectly most of the time but after a certain time the guage cannot be shown in HA and the screen shows this warning:

![Entity is non-numeric](https://github.com/alandtse/tesla/assets/69424200/5cb6a730-f0f8-42eb-ab41-3ee750ad77ee)
- Entity is non-numeric

I guess this is because the car is asleep but my question is can you use the last value given if the car sleep state is asleep?  I'd imagine this is fraught with potential issues so if you have any advice on how I can better handle (what is a very minot display issue) I'd greatly appreciate it.  I also appreciate that this may not be seen as a bug at all.

I've seen this on many versions of the integration but it shows right now on your latest release: 3.19.5

Thanks in advance - and especially for this integration.

**Comment by skipishere** [comment]
The integration does keep the last state value while the car is asleep. Normally the only time the value is non-numeric is after a restart of home assistant.

**Comment by skipishere** [comment]
Best bet would be to check the logs there might be a clue in there as to why, otherwise you can try looking at the history and seeing if there is a pattern when it loses state.

I've got the same guage setup with my car and apart from after a reboot of home assistant it always has a numeric value.

**Comment by skipishere** [comment]
Going to close this as without any information there isn't anything that can be done
