### ISSUE TITLE
PRESSURE_BAR to be depreciated

### ISSUE THREAD

**Issue by nilremgithub** [alandtse/tesla#829]
HA Log reports "PRESSURE_BAR was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.BAR instead"

Home Assistant 

2023.44.30.9

## Configuration

PRESSURE_BAR was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.BAR instead

## Describe the bug

Error reported in log..

## Debug log

```text

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 22 January 2024 at 14:11:19 (12 occurrences)
Last logged: 22 January 2024 at 14:11:19

PRESSURE_BAR was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.BAR instead, please create a bug report at https://github.com/alandtse/tesla/issues

```

**Comment by skipishere** [comment]
Duplicate (and fixed) in #810
