### ISSUE TITLE
Tesla powerwall - controls stopped working tonight , in particular the operation mode

### ISSUE THREAD

**Issue by ChillV2L** [alandtse/tesla#832]
## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by ChillV2L** [comment]
as per title ,

**Comment by sb2-brendan** [comment]
Can confirm that PW controls have stopped working. I've enabled debug logging and this is the result:

`2024-01-26 15:08:44.042 DEBUG (MainThread) [teslajsonpy.energy] Sending command: BATTERY_OPERATION_MODE
2024-01-26 15:08:44.042 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 7:57:54
2024-01-26 15:08:44.043 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/energy_sites/XXXXXXXXXXX/operation {'default_real_mode': 'autonomous'}
2024-01-26 15:08:44.238 DEBUG (MainThread) [teslajsonpy.connection] 401: {"response":null,"error":"https://powergate.prd.sn.tesla.services:443/api/v2/energy_site/operation =\u003e Unauthorized. Please register third-party account at https://developer.tesla.com/docs/","error_description":""}
2024-01-26 15:08:44.238 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140613442824896] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 195, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/tesla_custom/select.py", line 338, in async_select_option
    await self._energysite.set_operation_mode("autonomous")
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/energy.py", line 202, in set_operation_mode
    data = await self._send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/energy.py", line 61, in _send_command
    data = await self._api(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 1319, in api
    return await self.__post_with_retries_except_unavailable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 1351, in __post_with_retries_except_unavailable
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/connection.py", line 165, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/connection.py", line 216, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException`

**Comment by GammaScorpii** [comment]
Not working here either. Whenever I try to adjust the backup reserve I get this error pop up:
Failed to call service number/set_value. unknown error

Changing the backup mode also doesn't work:
Failed to call service select/select_option. unknown error

Strangely I can still read values like the battery level in HA.

**Comment by MikeatLorne** [comment]
I have the same symptoms - incoming information is fine but I cannot direct operation mode or reserve %

**Comment by SalisburyLad** [comment]
Attempts to change any of the parameters fail with: Failed to call service number/set_value. unknown error

**Comment by liveleeiow** [comment]
I’ve the same issues. I noticed around 20:00 uk time on 25th Jan.

I played around for a few hours and then gave up and went to bed.  I was hopeful it was a global issue rather than just me.

**Comment by AlexCWorrall** [comment]
Same here. Noticed failure at around 10pm UK on 25th January. Unable to change the backup reserve level.

**Comment by Gerynant24** [comment]
Also same here, reading is fine, just cannot write to the backup reserve any more.

**Comment by skipishere** [comment]
Please refrain from posting "me too" like posts, if you have more details to add or you are able to help then thanks.

Otherwise please use the subscribe button to be updated on any fixes/news around this issue.

**Comment by mcc05** [comment]
So I bumped teslajsonpy version to 3.9.9 in the manifest and control seems to be back

**Comment by Verbosed** [comment]
I have no coding expertise and am merely a very contented user of this HAC add on which I use to schedule overnight charging of my PW2 at advantageous electricity rates.

As I understand it to date we have been accessing/controlling our PW2 via a not officially (Tesla) sanctioned method via backdoor analysis/manipulation of their API

Reading around online it would appear that Tesla are now implementing an official method whereby third party developers can register their applications and have official access to their Tesla API. 

https://gearmusk.com/2023/10/14/tesla-launches-developer-api/

Looking at part of the debug log pasted earlier in this thread shows

“Unauthorized. Please register third-party account at https://developer.tesla.com/docs/","error_description":""}”

My fear is this is a conscious decision by Tesla to block (unless you have registered your application) access to their API. 

Additionally whilst access to their API is apparently currently free and whilst only conjecture on my part, they may commence charging a la twitter …

I sincerely hope I’m wrong as this application is perfect for my current needs ….

**Comment by JasSmiths** [comment]
> So I bumped teslajsonpy version to 3.9.9 in the manifest and control seems to be back

Is this definitely working? If so, can provide instructions?

**Comment by GSV3MiaC** [comment]
Has the integration developer maybe registered the latest version, as seems to be required now??

**Comment by skipishere** [comment]
> Has the integration developer maybe registered the latest version, as seems to be required now??

There is a large amount of discussion on #743 and #774 in regards to the API being changed over

**Comment by mcc05** [comment]
Its a temp workaround until @alandtse can do a release I think, in the HA custom_components / tesla_custom folder, edit the manifest.jon file and change the line  "requirements": ["teslajsonpy==**3.9.9**"],

**Comment by skipishere** [comment]
> Its a temp workaround until @alandtse can do a release I think, in the HA custom_components / tesla_custom folder, edit the manifest.jon file and change the line "requirements": ["teslajsonpy==**3.9.9**"], restart HA

@mcc05 you could make a PR with that change here, it's open source so then you'd just need to wait for the Pull Request to be approved

**Comment by mcc05** [comment]
> > Its a temp workaround until @alandtse can do a release I think, in the HA custom_components / tesla_custom folder, edit the manifest.jon file and change the line "requirements": ["teslajsonpy==**3.9.9**"], restart HA
> 
> @mcc05 you could make a PR with that change here, it's open source so then you'd just need to wait for the Pull Request to be approved

Done

**Comment by GSV3MiaC** [comment]
Excuse ignorance, but how / from where is that new 3.9.9 version of teslajsonpy acquired?

**Comment by mcc05** [comment]
> Excuse ignorance, but how / from where is that new 3.9.9 version of teslajsonpy acquired?

Its a dependency, that this custom component code instructs HA to pull down from github.

**Comment by scotflieger** [comment]
I am having the same issues. I use set_value and select_option services to set number.battery_backup_reserve and select.battery_grid_charging entities. These worked yesterday but today (26 Jan) I am getting 'unknown home assistant' errors.

**Comment by Gerynant24** [comment]
> Its a temp workaround until @alandtse can do a release I think, in the HA custom_components / tesla_custom folder, edit the manifest.jon file and change the line "requirements": ["teslajsonpy==**3.9.9**"], restart HA

Worked a treat - Basic steps for beginners (like me) ;-)
Find the Terminal app in Settings>Addons and run the app to open  terminal window
Navigate to the folder custom_components/tesla_custom/
Then use nano manifest.json 
Edit the file as above then CTRL+X to save it.

Finally restart HA

**Comment by JasSmiths** [comment]
> Its a temp workaround until @alandtse can do a release I think, in the HA custom_components / tesla_custom folder, edit the manifest.jon file and change the line "requirements": ["teslajsonpy==**3.9.9**"], restart HA

The Hero we all needed. 

Thank you.

**Comment by Avatar1976** [comment]
> * cd custom_components/tesla_custom
> * vi manifest.json
> * Change "teslajsonpy==3.9.8" to "teslajsonpy==3.9.9"
> * Restart homeassistant
> * Profit

Done works perfectly, big thanks to @mcc05 for working it out first too.
And the upstream Teslajson.py project.
