### ISSUE TITLE
Able to pull device and the 56 entities but cant send commad to tesla.

### ISSUE THREAD

**Issue by reyesmarkfrancis** [alandtse/tesla#867]
## Configuration

```yaml
Add your logs here.
```

## Debug log

Failed to call service button/press. unknown error 
![Err](https://github.com/alandtse/tesla/assets/46152666/f3f78247-d2d5-4b53-a9ee-da9f8032be62)

Add your logs here.

```

**Comment by zorrobyte** [comment]
So, there's a new API out for Tesla that works a different way for controlling things in the car, can't remember the name of it specifically, but it needs more than a refresh token. I remember migrating to it when installing Tessie.

I also can't control things, and this is likely why

**Comment by skipishere** [comment]
#774 and #743 are about new API unable to do actions.

I'm going to close this as the original post lacks any detail to even know what the issue might be.
@reyesmarkfrancis if you have hit a new problem (that isn't covered by the mentioned ones or currently exists), please update the original post and we can reopen and investigate
