### ISSUE TITLE
Broken Link and Missing App for Tesla Tokens in README.md

### ISSUE THREAD

**Issue by muik** [alandtse/tesla#872]
I found a broken link (Android: [Tesla Tokens](https://play.google.com/store/apps/details?id=net.leveugle.teslatokens)) in the [README.md](https://github.com/alandtse/tesla/blob/68e805e8a8e24d0c81c124136255aeeef7e3d82f/README.md) file. Additionally, I searched for the Tesla Tokens app on the Google Play Store but could not find it.

The link needs to be updated for Android users.

Thank you!

**Comment by alandtse** [comment]
Works for me. I just tested it.

**Comment by baylanger** [comment]
Just for fun I tested it, somehow it also doesn’t work for me. 

![IMG_1293](https://github.com/alandtse/tesla/assets/5240348/2e57bea6-7f3d-4f6f-ac38-0a537a16b6d5)

URL is https://play.google.com/store/apps/details?id=net.leveugle.teslatokens

I’m not logged into any G account when doing this, just in case it could perhaps make a difference.

I tried to search for teslatokens and “tesla tokens”, nothing showed up.

**Comment by skipishere** [comment]
Also tried it and it didn't work for me either. Wondering if it's been limited by country or removed

**Comment by advertisingfree** [comment]
same here. not working
