### ISSUE TITLE
Key Error with vehicles that do not use the TESLA proxy (on version 3.20)

### ISSUE THREAD

**Issue by sladey** [alandtse/tesla#889]
My apologies but I lost the logs with the exact details of the error after I downgraded to v 3.19.11.   However when I tried v3.20.00 and did not install the API proxy (since I own a 2018 Model X) I got a 'key error' on the following line (line 144 - custom_components/tesla_custom/__init__.py) :

if config[CONF_API_PROXY_CERT]:

**Comment by alandtse** [comment]
@llamafilm we should probably use config.get with appropriate logic instead of direct key access. Can you please take a look throughout your changes for this issue?

**Comment by CrazyCoder** [comment]
Same issue here.

```
Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 14:46:27 (4 occurrences)
Last logged: 17:00:26

Error setting up entry <mail> for tesla_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/__init__.py", line 144, in async_setup_entry
    if config[CONF_API_PROXY_CERT]:
       ~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'api_proxy_cert'
```

**Comment by pviegas** [comment]
Still not working after upgrading to this version.
The new error is:

Logger: homeassistant.config_entries
Source: config_entries.py:528
First occurred: 8:59:09 AM (4 occurrences)
Last logged: 9:32:28 AM

Config entry 'pviegas@gmail.com' for tesla_custom integration could not authenticate

**Comment by llamafilm** [comment]
Can you enable debug logging for this component and then post the log output? (grep for tesla).

**Comment by llamafilm** [comment]
Are you using the API Proxy?  It should ask you to choose on the first step of the config flow, and there should be some line like this in the debug log to indicate which server it's using:
```
2024-03-11 03:20:04.060 DEBUG (MainThread) [teslajsonpy.connection] get: https://c03d64a7-tesla-http-proxy/api/1/products {}
```

**Comment by r0m1CH** [comment]
I'm not using it. 
I don't have any fleet API.

**Comment by MattJeanes** [comment]
I'm not using the API Proxy either

**Comment by mitchins** [comment]
I am beginning to suspect we've been shifted over, and the error messaging
is poor. I will have to try following the API proxy instructions and see if
it all works.

**Comment by DanielSzoska** [comment]
> Still not working after upgrading to this version. The new error is:
> 
> Logger: homeassistant.config_entries Source: config_entries.py:528 First occurred: 8:59:09 AM (4 occurrences) Last logged: 9:32:28 AM
> 
> Config entry '[pviegas@gmail.com](mailto:pviegas@gmail.com)' for tesla_custom integration could not authenticate

Was the same here, but https://github.com/alandtse/tesla/releases/tag/v3.20.2 fixed this. It's now working.

**Comment by pviegas** [comment]
> > Still not working after upgrading to this version. The new error is:
> > Logger: homeassistant.config_entries Source: config_entries.py:528 First occurred: 8:59:09 AM (4 occurrences) Last logged: 9:32:28 AM
> > Config entry '[pviegas@gmail.com](mailto:pviegas@gmail.com)' for tesla_custom integration could not authenticate
> 
> Was the same here, but https://github.com/alandtse/tesla/releases/tag/v3.20.2 fixed this. It's now working.

Yep. Same here. All working now!
Thanks for the fast fix guys. 👌

**Comment by skipishere** [comment]
It sounds like people who have updated to [v3.20.2](https://github.com/alandtse/tesla/releases/tag/v3.20.2) are now fixed. If this is still a problem then a new issue should be opened with details using the latest version.
