### ISSUE TITLE
Entities are not keeping their last known value

### ISSUE THREAD

**Issue by fcastilloec** [alandtse/tesla#9]
I'm not 100% sure if this is a bug or a feature request. As reported in #4 many of the entities stay in an unknown state until the car is awakened. This is understandable if the car was never awake when the first (or any subsequent) polling happen.

The problem I see is after a successful update happens (the car was awake when polled). If the car goes back to sleep, all the entities go back to being unknown. This shouldn't be the case for most (if not all) of the entities. When a car is asleep, many of these values remain constant. For example, the `mileage_sensor` should show the last valid value and keep that value until a successful update happens, the same should happen with the `location_tracker`. I would argue that this behavior should happen with every single entity. The temperature sensor might be an exception, but I rather see the last temperature recorded in my car rather than nothing at all.

Another issue is that some entities default to showing that some doors are actually unlocked, due to the behavior described here (and in #4). The entities are not even greyed out, showing them as unlocked and giving you the option to lock them, which will wake up the car unnecessarily. As an example (see the image in #4), the frunk and trunk locks have this problem.

An example of what we could do if these changes are implemented: we could check the battery (or range) sensors, without waking up the car, to have a rough estimate of how much battery (or range) the car has. I know that there's a drain in the battery even in sleep mode, and it could be as much as 1-2% per day. Nonetheless, being able to have a rough estimate without having to wake up the car is very helpful.

**Comment by alandtse** [comment]
Thanks. This is a bug. It used to maintain the data.

**Comment by fcastilloec** [comment]
That's good to know. I think this bug also exist with the original Tesla integration. Do you think it's a good idea to open an issue there too? I'm not using that integration but just in case

**Comment by alandtse** [comment]
If you want. I'm the only one maintaining both.

**Comment by alandtse** [comment]
I'm actually not seeing this behavior. Tesla was having general connectivity issues a few days ago. Are you still seeing this? Please generate logs for teslajsonpy (but scrub for personal data) before posting.

**Comment by fcastilloec** [comment]
I disable the integration because of this problem. I'll re-enable it and see if it was a Tesla issue rather than your integration, and I'll report back when I have some time.

**Comment by fcastilloec** [comment]
I've re-enabled this integration and this seems to be fixed. I also updated HA to the latest version which I saw included some fixes for the included Tesla integration, which is also working without any issues.
It seems the problem might have with Tesla itself as you mentioned. There is one thing that I'd like to see implemented, and I'll open a new feature request for it. For now, I'll close this issue.

**Comment by fcastilloec** [comment]
@alandtse  Actually, I just saw this behavior again. I can reproduce it when Home Assistant is restarted, then none of the old states are kept. I can see on the details when was the last time it was updated, but the values are gone. I'm guessing this might be a limitation of Home Assistant itself and not this integration but if it's not, feel free to reopen this issue.

**Comment by alandtse** [comment]
On start-up it will not restore state. HA rejected that behavior for Tesla like 2 or 3 years ago.

**Comment by fcastilloec** [comment]
Too bad, I try not to restart HA, but sometimes there's no way around it. Usually after updates, or if I'm messing with the configuration, a restart is required and there's no way around it.
A suggestion, maybe mention this somewhere in the README? I'm sure I might not be the only one that encounters this and thinks there's an issue, but who knows....

**Comment by alandtse** [comment]
There's an option to force cars awake to update the info.
