### ISSUE TITLE
Need to reinstall v3.19.11

### ISSUE THREAD

**Issue by ingo916** [alandtse/tesla#915]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

v3.19.11

### Version of the Powerwall Gateway software

I dont have the powerwall just solar

### Model

no pwerwall

### Current Behavior

Tesla custom integration v3.20.0 will not work withHomeAssistant. I need to manually reinstall version v3.19.11

### Expected Behavior

would like the integration to work with home assistant with Tesla solar and no powerwall. This is working with version 3.19.11

### Debug logs

```true
no logs intigration not working
```

**Comment by alandtse** [comment]
This is a HACS setting and not related to this component at all.
![image](https://github.com/alandtse/tesla/assets/7086117/0ed765d7-2b6f-48c4-87e2-54841429f2d5)
