### ISSUE TITLE
Powerwall & Car Issue: Values appear to not be updating unless integration is reloaded

### ISSUE THREAD

**Issue by monkga1** [alandtse/tesla#922]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

v3.20.4

### Version of the Powerwall Gateway software

24.4.0

### Model

2

### Current Behavior

Some time today (but after charge % being not available) sensor values (also for car) do not appear to be updating.

### Expected Behavior

Updated as per polling interval (660s)

### Debug logs

```true
Not sure how to do this.
```

### Anything else?

Example...

![Screenshot 2024-03-22 165342](https://github.com/alandtse/tesla/assets/122105091/adc33fdd-af0c-48aa-aa15-1203806d34f3)

**Comment by hogsterbogster** [comment]
Seeing the same behaviour here. Also using the controls like changing the Backup Reserve or changing the Operation Mode (Self-Powered, Time-Based Control, etc) aren’t working at all 😢

Are there any known workarounds for this?

Many thanks,

David

**Comment by tj1816** [comment]
Same issue here

**Comment by barryperfect** [comment]
I have the same issue. 

As far as a I can tell commands that are sent are actioned, but the status is not being updated in response to these commands or any changes made via the Tesla App, unless you reload the integration.

e.g. I can set my Powerwall to Self Powered Mode, either using the integration, or the Tesla App but this change is not reflected in the integration status, it still says Time Based.

As above this seems to have happened since my Powerwall had a firmware update last Thursday (to 24.4.0 0fe780c9)

**Comment by barryperfect** [comment]
> I have the same issue.
> 
> As far as a I can tell commands that are sent are actioned, but the status is not being updated in response to these commands or any changes made via the Tesla App, unless you reload the integration.
> 
> e.g. I can set my Powerwall to Self Powered Mode, either using the integration, or the Tesla App but this change is not reflected in the integration status, it still says Time Based.
> 
> As above this seems to have happened since my Powerwall had a firmware update last Thursday (to 24.4.0 0fe780c9)

It may be early days but I think the workaround from [
](https://github.com/alandtse/tesla/issues/919#issuecomment-2015548967)

Seems to make my data update again

**Comment by monkga1** [comment]
Seems that car part is updating again correctly but not PW part still.  I haven't made any changes.

**Comment by sdrake001** [comment]
I also have the same issue, none of the sensors appear to be working, battery, battery remaining, load power, solar power etc This seems to have happened since installing HA core 2024.3.1 to 2024.3.3 yesterday.

**Comment by barryperfect** [comment]
> I also have the same issue, none of the sensors appear to be working, battery, battery remaining, load power, solar power etc This seems to have happened since installing HA core 2024.3.1 to 2024.3.3 yesterday.

Not sure if you saw my post further up, but doing this workaround seems to have resolved the values not updating. I decided to move over to the HA inbuilt Powerwall Integration for monitoring the battery level and reserve until the custom integration is updated and works again.

[https://github.com/alandtse/tesla/issues/922#issuecomment-2019693873]

**Comment by sdrake001** [comment]
Thanks Barry! I too have also installed the HA Tesla Powerwall integration and I have some data appearing but it doesn't match what is showing in the Tesla app.
I am a complete novice at HA and have to be honest I can't follow all the suggestions that are being made to edit .yaml 😬 Looks like I will have to keep my fingers crossed for a fix.
________________________________

**Comment by ZaeGitHub** [comment]
I am also having this problem, but the bigger issue for me is that none of the APF entries are updating, such as APF Generation Entity. They do not update without a manual reload.. Unfortunately, the Tesla Powerwall integration will not help with this, since I use it to track things like real-time solar generation.

**Comment by ziptbm** [comment]
Is this integration going unavailable at all for you?  Or is it just not updating?

**Comment by ZaeGitHub** [comment]
> Is this integration going unavailable at all for you? Or is it just not updating?

It doesn't update unless you make the changes listed above.
https://github.com/alandtse/tesla/issues/922#issuecomment-2019693873

**Comment by ziptbm** [comment]
> > Is this integration going unavailable at all for you? Or is it just not updating?
> 
> It doesn't update unless you make the changes listed above. [#919 (comment)](https://github.com/alandtse/tesla/issues/919#issuecomment-2019693873)

Both.  I'm seeing them not update and also all sensors go unavailable after a certain amount of time.  I'm catching up and trying to figure out if it's related to this issue, fleet api (I only have powerwall), or something else.  I just commented out line 94 per that workaround.

**Comment by coddipm** [comment]
Same problem here. Powerwall data will only update if the integration is reloaded. Spent an hour with Tesla tech support and they claimed nothing changed on their end, but not sure I buy that.

**Comment by ziptbm** [comment]
I've seen this consistently now for the last week and half, but wasn't sure if it was related to this issue per my comments above since I only have Powerwalls and do not have cars.  Either way, https://github.com/alandtse/tesla/issues/937 confirmed this is the same issue.

Commenting out line 94 did not work for me as the sensors report values after a reload/reboot, but then stop after a period of time and become unavailable.

Does this mean it needs to use the FleetAPI?  Even though there are no cars?

**Comment by gdotp01** [comment]
> I also have the same issue, none of the sensors appear to be working, battery, battery remaining, load power, solar power etc This seems to have happened since installing HA core 2024.3.1 to 2024.3.3 yesterday.

I think I’ve seen this as well. I updated HA yesterday and the sensors have stopped reporting. It looks like changing the battery reserve is however still working

**Comment by gdotp01** [comment]
As per above

“It doesn't update unless you make the changes listed above. https://github.com/alandtse/tesla/issues/919#issuecomment-2019693873”

this did not work for me. The values do update once when it’s reloaded but don’t refresh after that.

**Comment by skipishere** [comment]
Is this still an issue? There have been some changes around this area that might have resolved it.

**Comment by monkga1** [comment]
It seems to be resolved.  I will try and close it.

Regards
Gav
________________________________
