### ISSUE TITLE
Powerwall Issue: Unable to add account above 3.19.11 version

### ISSUE THREAD

**Issue by rm-rf-asterisk** [alandtse/tesla#936]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

3.20.5

### Version of the Powerwall Gateway software

23.44.0

### Model

2

### Current Behavior

I currently use 3.19.11 but any version up to 3.20.5 I am unable to authenticate

### Expected Behavior

I add my username and refresh token i expect it to load.  
Instead i get "Unknown error occurred"
The error message in the logs points to api_proxy_cert but I did not check the "use fleet API" checkbox.
![Screenshot 2024-03-31 at 11 52 51 AM](https://github.com/alandtse/tesla/assets/147197487/2f237ab0-3287-42e3-a9f8-e2bd801a19af)

### Debug logs

```true
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 11:50:27 AM (1 occurrences)
Last logged: 11:50:27 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 25, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 68, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 197, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 405, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 502, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/config_flow.py", line 96, in async_step_credentials
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/config_flow.py", line 260, in validate_input
    controller = TeslaAPI(
                 ^^^^^^^^^
TypeError: Controller.__init__() got an unexpected keyword argument 'api_proxy_cert'
```

**Comment by llamafilm** [comment]
This error sounds like you choose the Fleet API checkbox. Can you delete the integration, then restart home assistant, then install the latest version and post the log again?

**Comment by rm-rf-asterisk** [comment]
> This error sounds like you choose the Fleet API checkbox. Can you delete the integration, then restart home assistant, then install the latest version and post the log again?

That is what i thought but i am confirming I unchecked the fleet box. You would not see the screenshot i shared if i did check it, as it would ask for fleet api specifics right?

**Comment by llamafilm** [comment]
Actually, it’s not proven by the screenshot because the additional text fields would be below that. Also - if you first tried with API Proxy, and then reconfigured it to do without, then it may still expect those values even though you don’t see the fields in this dialog. That’s why I suggest to fully remove and restart in between attempts.

**Comment by rm-rf-asterisk** [comment]
> Actually, it’s not proven by the screenshot because the additional text fields would be below that. Also - if you first tried with API Proxy, and then reconfigured it to do without, then it may still expect those values even though you don’t see the fields in this dialog. That’s why I suggest to fully remove and restart in between attempts.

The screen shot i provided "WITH" fleet checkbox would look like this.
![Screenshot 2024-03-31 at 12 08 27 PM](https://github.com/alandtse/tesla/assets/147197487/3232db69-5341-4ac8-8942-7b7e9ed17b1a)

Note how my screenshot looks
![Screenshot 2024-03-31 at 11 52 51 AM](https://github.com/alandtse/tesla/assets/147197487/a9afd954-1f18-46cc-8057-bc5a947ffe4f)

So i can see the confusion if there was some sort of html loading error, but I am confirming once more this is not because I selected the checkbox.

Already did all the things like restarting and doing a fresh install. At the end only using 3.19.11 works for me.

**Comment by llamafilm** [comment]
Okay, got it.  Sorry I didn’t see the submit button in your first photo.  

are you using HAOS or some other installation method? I wonder if maybe you have an older version of teslajsonpy. In general, this integration needs to be paired with the right library version.

**Comment by rm-rf-asterisk** [comment]
> Okay, got it. Sorry I didn’t see the submit button in your first photo.
> 
> are you using HAOS or some other installation method? I wonder if maybe you have an older version of teslajsonpy. In general, this integration needs to be paired with the right library version.

I use HAOS and HACS, both are the latest versions. 
![Screenshot 2024-03-31 at 12 22 58 PM](https://github.com/alandtse/tesla/assets/147197487/b108aaf1-a702-4cf8-a5e7-139bbd2b266d)

Hope this helps

**Comment by llamafilm** [comment]
That sort of confirms my hunch, your library is too old.  It should be updated automatically after restarting Home Assistant.  I just checked on my system, with a clean install of tesla_custom from HACS, and the first time I try to add a device I see this in home-assistant.log:
```
2024-03-31 14:58:17.459 INFO (SyncWorker_53) [homeassistant.util.package] Attempting install of teslajsonpy==3.10.2
```

I'm not sure why this didn't work automatically for you.  You could try running [pipdeptree](https://pypi.org/project/pipdeptree/) to see if something depends on it.

If you have SSH access to the host (port 22222), you can upgrade the library inside the homeassistant container with `docker exec -it homeassistant pip install teslajsonpy --upgrade`.

**Comment by alandtse** [comment]
Try to add the component again. You don't have to complete the installation but it does a dependency install check every time you add.

**Comment by llamafilm** [comment]
Can you clarify exactly where is this `/homeassistant` directory you’re talking about? I don’t have that. My python modules are installed into a site-packages folder. I may have done something non-standard, I don’t remember. What version of HA are you running?

**Comment by rm-rf-asterisk** [comment]
So for me /homeassistant/teslajsonpy was mapped with /config/teslajsonpy 
I am not sure how it was put there but when i deleted /config/teslajsonpy and redid the install it worked, but I do see now the new teslajsonpy inside of /usr/local/lib/python3.12/site-packages/teslajsonpy with version 3.10.2

I personally never go into here, I just installed the advanced terminal with privileged mode to get this info otherwise anything i done had to be with the limited ha terminal

**Comment by alandtse** [comment]
That would only exist if you manually installed teslajsonpy into your config. You probably followed some old advice posted here by someone to manually copy teslajsonpy. We discourage it but random people suggest it to install a "fixed" version but then it locks you out from all updates.
