### ISSUE TITLE
vehicle rejected request: your public key has not been paired with the vehicle.

### ISSUE THREAD

**Issue by DamWeg** [alandtse/tesla#960]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

3.21.0

### Version of the Tesla car software

2024.8.9

### Model

Model 3

### Current Behavior

Hello, I am following the instructions and everything seems to be configured correctly—it fetches data about the car, but unfortunately, when executing actions, I get the error: "vehicle rejected request: your public key has not been paired with the vehicle." Of course, the fleet API key has been added to the car. Maybe someone has encountered a similar issue.

HTTP proxy installed
Domain with the public key exists
Generating token from HTTP proxy
Key added to the car
Maybe I should also send the key through Tesla's API so that they can register it and link it to the developer account. I've tried various solutions. I used a refresh token from the Tesla auth app on iOS as well, but unfortunately, it did not yield the expected results. I reset the car, removed the key, and added it again.

### Expected Behavior

I need help in solving this problem with the key.

### Debug logs

```true
2024-05-08 21:27:53.815 DEBUG (MainThread) [teslajsonpy.connection] 500: {"response":null,"error":"vehicle rejected request: your public key has not been paired with the vehicle","error_description":""}
```

**Comment by alandtse** [comment]
@llamafilm I'm thinking about asking people to go directly to your [repo](https://github.com/llamafilm/tesla-http-proxy-addon) for Proxy issues. However, let me know if you feel better just addressing them here since this is the most natural location for HA users.

**Comment by DamWeg** [comment]
In the Tesla API documentation, I found information about registering a CSR key with Tesla, which may take about a week. I sent such a key directly through the Tesla API. Maybe this will help solve the problem with the key.

**Comment by llamafilm** [comment]
@alandtse yes I think it makes sense to track proxy issues over there.

@DamWeg if you're still having trouble, please open an issue at https://github.com/llamafilm/tesla-http-proxy-addon.  Also read the comments here to see if it helps: https://github.com/teslamotors/vehicle-command/issues/174
My guess if you re-ran the proxy setup again, overwriting the first key, so the easiest path forward is to delete all the addon files and start over.
