### ISSUE TITLE
New breaking change in HomeAssistant dev breaks integration due to removal of const values.

### ISSUE THREAD

**Issue by FMKaiba** [alandtse/tesla#97]
## Version of the custom_component
Version: 1.3.1 and Dev

## Configuration

```yaml
via Integration in UI
```

## Describe the bug

With new breaking change in this commit https://github.com/home-assistant/core/commit/51510c542a09c75587507369a1a496dc119d85ab#diff-07e20eb7c6560330f9774eb23343f5dd3002106bb8b6523ccb18d95857990d77

we get  Setup failed for tesla_custom: Unable to import component: cannot import name 'HTTP_UNAUTHORIZED' from 'homeassistant.const' (homeassistant/const.py)
due to the const being removed

## Debug log

```text

Logger: homeassistant.setup
Source: setup.py:178
First occurred: November 12, 2021, 20:13:21 (1 occurrences)
Last logged: November 12, 2021, 20:13:21

Setup failed for tesla_custom: Unable to import component: cannot import name 'HTTP_UNAUTHORIZED' from 'homeassistant.const' (/usr/lib/python3.9/site-packages/homeassistant/const.py)

```

**Comment by alandtse** [comment]
Use dev. It's already fixed there. #87

**Comment by FMKaiba** [comment]
Definatly fixed. Sorry, I do not think Home Assistant had actually rebooted as it mentioned when I tried out DEV.

It is solved in Dev

**Comment by alandtse** [comment]
No need to say sorry, I hadn't remembered it wasn't pushed yet.

**Comment by purcell-lab** [comment]
@alandtse I just upgraded to version | core-2021.12.0b1 on the beta channel, restarted/ rebooted and I am receiving the same error with the loading of the tesla custom component.


```
Logger: homeassistant.setup
Source: setup.py:153
First occurred: 4:52:22 PM (1 occurrences)
Last logged: 4:52:22 PM

Setup failed for tesla_custom: Unable to import component: cannot import name 'HTTP_UNAUTHORIZED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

## System Health

version | core-2021.12.0b1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.9.277-118
arch | aarch64
timezone | Australia/Sydney

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4380
Installed Version | 1.18.0
Stage | running
Available Repositories | 977
Installed Repositories | 30

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 15, 2021, 11:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.3 LTS
-- | --
update_channel | beta
supervisor_version | supervisor-2021.12.0
docker_version | 20.10.7
disk_total | 114.4 GB
disk_used | 53.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (3.7.0), Check Home Assistant configuration (3.9.0), Mosquitto broker (6.0.1), Terminal & SSH (9.2.1), File editor (5.3.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 8
views | 11
mode | storage

</details>

**Comment by purcell-lab** [comment]
Sorry, I see what is going on, the HACS error won't let me download the fixed tesla custom component.

I'll download manually.
