### ISSUE TITLE
Fleet API Proxy: reset/change misconfigured Proxy URL?

### ISSUE THREAD

**Issue by FFV21** [alandtse/tesla#970]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

v3.21.0

### Version of the Tesla car software

2024.14.6

### Model

Model 3

### Current Behavior

Because the owner API stopped working for me recently I set up a docker container running Fleet API Proxy this morning and have that working.

When I configuring this custom integration I did a stupid thing and made a mistake on the Proxy URL address.
I put in the external address https://tesla.xxxxxxxx.com (FQDN) instead of the internal proxy host address https://TeslaHTTPProxy:443.

Now when the integration launches it is looking for the misconfigured https://tesla.xxxxxxxx.com and as nothing is there it is obviously failing to set up.

Is there any way I can change the Proxy URL without deleting my account/car from the integration and starting over? 

I have so many automations based on this integration it would take forever to fix my stupid mistake.

Thank you!

### Expected Behavior

Would like to change the Proxy URL without deleting/reinstalling if possible.

### Debug logs

```true
2024-05-25 15:47:58.000 DEBUG (MainThread) [teslajsonpy.connection] Successfully refreshed oauth
2024-05-25 15:47:58.000 DEBUG (MainThread) [teslajsonpy.connection] get: https://tesla.xxxxxxxx.com/api/1/products {}
2024-05-25 15:47:58.180 DEBUG (MainThread) [teslajsonpy.connection] 502: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>tesla.xxxxxxxx.com | 502: Bad gateway</title>
```

### Anything else?

Docker Fleet API Proxy: https://github.com/iainbullock/tesla-http-proxy-docker v1.0.5
Docker HA Core version 2024.5.5

**Comment by FFV21** [comment]
Found it in /config/config/core.config_entries and changed the URL there.

**Comment by llamafilm** [comment]
FWIW, deleting and re-adding the car won’t break any automations, because the entity_id remains the same.
